---
title: "Datacleaningcode_ID"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
library(tidyverse)
#here are functions
#for temperature

resultconvert_celsius<-function(dat, variable, unit, out_unit) {
  dat$ResultMeasureValue[which(dat$CharacteristicName == variable & dat$ResultMeasure.MeasureUnitCode == unit)] <- (dat$ResultMeasureValue[which(dat$CharacteristicName == variable & dat$ResultMeasure.MeasureUnitCode == unit)] -32)* 5/9
  
dat$ResultMeasure.MeasureUnitCode[which(dat$CharacteristicName == variable & dat$ResultMeasure.MeasureUnitCode == unit)] <- out_unit

return(dat)
  
}


detectconvert_celsius<-function(dat, variable, unit, out_unit) {
  dat$DetectionQuantitationLimitMeasure.MeasureValue[which(dat$CharacteristicName == variable & dat$DetectionQuantitationLimitMeasure.MeasureUnitCode == unit)] <- (dat$DetectionQuantitationLimitMeasure.MeasureValue[which(dat$CharacteristicName == variable & dat$DetectionQuantitationLimitMeasure.MeasureUnitCode == unit)] * -32)*5/9
  
dat$DetectionQuantitationLimitMeasure.MeasureUnitCode[which(dat$CharacteristicName == variable & dat$DetectionQuantitationLimitMeasure.MeasureUnitCode == unit)] <- out_unit

return(dat)
  
}

#for all other conversions

resultconvert<-function(dat, variable, unit, out_unit, conv_factor) {
  dat$ResultMeasureValue[which(dat$CharacteristicName == variable & dat$ResultMeasure.MeasureUnitCode == unit)] <- dat$ResultMeasureValue[which(dat$CharacteristicName == variable & dat$ResultMeasure.MeasureUnitCode == unit)] * conv_factor
  
dat$ResultMeasure.MeasureUnitCode[which(dat$CharacteristicName == variable & dat$ResultMeasure.MeasureUnitCode == unit)] <- out_unit

return(dat)
  
}


detectconvert<-function(dat, variable, unit, out_unit, conv_factor) {
  dat$DetectionQuantitationLimitMeasure.MeasureValue[which(dat$CharacteristicName == variable & dat$DetectionQuantitationLimitMeasure.MeasureUnitCode == unit)] <- dat$DetectionQuantitationLimitMeasure.MeasureValue[which(dat$CharacteristicName == variable & dat$DetectionQuantitationLimitMeasure.MeasureUnitCode == unit)] * conv_factor
  
dat$DetectionQuantitationLimitMeasure.MeasureUnitCode[which(dat$CharacteristicName == variable & dat$DetectionQuantitationLimitMeasure.MeasureUnitCode == unit)] <- out_unit

return(dat)
  
}


`%notin%` <- Negate(`%in%`)

IDdatPull<-read.csv("~/Lagos Limno/ID_alldata_1975_to_2020.csv")

names(IDdatPull)

summary(IDdatPull)

#removing data that have Y's instead of keeping data that have N's

read.csv("~/Lagos Limno/list of unique parameters to remove.csv") -> remove_params #update this


data<- IDdatPull[IDdatPull$CharacteristicName %notin% remove_params$Unique.parameters,]
data<-data %>% mutate(obs_id = seq(1, nrow(data), 1))


# tdata1<-data %>% filter(!is.na(ResultDepthHeightMeasure.MeasureValue)) #identified specified depth samples
# 
# 
# tdata2<-data %>% filter(is.na(ResultDepthHeightMeasure.MeasureValue)) %>% filter(!is.na(ActivityTopDepthHeightMeasure.MeasureValue)) #these are potential integrated samples
# 
# unique(tdata2$SampleCollectionMethod.MethodName)
# method_name<-c("")
# 
# unique(tdata2$SampleCollectionMethod.MethodIdentifier)
# method_identifier<-c("")
# 
# unique(tdata2$SampleCollectionMethod.MethodIdentifierContext)
# method_context<-c("")
# 
# unique(tdata2$SampleCollectionEquipmentName)
# method_equipment<-c("")
# 
# tdata2<-tdata2 %>% filter(SampleCollectionMethod.MethodName %in% method_name | 
#                             SampleCollectionMethod.MethodIdentifier %in% method_identifier|
#                             SampleCollectionMethod.MethodIdentifierContext %in% method_context|
#                             SampleCollectionEquipmentName %in% method_equipment)  #all grab samples
# 
# tdata3<-data %>% filter(is.na(ResultDepthHeightMeasure.MeasureValue)) #identifying grab samples
# 
# unique(tdata3$SampleCollectionMethod.MethodName)
# method_name<-c("Grab sample  (dip)", "SRBC Standard Grab Sample Method", "Water Grab Sampling")
# 
# unique(tdata3$SampleCollectionMethod.MethodIdentifier)
# method_identifier<-c("GRAB-001") #all others were unknown - MBL-001, SP-001
# 
# unique(tdata3$SampleCollectionMethod.MethodIdentifierContext)
# method_context<-c("Grab sample","USGS parameter code 82398")
# 
# unique(tdata3$SampleCollectionEquipmentName)
# method_equipment<-c("Water Bottle", "Open-Mouth Bottle", "Van Dorn Bottle")
# 
# tdata3<-tdata3 %>% filter(SampleCollectionMethod.MethodName %in% method_name | 
#                             SampleCollectionMethod.MethodIdentifier %in% method_identifier|
#                             SampleCollectionMethod.MethodIdentifierContext %in% method_context|
#                             SampleCollectionEquipmentName %in% method_equipment)  #all grab samples
# 
# data2<-rbind(tdata1, tdata2, tdata3)
# rm(tdata1)
# rm(tdata2)
# rm(tdata3)
# 
# tdata4<-data %>% filter(obs_id %notin% data2$obs_id)#created object to look at all data not in datata2
# 
# unique(tdata4$CharacteristicName)
# secchiparams<-c("Depth, Secchi disk depth") #pulled out secchi data cuz it may not have depth data
# 
# tdata4<-tdata4 %>% filter(CharacteristicName %in% secchiparams) #filtered out only the secchi vars
# data<-rbind(data2, tdata4) #combined everything back together

#will need to check for each state (the depth data)

#rm(tdata4)
#rm(data2)
#data<-data %>% select(-obs_id)
#rm(MDdatPull)
#unique(data$CharacteristicName)

str(data$ResultMeasureValue)
sum(is.na(data$ResultMeasureValue))
data1<-data %>% filter(!is.na(ResultMeasureValue))
data2<-data %>% filter(!is.na(DetectionQuantitationLimitMeasure.MeasureValue)) %>% filter(is.na(ResultMeasureValue))
data3<-rbind(data1, data2)
data<-data3

rm(data1, data2, data3)


#unique organizations
unique(data$OrganizationIdentifier) #19 organizations data
table(data$OrganizationFormalName) #tells us number of obvs in each organization




#looking at activity type codes #getting rid of quality control vars
unique(data$ActivityTypeCode)
activitytype_keep<-c("Quality Control Sample-Field Blank", "Quality Control Sample-Field Replicate", "Quality Control Field Replicate Msr/Obs")
data<-data[which(data$ActivityTypeCode %notin% activitytype_keep),]
unique(data$ActivityTypeCode)

#manually checking these columns to see if these is data we keep or can drop

unique(data$SubjectTaxonomicName) #expected it to be na - to make sure nothing we need is in there
unique(data$SampleTissueAnatomyName) #also NA's - expected
unique(data$ActivityMediaSubdivisionName)
#only keeping subdivision name with surface water and NA's - dropping everything else 
data<-data %>% filter(ActivityMediaSubdivisionName == "Surface Water" | is.na(ActivityMediaSubdivisionName))
unique(data$ActivityMediaSubdivisionName)

unique(data$ResultStatusIdentifier)
unique(data$ResultValueTypeName)


unique(data$ResultDetectionConditionText)
#filtered out vars we don't need in resultsdetection condition text - did it in multistep because R doesn't handle multiple OR statements well


data<-data %>% filter(ResultDetectionConditionText != "Systematic Contamination" | is.na(ResultDetectionConditionText))

data<-data %>% filter(is.na(ResultDetectionConditionText) | ResultDetectionConditionText != "Not Reported")
unique(data$ResultDetectionConditionText)



unique(data$ResultSampleFractionText)

data<-data %>% filter(is.na(ResultSampleFractionText) | ResultSampleFractionText != "Bed Sediment")
unique(data$ResultSampleFractionText)


data<-data %>% select(-ActivityMediaName, -ActivityMediaSubdivisionName, -ActivityStartTime.Time, -ActivityStartTime.TimeZoneCode, -ActivityEndTime.Time, -ActivityEndTime.TimeZoneCode, -SampleAquifer, -HydrologicCondition, -HydrologicEvent, -SubjectTaxonomicName, -SampleTissueAnatomyName, -LaboratoryName, -AnalysisStartDate, -PreparationStartDate)

unique(data$ActivityDepthHeightMeasure.MeasureUnitCode) #has ft, feet, and m - need to convert the ones with ft and feet 
unique(data$ActivityTopDepthHeightMeasure.MeasureUnitCode) #all in m - no conversion needed
unique(data$ActivityBottomDepthHeightMeasure.MeasureUnitCode) #all in m - no conversion needed
unique(data$ResultDepthHeightMeasure.MeasureUnitCode) #all in m - no conversion needed


data$ActivityDepthHeightMeasure.MeasureValue<-ifelse(data$ActivityDepthHeightMeasure.MeasureUnitCode == "ft", data$ActivityDepthHeightMeasure.MeasureValue*0.3048, data$ActivityDepthHeightMeasure.MeasureValue)

data$ActivityDepthHeightMeasure.MeasureValue<-ifelse(data$ActivityDepthHeightMeasure.MeasureUnitCode == "feet", data$ActivityDepthHeightMeasure.MeasureValue*0.3048, data$ActivityDepthHeightMeasure.MeasureValue)


data$ActivityDepthHeightMeasure.MeasureUnitCode<-"m"


data$ResultDepthHeightMeasure.MeasureValue<-ifelse(data$ResultDepthHeightMeasure.MeasureUnitCode == "ft", data$ResultDepthHeightMeasure.MeasureValue*0.3048, data$ResultDepthHeightMeasure.MeasureValue)


data$ResultDepthHeightMeasure.MeasureUnitCode<-"m"



#check
unique(data$ActivityDepthHeightMeasure.MeasureUnitCode)
unique(data$ResultDepthHeightMeasure.MeasureUnitCode)

```

```{r}
#list of unique parameters
#unique(data$CharacteristicName)
#write.table(unique(data$CharacteristicName), "unique_parameters_ID.csv", row.names = FALSE)

```


```{r}

###creating new columns to preserve original pulled data

data$source_parameter<- data$CharacteristicName
data$source_value<- data$ResultMeasureValue
data$source_unit <- data$ResultMeasure.MeasureUnitCode
data$detectionlimit_legacy<- data$DetectionQuantitationLimitMeasure.MeasureValue
data$detectionlimit_unit_legacy<- data$DetectionQuantitationLimitMeasure.MeasureUnitCode

```


```{r}
#Depth
unique(data$CharacteristicName)
Depth_params<-c("Depth, data-logger (non-ported)", "Depth", "Depth, data-logger (ported)", "Depth, bottom") #only values for depth
data_depth<-data[data$CharacteristicName%in%Depth_params,] #want to match all records to the vector we created above 
unique(data_depth$ResultSampleFractionText)
temp<-data_depth %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep
#fractionkeep<-c("Total") #only want total aluminum
#data_aluminum_total<-data_aluminum_total[which(data_aluminum_total$ResultSampleFractionText %in% fractionkeep | is.na(data_aluminum_total$ResultSampleFractionText)),] #keeping if it's ones we chose or NA
#unique(data_aluminum_total$ResultSampleFractionText)

###create dataset to check for non numeric objects in dataset
temp<-data_depth %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change
data_depth<-data_depth %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_depth$ResultMeasure.MeasureUnitCode) #checked units #change ft to m
unique(data_depth$DetectionQuantitationLimitMeasure.MeasureUnitCode) #checked units #all NA's no change needed

#working with Depth, data-logger (non-ported)

temp<-data_depth %>% filter(CharacteristicName == "Depth, data-logger (non-ported)")
unique(temp$ResultMeasure.MeasureUnitCode) #convert ft to m
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)

data_depth<-resultconvert(dat = data_depth, variable = "Depth, data-logger (non-ported)", unit = "ft", out_unit = "m", conv_factor = 0.3048)


#working with Depth

temp<-data_depth %>% filter(CharacteristicName == "Depth")
unique(temp$ResultMeasure.MeasureUnitCode) #convert ft to m
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode) #convert ft to m

data_depth<-resultconvert(dat = data_depth, variable = "Depth", unit = "ft", out_unit = "m", conv_factor = 0.3048)
data_depth<-detectconvert(dat = data_depth, variable = "Depth", unit = "ft", out_unit = "m", conv_factor = 0.3048)



#working with Depth, data-logger (ported)

temp<-data_depth %>% filter(CharacteristicName == "Depth, data-logger (ported)")
unique(temp$ResultMeasure.MeasureUnitCode) 
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode) #no conversions needed for either - all in m


#working with Depth, bottom

temp<-data_depth %>% filter(CharacteristicName == "Depth, bottom")
unique(temp$ResultMeasure.MeasureUnitCode) 
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)


data_depth<-resultconvert(dat = data_depth, variable = "Depth, bottom", unit = "ft", out_unit = "m", conv_factor = 0.3048)



data_depth$CharacteristicName<-"Depth"  #set all depth params as depth

#done
```


```{r}
#secchi

unique(data$CharacteristicName)

Secchi_params<-c("Depth, Secchi disk depth") #values for secchi
data_secchi<-data[data$CharacteristicName%in%Secchi_params,]
unique(data_secchi$ResultSampleFractionText)


###create dataset to check for non numeric objects in dataset
temp<-data_secchi %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change
data_secchi<-data_secchi %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_secchi$ResultMeasure.MeasureUnitCode) #checked units
unique(data_secchi$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#all in "m" - no conversions needed

data_secchi$CharacteristicName<-"Secchi"  #set all secchi params as secchi


#done
```


```{r}
#calcium

Calcium_params<-c("Calcium") #only values for calcium
data_calcium<-data[data$CharacteristicName%in%Calcium_params,] #want to match all records to the vector we created above which have calcium
unique(data_calcium$ResultSampleFractionText)
fractionkeep<-c("Dissolved")
data_calcium<-data_calcium[which(data_calcium$ResultSampleFractionText %in% fractionkeep | is.na(data_calcium$ResultSampleFractionText)),] #keeping if it's ones we chose or NA
unique(data_calcium$ResultSampleFractionText)
temp<-data_calcium %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep



###create dataset to check for non numeric objects in dataset
temp<-data_calcium %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change
data_calcium<-data_calcium %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_calcium$ResultMeasure.MeasureUnitCode) #checked units
unique(data_calcium$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#convert ug/l to mg/l
data_calcium<-resultconvert(dat = data_calcium, variable = "Calcium", unit = "ug/l", out_unit = "mg/l", conv_factor = 0.001)



data_calcium$CharacteristicName<-"Calcium, dissolved"


#COMPLETED
```

```{r}
#aluminum total

Aluminum_params<-c("Aluminum") #only values for aluminum
data_aluminum_total<-data[data$CharacteristicName%in%Aluminum_params,] #want to match all records to the vector we created above which have calcium
unique(data_aluminum_total$ResultSampleFractionText)
fractionkeep<-c("Total")
data_aluminum_total<-data_aluminum_total[which(data_aluminum_total$ResultSampleFractionText %in% fractionkeep | is.na(data_aluminum_total$ResultSampleFractionText)),] #keeping if it's ones we chose or NA
unique(data_aluminum_total$ResultSampleFractionText)
temp<-data_aluminum_total %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep



###create dataset to check for non numeric objects in dataset
temp<-data_aluminum_total %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change
data_aluminum_total<-data_aluminum_total %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_aluminum_total$ResultMeasure.MeasureUnitCode) #checked units
unique(data_aluminum_total$DetectionQuantitationLimitMeasure.MeasureUnitCode) #checked units - all NA's - won't have to convert any detection limits

#already in ug/l - no coversions needed
data_aluminum_total$CharacteristicName<-"Aluminum, total"

#completed


```


```{r}
#aluminum dissolved

Aluminum_params<-c("Aluminum") #only values for aluminum
data_aluminum_dissolved<-data[data$CharacteristicName%in%Aluminum_params,] #want to match all records to the vector we created above which have calcium
unique(data_aluminum_dissolved$ResultSampleFractionText)
fractionkeep<-c("Dissolved")
data_aluminum_dissolved<-data_aluminum_dissolved[which(data_aluminum_dissolved$ResultSampleFractionText %in% fractionkeep | is.na(data_aluminum_dissolved$ResultSampleFractionText)),] #keeping if it's ones we chose or NA
unique(data_aluminum_dissolved$ResultSampleFractionText)
temp<-data_aluminum_dissolved %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep



###create dataset to check for non numeric objects in dataset
temp<-data_aluminum_dissolved %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change
data_aluminum_dissolved<-data_aluminum_dissolved %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_aluminum_dissolved$ResultMeasure.MeasureUnitCode) #checked units
unique(data_aluminum_dissolved$DetectionQuantitationLimitMeasure.MeasureUnitCode) #checked units - all NA's - won't have to convert any detection limits

#units in mg/l - convert to ug/l


data_aluminum_dissolved<-resultconvert(dat = data_aluminum_dissolved, variable = "Aluminum", unit = "mg/l", out_unit = "ug/l", conv_factor = 1000)
data_aluminum_dissolved<-detectconvert(dat = data_aluminum_dissolved, variable = "Aluminum", unit = "mg/l", out_unit = "ug/l", conv_factor = 1000)


data_aluminum_dissolved$CharacteristicName<-"Aluminum, dissolved"


#completed


```


```{r}
#mercury total


Mercury_params<-c("Mercury") #only values for mercury
data_mercury_total<-data[data$CharacteristicName%in%Mercury_params,] #want to match all records to the vector we created above which have calcium
unique(data_mercury_total$ResultSampleFractionText)
temp<-data_mercury_total %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep
fractionkeep<-c("Total")
data_mercury_total<-data_mercury_total[which(data_mercury_total$ResultSampleFractionText %in% fractionkeep | is.na(data_mercury_total$ResultSampleFractionText)),] 
unique(data_mercury_total$ResultSampleFractionText)

#keeping if it's ones we chose or NA


###create dataset to check for non numeric objects in dataset
temp<-data_mercury_total %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change #found 7 objects - all NA's - safe to convert
data_mercury_total<-data_mercury_total %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_mercury_total$ResultMeasure.MeasureUnitCode) #checked units
unique(data_mercury_total$DetectionQuantitationLimitMeasure.MeasureUnitCode)#checked units - same as resultmeasurevalues

#convert ug/l and mg/l to ng/l


data_mercury_total<-resultconvert(dat = data_mercury_total, variable = "Mercury", unit = "mg/l", out_unit = "ng/l", conv_factor = 1000000)
data_mercury_total<-detectconvert(dat = data_mercury_total, variable = "Mercury", unit = "mg/l", out_unit = "ng/l", conv_factor = 1000000)

data_mercury_total<-resultconvert(dat = data_mercury_total, variable = "Mercury", unit = "ug/l", out_unit = "ng/l", conv_factor = 1000)
data_mercury_total<-detectconvert(dat = data_mercury_total, variable = "Mercury", unit = "ug/l", out_unit = "ng/l", conv_factor = 1000)


data_mercury_total$CharacteristicName<-"Mercury, total"

#completed

```


```{r}
#mercury dissolved


Mercury_params<-c("Mercury") #only values for mercury
data_mercury_dissolved<-data[data$CharacteristicName%in%Mercury_params,] #want to match all records to the vector we created above which have calcium
unique(data_mercury_dissolved$ResultSampleFractionText)
temp<-data_mercury_dissolved %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep
fractionkeep<-c("Dissolved")
data_mercury_dissolved<-data_mercury_dissolved[which(data_mercury_dissolved$ResultSampleFractionText %in% fractionkeep | is.na(data_mercury_dissolved$ResultSampleFractionText)),] 
unique(data_mercury_dissolved$ResultSampleFractionText)



###create dataset to check for non numeric objects in dataset
temp<-data_mercury_dissolved %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change #found 7 objects - all NA's - safe to convert
data_mercury_dissolved<-data_mercury_dissolved %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_mercury_dissolved$ResultMeasure.MeasureUnitCode) #checked units
unique(data_mercury_dissolved$DetectionQuantitationLimitMeasure.MeasureUnitCode)#checked units - same as resultmeasurevalues
#detection limit and result measure value - in ug/l - change to ng/l
data_mercury_dissolved<-resultconvert(dat = data_mercury_dissolved, variable = "Mercury", unit = "ug/l", out_unit = "ng/l", conv_factor = 1000)
data_mercury_dissolved<-detectconvert(dat = data_mercury_dissolved, variable = "Mercury", unit = "ug/l", out_unit = "ng/l", conv_factor = 1000)


data_mercury_dissolved$CharacteristicName<-"Mercury, total dissolved"


#completed

```



```{r}
#methylmercury total #0 values for this

# 
# methylmercury_params<-c("Methylmercury(1+)") #only values for mercury
# data_methylmercury_total<-data[data$CharacteristicName%in%methylmercury_params,] #want to match all records to the vector we created above which have calcium
# unique(data_methylmercury_total$ResultSampleFractionText)
# temp<-data_methylmercury_total %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep
# fractionkeep<-c("Total")
# data_methylmercury_total<-data_methylmercury_total[which(data_methylmercury_total$ResultSampleFractionText %in% fractionkeep | is.na(data_methylmercury_total$ResultSampleFractionText)),] 
# unique(data_methylmercury_total$ResultSampleFractionText)
# 
# #keeping if it's ones we chose or NA
# 
# 
# ###create dataset to check for non numeric objects in dataset
# temp<-data_methylmercury_total %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change #found 7 objects - all NA's - safe to convert
# data_methylmercury_total<-data_methylmercury_total %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA
# 
# unique(data_methylmercury_total$ResultMeasure.MeasureUnitCode) #checked units
# unique(data_methylmercury_total$DetectionQuantitationLimitMeasure.MeasureUnitCode)#checked units - same as resultmeasurevalues
# 
# #convert ug/l and mg/l to ng/l
# 
# 
# data_methylmercury_total<-resultconvert(dat = data_methylmercury_total, variable = "Mercury", unit = "mg/l", out_unit = "ng/l", conv_factor = 1000000)
# data_methylmercury_total<-detectconvert(dat = data_methylmercury_total, variable = "Mercury", unit = "mg/l", out_unit = "ng/l", conv_factor = 1000000)
# 
# data_methylmercury_total<-resultconvert(dat = data_methylmercury_total, variable = "Mercury", unit = "ug/l", out_unit = "ng/l", conv_factor = 1000)
# data_methylmercury_total<-detectconvert(dat = data_methylmercury_total, variable = "Mercury", unit = "ug/l", out_unit = "ng/l", conv_factor = 1000)
# 
# 
# data_methylmercury_total$CharacteristicName<-"Mercury, total"
# 
# #completed

```


```{r}
#methylmercury dissolved


methylmercury_params<-c("Methylmercury(1+)") #only values for mercury
data_methylmercury_dissolved<-data[data$CharacteristicName%in%methylmercury_params,] #want to match all records to the vector we created above which have calcium
unique(data_methylmercury_dissolved$ResultSampleFractionText)
temp<-data_methylmercury_dissolved %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep
fractionkeep<-c("Dissolved")
data_methylmercury_dissolved<-data_methylmercury_dissolved[which(data_methylmercury_dissolved$ResultSampleFractionText %in% fractionkeep | is.na(data_methylmercury_dissolved$ResultSampleFractionText)),] 
unique(data_methylmercury_dissolved$ResultSampleFractionText)



###create dataset to check for non numeric objects in dataset
temp<-data_methylmercury_dissolved %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change #found 7 objects - all NA's - safe to convert
data_methylmercury_dissolved<-data_methylmercury_dissolved %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_methylmercury_dissolved$ResultMeasure.MeasureUnitCode) #checked units
unique(data_methylmercury_dissolved$DetectionQuantitationLimitMeasure.MeasureUnitCode)#checked units - same as resultmeasurevalues

#all in ng/l - no conversions needed

#detection limit and result measure value - in ug/l - change to ng/l

data_methylmercury_dissolved$CharacteristicName<-"Methylmercury, dissolved"


#completed

```




```{r}
#Magnesium

Magnesium_params<-c("Magnesium") #only values for magnesium
data_magnesium<-data[data$CharacteristicName%in%Magnesium_params,] #want to match all records to the vector we created above which have calcium
unique(data_magnesium$ResultSampleFractionText)
fractionkeep<-c("Dissolved")
data_magnesium<-data_magnesium[which(data_magnesium$ResultSampleFractionText %in% fractionkeep | is.na(data_magnesium$ResultSampleFractionText)),] #keeping if it's ones we chose or NA
unique(data_magnesium$ResultSampleFractionText)
temp<-data_magnesium %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep



###create dataset to check for non numeric objects in dataset
temp<-data_magnesium %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change
data_magnesium<-data_magnesium %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_magnesium$ResultMeasure.MeasureUnitCode) #checked units
unique(data_magnesium$DetectionQuantitationLimitMeasure.MeasureUnitCode) #checked units



data_magnesium<-resultconvert(dat = data_magnesium, variable = "Magnesium", unit = "ug/l", out_unit = "mg/l", conv_factor = 0.001)



data_magnesium$CharacteristicName<-"Magnesium, dissolved"


#completed
```

```{r}
#selenium total

Selenium_params<-c("Selenium") #only values for selenium
data_selenium_total<-data[data$CharacteristicName%in%Selenium_params,] #want to match all records to the vector we created above which have calcium
unique(data_selenium_total$ResultSampleFractionText)
temp<-data_selenium_total %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep
fractionkeep<-c("Total")
data_selenium_total<-data_selenium_total[which(data_selenium_total$ResultSampleFractionText %in% fractionkeep | is.na(data_selenium_total$ResultSampleFractionText)),]
unique(data_selenium_total$ResultSampleFractionText)


###create dataset to check for non numeric objects in dataset
temp<-data_selenium_total %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change # 1 NA - can change
data_selenium_total<-data_selenium_total %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_selenium_total$ResultMeasure.MeasureUnitCode)#checked units
unique(data_selenium_total$DetectionQuantitationLimitMeasure.MeasureUnitCode)


data_selenium_total$CharacteristicName<-"Selenium, total"


#units matched - all ug/l - this is lagos units

#completed
```


```{r}
#selenium dissolved

Selenium_params<-c("Selenium") #only values for selenium
data_selenium_dissolved<-data[data$CharacteristicName%in%Selenium_params,] #want to match all records to the vector we created above which have calcium
unique(data_selenium_dissolved$ResultSampleFractionText)
temp<-data_selenium_dissolved %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep
fractionkeep<-c("Dissolved")
data_selenium_dissolved<-data_selenium_dissolved[which(data_selenium_dissolved$ResultSampleFractionText %in% fractionkeep | is.na(data_selenium_dissolved$ResultSampleFractionText)),] 
unique(data_selenium_dissolved$ResultSampleFractionText)


###create dataset to check for non numeric objects in dataset
temp<-data_selenium_dissolved %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change # 1 NA - can change
data_selenium_dissolved<-data_selenium_dissolved %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_selenium_dissolved$ResultMeasure.MeasureUnitCode)#checked units
unique(data_selenium_dissolved$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#selenium needs to be in ug/l - result values are in ug/l - detection limits has ug/l and mg/l - need to convert mg/l to ug/l

data_selenium_dissolved$CharacteristicName<-"Selenium, dissolved"


#units matched - all ug/l - this is lagos units

#completed
```


```{r}
#arsenic total

Arsenic_params<-c("Arsenic") #only values for arsenic
data_arsenic_total<-data[data$CharacteristicName%in%Arsenic_params,] #want to match all records to the vector we created above which have calcium
unique(data_arsenic_total$ResultSampleFractionText)
temp<-data_arsenic_total %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep
fractionkeep<-c("Total")
data_arsenic_total<-data_arsenic_total[which(data_arsenic_total$ResultSampleFractionText %in% fractionkeep | is.na(data_arsenic_total$ResultSampleFractionText)),]
unique(data_arsenic_total$ResultSampleFractionText)



###create dataset to check for non numeric objects in dataset
temp<-data_arsenic_total %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change
data_arsenic_total<-data_arsenic_total %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_arsenic_total$ResultMeasure.MeasureUnitCode)#checked units
unique(data_arsenic_total$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#need to change resultmeasure value and detection limits from mg/l to ug/l- lagos units 


data_arsenic_total<-resultconvert(dat = data_arsenic_total, variable = "Arsenic", unit = "mg/l", out_unit = "ug/l", conv_factor = 1000)
data_arsenic_total<-detectconvert(dat = data_arsenic_total, variable = "Arsenic", unit = "mg/l", out_unit = "ug/l", conv_factor = 1000)

data_arsenic_total$CharacteristicName<-"Arsenic, total"


#completed

```

```{r}
#arsenic dissolved

Arsenic_params<-c("Arsenic") #only values for arsenic
data_arsenic_dissovled<-data[data$CharacteristicName%in%Arsenic_params,] #want to match all records to the vector we created above which have calcium
unique(data_arsenic_dissovled$ResultSampleFractionText)
temp<-data_arsenic_dissovled %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep
fractionkeep<-c("Dissolved")
data_arsenic_dissovled<-data_arsenic_dissovled[which(data_arsenic_dissovled$ResultSampleFractionText %in% fractionkeep | is.na(data_arsenic_dissovled$ResultSampleFractionText)),]
unique(data_arsenic_dissovled$ResultSampleFractionText)



###create dataset to check for non numeric objects in dataset
temp<-data_arsenic_dissovled %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change
data_arsenic_dissovled<-data_arsenic_dissovled %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_arsenic_dissovled$ResultMeasure.MeasureUnitCode)#checked units
unique(data_arsenic_dissovled$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#all in lagos units - no conversion needed

data_arsenic_dissovled$CharacteristicName<-"Arsenic, dissolved"


#completed

```



```{r}
#atrazine dissolved - sample fraction - doesn't have a total

Atrazine_params<-c("Atrazine") #only values for atrazine
data_atrazine_dissolved<-data[data$CharacteristicName%in%Atrazine_params,] #want to match all records to the vector we created above which have calcium
unique(data_atrazine_dissolved$ResultSampleFractionText)
temp<-data_atrazine_dissolved %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep

###create dataset to check for non numeric objects in dataset
temp<-data_atrazine_dissolved %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change #1 NA's - can change
data_atrazine_dissolved<-data_atrazine_dissolved %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_atrazine_dissolved$ResultMeasure.MeasureUnitCode)#checked units
unique(data_atrazine_dissolved$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#convert detection limit from ng/l to ug/l 
data_atrazine_dissolved<-detectconvert(dat = data_atrazine_dissolved, variable = "Atrazine", unit = "ng/l", out_unit = "ug/l", conv_factor = 0.001)

data_atrazine_dissolved$CharacteristicName<-"Atrazine, dissolved"

#completed
```

```{r}
#ecoli
unique(data$CharacteristicName)

Ecoli_params<-c("Escherichia coli") #only values for Escherichia coli
data_ecoli<-data[data$CharacteristicName%in%Ecoli_params,] #want to match all records to the vector we created above which have calcium
unique(data_ecoli$ResultSampleFractionText)
temp<-data_ecoli %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep



###create dataset to check for non numeric objects in dataset
temp<-data_ecoli %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change #1 NA - can change
data_ecoli<-data_ecoli %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_ecoli$ResultMeasure.MeasureUnitCode) #checked units
unique(data_ecoli$DetectionQuantitationLimitMeasure.MeasureUnitCode)


data_ecoli<-resultconvert(dat = data_ecoli, variable = "Escherichia coli", unit = "#/100ml", out_unit = "cfu/100ml", conv_factor = 1)
data_ecoli<-detectconvert(dat = data_ecoli, variable = "Escherichia coli", unit = "#/100ml", out_unit = "cfu/100ml", conv_factor = 1)


unique(data_ecoli$ResultMeasure.MeasureUnitCode) #checked units
unique(data_ecoli$DetectionQuantitationLimitMeasure.MeasureUnitCode)


data_ecoli$CharacteristicName<-"E. coli-CFU"


#completed
```


```{r}
#silica dissolved

Silica_params<-c("Silica", "Silicon") #only values for silica
data_silica<-data[data$CharacteristicName%in%Silica_params,] #want to match all records to the vector we created above which have calcium
data_silica$CharacteristicName<-"Silica"  #set all silica params as silica 
unique(data_silica$ResultSampleFractionText)
fractionkeep<-c("Dissolved")
data_silica<-data_silica[which(data_silica$ResultSampleFractionText %in% fractionkeep | is.na(data_silica$ResultSampleFractionText)),] #keeping if it's ones we chose or NA
unique(data_silica$ResultSampleFractionText)
temp<-data_silica %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep



###create dataset to check for non numeric objects in dataset
temp<-data_silica %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change
data_silica<-data_silica %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_silica$ResultMeasure.MeasureUnitCode) #checked units
unique(data_silica$DetectionQuantitationLimitMeasure.MeasureUnitCode)


data_silica$CharacteristicName<-"Silica, dissolved"


#lagos units for silica is mg/l - no conversion needed 
#completed

```

```{r}
#chloride

Chloride_params<-c("Chloride") #only values for chloride
data_chloride<-data[data$CharacteristicName%in%Chloride_params,] #want to match all records to the vector we created above which have calcium
unique(data_chloride$ResultSampleFractionText)
fractionkeep<-c("Dissolved")
data_chloride<-data_chloride[which(data_chloride$ResultSampleFractionText %in% fractionkeep | is.na(data_chloride$ResultSampleFractionText)),] #keeping if it's ones we chose or NA
unique(data_chloride$ResultSampleFractionText)
temp<-data_chloride %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep



###create dataset to check for non numeric objects in dataset
temp<-data_chloride %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change
data_chloride<-data_chloride %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_chloride$ResultMeasure.MeasureUnitCode) #checked units
unique(data_chloride$DetectionQuantitationLimitMeasure.MeasureUnitCode)

data_chloride$CharacteristicName<-"Chloride, dissolved"

#already in lagos units - mg/l - no conversions needed
```


```{r}
#oxygen

Oxygen_params<-c("Oxygen", "Dissolved oxygen (DO)") #only values for oxygen
data_oxygen<-data[data$CharacteristicName%in%Oxygen_params,] #want to match all records to the vector we created above which have oxygen
unique(data_oxygen$ResultSampleFractionText)
temp<-data_oxygen %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep
#both types are dissolved oxygen - convert all characteristic names to oxygen



###create dataset to check for non numeric objects in dataset
temp<-data_oxygen %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change #1 NA observation - can change
data_oxygen<-data_oxygen %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_oxygen$ResultMeasure.MeasureUnitCode) #checked units
unique(data_oxygen$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#resultmeasurevalue has mg/l, and % saturation - need all in mg/l - detection limits all in mg/l - no need to change 

temp<-filter(data_oxygen, ResultMeasure.MeasureUnitCode == "% saturatn")
#1ppm = 1mg/l, and 1 DO% saturation = 0.08 mg/l

#Cannot convert % sat into mg/l unless you know temp, alt or pressure
data_oxygen<-resultconvert(dat = data_oxygen, variable = "Oxygen", unit = "% saturatn", out_unit = "mg/l", conv_factor = 0.08)
data_oxygen<-resultconvert(dat = data_oxygen, variable = "Oxygen", unit = "ppm", out_unit = "mg/l", conv_factor = 1)


data_oxygen$CharacteristicName<-"Oxygen, dissolved"


#completed

```


```{r}
#chlorophyll

unique(data$CharacteristicName)


Chla_params<-c("Chlorophyll a", "Chlorophyll a, corrected for pheophytin", "Chlorophyll a, uncorrected for pheophytin") #only values for Chl
data_chla<-data[data$CharacteristicName%in%Chla_params,] #want to match all records to the vector we created above which have chl
unique(data_chla$ResultSampleFractionText)
temp<-data_chla %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep



###create dataset to check for non numeric objects in dataset
temp<-data_chla %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change #2 NA's - can change
data_chla<-data_chla%>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_chla$ResultMeasure.MeasureUnitCode) #checked units
unique(data_chla$DetectionQuantitationLimitMeasure.MeasureUnitCode)
#results and detection limit both in mg/m3 and mg/l for resultmeasure and mg/m3 for detection limit - need to convert ug/l
#1mg/m3 = 1ug/l

#working with Chlorophyll a

temp<-data_chla %>% filter(CharacteristicName == "Chlorophyll a")
unique(temp$ResultMeasure.MeasureUnitCode)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)


data_chla<-resultconvert(dat = data_chla, variable = "Chlorophyll a", unit = "mg/l", out_unit = "ug/l", conv_factor = 1000)
data_chla<-resultconvert(dat = data_chla, variable = "Chlorophyll a", unit = "mg/m3", out_unit = "ug/l", conv_factor = 1)
data_chla<-detectconvert(dat = data_chla, variable = "Chlorophyll a", unit = "mg/m3", out_unit = "ug/l", conv_factor = 1)


#working with Chlorophyll a, corrected for pheophytin

temp<-data_chla %>% filter(CharacteristicName == "Chlorophyll a, corrected for pheophytin")
unique(temp$ResultMeasure.MeasureUnitCode)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)

data_chla<-resultconvert(dat = data_chla, variable = "Chlorophyll a, corrected for pheophytin", unit = "mg/m3", out_unit = "ug/l", conv_factor = 1)
data_chla<-detectconvert(dat = data_chla, variable = "Chlorophyll a, corrected for pheophytin", unit = "mg/m3", out_unit = "ug/l", conv_factor = 1)


#working with Chlorophyll a, uncorrected for pheophytin
temp<-data_chla %>% filter(CharacteristicName == "Chlorophyll a, uncorrected for pheophytin")
unique(temp$ResultMeasure.MeasureUnitCode)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#already in ug/l - no conversions needed

data_chla$CharacteristicName<-"Chlorophyll a"



#completed
```


```{r}
# pH

pH_params<-c("pH") #only values for pH
data_pH<-data[data$CharacteristicName%in%pH_params,] #want to match all records to the vector we created above which have pH
unique(data_pH$ResultSampleFractionText)
temp<-data_pH %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep



###create dataset to check for non numeric objects in dataset
temp<-data_pH %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change
data_pH<-data_pH %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_pH$ResultMeasure.MeasureUnitCode) #checked units
unique(data_pH$DetectionQuantitationLimitMeasure.MeasureUnitCode)

temp<-filter(data_pH, ResultMeasure.MeasureUnitCode == "None")

#convert text - from std units to pH and none to pH - (for resutl values) data is correct, but mislabelled - same for detection limits

data_pH$DetectionQuantitationLimitMeasure.MeasureUnitCode<-"pH"
unique(data_pH$DetectionQuantitationLimitMeasure.MeasureUnitCode)

data_pH$ResultMeasure.MeasureUnitCode<-"pH"
unique(data_pH$ResultMeasure.MeasureUnitCode)

data_pH$CharacteristicName<-"pH, equilibrated"

#completed
```

```{r}
#temperature

Temp_params<-c("Temperature, water") #only values for water temp
data_temp<-data[data$CharacteristicName%in%Temp_params,] #want to match all records to the vector we created above which have calcium
unique(data_temp$ResultSampleFractionText)
temp<-data_temp %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep



###create dataset to check for non numeric objects in dataset
temp<-data_temp %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change
data_temp<-data_temp %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_temp$ResultMeasure.MeasureUnitCode) #checked units
unique(data_temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#convert degF to deg C for resultmeasurevalue

data_temp<-resultconvert_celsius(dat = data_temp, variable = "Temperature, water", unit = "deg F", out_unit = "deg C")

data_temp$CharacteristicName<-"Temperature"


#completed
```


```{r}
#sulfate
Sulfate_params<-c("Sulfate", "Sulfur Sulfate", "Sulfate as SO4", "Sulfate as S") #only values for sulfate
data_sulfate<-data[data$CharacteristicName%in%Sulfate_params,] #want to match all records to the vector we created above which have calcium
unique(data_sulfate$ResultSampleFractionText)
fractionkeep<-c("Dissolved")
data_sulfate<-data_sulfate[which(data_sulfate$ResultSampleFractionText %in% fractionkeep | is.na(data_sulfate$ResultSampleFractionText)),] #keeping if it's ones we chose or NA
unique(data_sulfate$ResultSampleFractionText)
temp<-data_sulfate %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep



###create dataset to check for non numeric objects in dataset
temp<-data_sulfate %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change
data_sulfate<-data_sulfate %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_sulfate$ResultMeasure.MeasureUnitCode) #checked units
unique(data_sulfate$DetectionQuantitationLimitMeasure.MeasureUnitCode)

data_sulfate$CharacteristicName<-"Sulfate, dissolved"


#already in lagos units - mg/l - no need for conversion
```

```{r}
#turbidity

Turbidity_params<-c("Turbidity") #only values for turbidity
data_turb<-data[data$CharacteristicName%in%Turbidity_params,] #want to match all records to the vector we created above which have calcium
unique(data_turb$ResultSampleFractionText)
temp<-data_turb %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep



###create dataset to check for non numeric objects in dataset
temp<-data_turb %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change
data_turb<-data_turb %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_turb$ResultMeasure.MeasureUnitCode) #checked units
unique(data_turb$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#detection limit is in NTU - lagos units - don't need to change
#resultmeasurevalue has FTU and FNU - need to convert to NTU

#FTU= NTU, and FNU= NTU ( suggested at similar/comparable - no direct conversion)
#converting both readings to NTU - drop NTRU and JTU
#1mg/l = 3NTU (NTU is smaller)

temp<-filter(data_turb, ResultMeasure.MeasureUnitCode == "NTRU") #only 2 value - drop it
temp<-filter(data_turb, ResultMeasure.MeasureUnitCode == "JTU") #only 49 value - drop it
temp<-filter(data_turb, ResultMeasure.MeasureUnitCode == "mg/l") #470 values - keeping and converting 
temp<-filter(data_turb, ResultMeasure.MeasureUnitCode == "%") #107 values - drop it 

data_turb<-filter(data_turb, ResultMeasure.MeasureUnitCode != "NTRU")
data_turb<-filter(data_turb, ResultMeasure.MeasureUnitCode != "JTU")
data_turb<-filter(data_turb, ResultMeasure.MeasureUnitCode != "%")


data_turb<-resultconvert(dat = data_turb, variable = "Turbidity", unit = "mg/l", out_unit = "NTU", conv_factor = 3)


data_turb$ResultMeasure.MeasureUnitCode<-"NTU"
unique(data_turb$ResultMeasure.MeasureUnitCode)


data_turb$CharacteristicName<-"Turbidity"

#completed

```

```{r}
#conductivity

Cond_params<-c("Specific conductance","Conductivity") #only values for conductivity
data_cond<-data[data$CharacteristicName%in%Cond_params,] #want to match all records to the vector we created above which have calcium
unique(data_cond$ResultSampleFractionText)
temp<-data_cond %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep



###create dataset to check for non numeric objects in dataset
temp<-data_cond %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change
data_cond<-data_cond %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_cond$ResultMeasure.MeasureUnitCode) #checked units
unique(data_cond$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#detectionlimit limit - change us/cm@25 degrees and umho/cm to us/cm - all 1:1 conversions - change text only
#resultmeasure value: change us/cm@25 degrees and umho/cm to us/cm - all 1:1 conversions - change text only. Also convert mho/cm and ms/cm to us/cm (*1000)


#working with conductivity

temp<-data_cond %>% filter(CharacteristicName == "Conductivity")
unique(temp$ResultMeasure.MeasureUnitCode)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)

data_cond<-resultconvert(dat = data_cond, variable = "Conductivity", unit = "umho/cm", out_unit = "uS/cm", conv_factor = 1)
data_cond<-detectconvert(dat = data_cond, variable = "Conductivity", unit = "umho/cm", out_unit = "uS/cm", conv_factor = 1)


#working with specific conductance

temp<-data_cond %>% filter(CharacteristicName == "Specific conductance")
unique(temp$ResultMeasure.MeasureUnitCode)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)




data_cond<-resultconvert(dat = data_cond, variable = "Specific conductance", unit = "uS/cm @25C", out_unit = "uS/cm", conv_factor = 1)
data_cond<-resultconvert(dat = data_cond, variable = "Specific conductance", unit = "umho/cm", out_unit = "uS/cm", conv_factor = 1)
data_cond<-resultconvert(dat = data_cond, variable = "Specific conductance", unit = "mho/cm", out_unit = "uS/cm", conv_factor = 1000)
data_cond<-resultconvert(dat = data_cond, variable = "Specific conductance", unit = "mS/cm", out_unit = "uS/cm", conv_factor = 1000)
data_cond<-detectconvert(dat = data_cond, variable = "Specific conductance", unit = "uS/cm @25C", out_unit = "uS/cm", conv_factor = 1)

data_cond$CharacteristicName<-"Conductivity"


#conversion from umho/cm to us/cm - conversion = 1:1 
#completed
```


```{r}
# total carbon (TC)

Carbon_params<-c("Carbon","Organic carbon") #only values for carbon
data_tc<-data[data$CharacteristicName%in%Carbon_params,] #want to match all records to the vector we created above which have calcium
unique(data_tc$ResultSampleFractionText)
fractionkeep<-c("Total") #only want dissolved organic carbon - not total or suspended
data_tc<-data_tc[which(data_tc$ResultSampleFractionText %in% fractionkeep | is.na(data_tc$ResultSampleFractionText)),] #keeping if it's ones we chose or NA
unique(data_tc$ResultSampleFractionText)


###create dataset to check for non numeric objects in dataset
temp<-data_tc %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change
data_tc<-data_tc %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_tc$ResultMeasure.MeasureUnitCode) #checked units
unique(data_tc$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#units are mg/l - this is lagos units - no need for conversion

data_tc$CharacteristicName<-"Carbon, total organic"


#completed
```


```{r}
# total dissolved carbon (TDC)

Carbon_params<-c("Carbon","Organic carbon") #only values for carbon
data_tdc<-data[data$CharacteristicName%in%Carbon_params,] #want to match all records to the vector we created above which have calcium
unique(data_tdc$ResultSampleFractionText)
fractionkeep<-c("Dissolved") #only want dissolved organic carbon - not total or suspended
data_tdc<-data_tdc[which(data_tdc$ResultSampleFractionText %in% fractionkeep | is.na(data_tdc$ResultSampleFractionText)),] #keeping if it's ones we chose or NA
unique(data_tdc$ResultSampleFractionText)


###create dataset to check for non numeric objects in dataset
temp<-data_tdc %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change
data_tdc<-data_tdc %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_tdc$ResultMeasure.MeasureUnitCode) #checked units
unique(data_tdc$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#units are mg/l - this is lagos units - no need for conversion

data_tdc$CharacteristicName<-"Carbon, dissolved organic"


#completed
```



```{r}
#alkalinity


Alk_params<-c("Alkalinity, total", "Alkalinity, Carbonate as CaCO3", "Alkalinity", "Alkalinity, carbonate" ) #only values for alkalinity
data_alk<-data[data$CharacteristicName%in%Alk_params,] #want to match all records to the vector we created above which have calcium
unique(data_alk$ResultSampleFractionText) #keeping both total and dissolved
temp<-data_alk %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep



###create dataset to check for non numeric objects in dataset
temp<-data_alk %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change
data_alk<-data_alk %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_alk$ResultMeasure.MeasureUnitCode) #checked units
unique(data_alk$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#need to convert mg/l CaCO3 to ueq/l - multiply caco3*19.98, will be converting mg/l to ueql the same way - *19.98

#working with Alkalinity, total

temp<-data_alk %>% filter(CharacteristicName == "Alkalinity, total")
unique(temp$ResultMeasure.MeasureUnitCode)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)

data_alk<-resultconvert(dat = data_alk, variable = "Alkalinity, total", unit = "mg/l", out_unit = "ueq/l", conv_factor = 19.98)
data_alk<-resultconvert(dat = data_alk, variable = "Alkalinity, total", unit = "mg/l CaCO3", out_unit = "ueq/l", conv_factor = 19.98)
data_alk<-detectconvert(dat = data_alk, variable = "Alkalinity, total", unit = "mg/l", out_unit = "ueq/l", conv_factor = 19.98)

#working with Alkalinity, Carbonate as CaCO3
temp<-data_alk %>% filter(CharacteristicName == "Alkalinity, Carbonate as CaCO3")
unique(temp$ResultMeasure.MeasureUnitCode)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)

data_alk<-resultconvert(dat = data_alk, variable = "Alkalinity, Carbonate as CaCO3", unit = "mg/l", out_unit = "ueq/l", conv_factor = 19.98)


#working with Alkalinity
temp<-data_alk %>% filter(CharacteristicName == "Alkalinity")
unique(temp$ResultMeasure.MeasureUnitCode)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)


data_alk<-resultconvert(dat = data_alk, variable = "Alkalinity", unit = "mg/l CaCO3", out_unit = "ueq/l", conv_factor = 19.98)
data_alk<-detectconvert(dat = data_alk, variable = "Alkalinity", unit = "mg/l CaCO3", out_unit = "ueq/l", conv_factor = 19.98)


#working with Alkalinity, carbonate
temp<-data_alk %>% filter(CharacteristicName == "Alkalinity, carbonate")
unique(temp$ResultMeasure.MeasureUnitCode)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)


data_alk<-resultconvert(dat = data_alk, variable = "Alkalinity, carbonate", unit = "mg/l CaCO3", out_unit = "ueq/l", conv_factor = 19.98)


data_alk$CharacteristicName<-"Alkalinity"


#completed

```


```{r}
#TSS

Tss_params<-c("Total suspended solids","Total dissolved solids") #only values for tss
data_tss<-data[data$CharacteristicName%in%Tss_params,] #want to match all records to the vector we created above which have salinity
unique(data_tss$ResultSampleFractionText)
temp<-data_tss %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep
#we only want suspended and total
fractionkeep<-c("Suspended", "Total") 
data_tss<-data_tss[which(data_tss$ResultSampleFractionText %in% fractionkeep | is.na(data_tss$ResultSampleFractionText)),] #keeping if it's ones we chose or NA
unique(data_tss$ResultSampleFractionText)




###create dataset to check for non numeric objects in dataset
temp<-data_tss %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change #3 NA's - can change
data_tss<-data_tss %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_tss$ResultMeasure.MeasureUnitCode) #checked units
unique(data_tss$DetectionQuantitationLimitMeasure.MeasureUnitCode)

data_tss$CharacteristicName<-"Solids, total suspended"

#units in mg/l - lagos units - no conversions needed
#completed


```

```{r}
#Salinity

Salinity_params<-c("Salinity") #only values for salinity
data_salinity<-data[data$CharacteristicName%in%Salinity_params,] #want to match all records to the vector we created above which have salinity
unique(data_salinity$ResultSampleFractionText)


###create dataset to check for non numeric objects in dataset
temp<-data_salinity %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change #3 NA's - can change
data_salinity<-data_salinity %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_salinity$ResultMeasure.MeasureUnitCode) #checked units
unique(data_salinity$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#has mg/ml = 1 ppt - convert text to ppt
#has ppth (parts per hundred trillion - change to ppt - conversion)
#ppm>ppb>ppt>ppth


data_salinity<-resultconvert(dat = data_salinity, variable = "Salinity", unit = "mg/mL @25C", out_unit = "ppt", conv_factor = 1)
data_salinity<-resultconvert(dat = data_salinity, variable = "Salinity", unit = "ppth", out_unit = "ppt", conv_factor = 100)

data_salinity$CharacteristicName<-"Salinity"


#completed
```




```{r}
#color true

truecolor_params<-c("True color") #only values for true color
data_truecolor<-data[data$CharacteristicName%in%truecolor_params,] #want to match all records to the vector we created above which have true color
unique(data_truecolor$ResultSampleFractionText)



###create dataset to check for non numeric objects in dataset
temp<-data_truecolor %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change #3 NA's - can change
data_truecolor<-data_truecolor %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_truecolor$ResultMeasure.MeasureUnitCode) #checked units
unique(data_truecolor$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#in lagos units - PCU - no coversion needed
data_truecolor$CharacteristicName<-"Color, true"


#completed
```


```{r}
#color apparent 

apparentcolor_params<-c("Color") #only values for color
data_apparentcolor<-data[data$CharacteristicName%in%apparentcolor_params,] #want to match all records to the vector we created above which have color
unique(data_apparentcolor$ResultSampleFractionText)



###create dataset to check for non numeric objects in dataset
temp<-data_apparentcolor %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change #3 NA's - can change
data_apparentcolor<-data_apparentcolor %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_apparentcolor$ResultMeasure.MeasureUnitCode) #checked units
unique(data_apparentcolor$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#in lagos units - PCU - no coversion needed
data_apparentcolor$CharacteristicName<-"Color, apparent"


#completed
```


```{r}

###DIP (dissolved inorganic phosphorus)

unique(data$CharacteristicName)

DIP_params<-c("Orthophosphate", "Orthophosphate as P","Orthophosphate as PO4", "Phosphate-phosphorus", "Phosphate-phosphorus as P") #only values for DIP
data_DIP<-data[data$CharacteristicName%in%DIP_params,] #want to match all records to the vector we created above which have DIP
unique(data_DIP$ResultSampleFractionText)
temp<-data_DIP %>% filter(is.na(ResultSampleFractionText))
#unique(temp$CharacteristicName) #this characteristic name is typically associated with dissolved 
fractionkeep<-c("Dissolved")
data_DIP<-data_DIP[which(data_DIP$ResultSampleFractionText %in% fractionkeep | is.na(data_DIP$ResultSampleFractionText)),]
unique(data_DIP$ResultSampleFractionText)


###create dataset to check for non numeric objects in dataset
temp<-data_DIP %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values - if NA's not losing any other data - can change
#162 NA's - can change
data_DIP<-data_DIP %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA


unique(data_DIP$ResultMeasure.MeasureUnitCode) #check units
unique(data_DIP$DetectionQuantitationLimitMeasure.MeasureUnitCode)


#working with orthophosphate

temp<-data_DIP %>% filter(CharacteristicName == "Orthophosphate")
unique(temp$ResultMeasure.MeasureUnitCode)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)



#convert orthophosphate mg/l, mg/l as P, mg/l as PO4 to ug/L P for resultmeasurevalue and detection limits

data_DIP<-resultconvert(dat = data_DIP, variable = "Orthophosphate", unit = "mg/l", out_unit = "ug/L", conv_factor = 326.1)
data_DIP<-detectconvert(dat = data_DIP, variable = "Orthophosphate", unit = "mg/l", out_unit = "ug/L", conv_factor = 326.1)

data_DIP<-resultconvert(dat = data_DIP, variable = "Orthophosphate", unit = "mg/l as P", out_unit = "ug/L", conv_factor = 1000)
data_DIP<-detectconvert(dat = data_DIP, variable = "Orthophosphate", unit = "mg/l as P", out_unit = "ug/L", conv_factor = 1000)

data_DIP<-resultconvert(dat = data_DIP, variable = "Orthophosphate", unit = "mg/l asPO4", out_unit = "ug/L", conv_factor = 326.1)
data_DIP<-detectconvert(dat = data_DIP, variable = "Orthophosphate", unit = "mg/l asPO4", out_unit = "ug/L", conv_factor = 326.1)


#working with Orthophosphate as P

temp<-data_DIP %>% filter(CharacteristicName == "Orthophosphate as P")
unique(temp$ResultMeasure.MeasureUnitCode)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)

data_DIP<-resultconvert(dat = data_DIP, variable = "Orthophosphate as P", unit = "mg/l", out_unit = "ug/L", conv_factor = 326.1)


#working with Orthophosphate as PO4

temp<-data_DIP %>% filter(CharacteristicName == "Orthophosphate as PO4")
unique(temp$ResultMeasure.MeasureUnitCode)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)

data_DIP<-resultconvert(dat = data_DIP, variable = "Orthophosphate as PO4", unit = "mg/l asPO4", out_unit = "ug/L", conv_factor = 326.1)


#working with "Phosphate-phosphorus"

temp<-data_DIP %>% filter(CharacteristicName == "Phosphate-phosphorus")
unique(temp$ResultMeasure.MeasureUnitCode)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)

data_DIP<-resultconvert(dat = data_DIP, variable = "Phosphate-phosphorus", unit = "mg/l", out_unit = "ug/L", conv_factor = 326.1)
data_DIP<-detectconvert(dat = data_DIP, variable = "Phosphate-phosphorus", unit = "mg/l", out_unit = "ug/L", conv_factor = 326.1)


#working with Phosphate-phosphorus as P


temp<-data_DIP %>% filter(CharacteristicName == "Phosphate-phosphorus as P")
unique(temp$ResultMeasure.MeasureUnitCode)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)

data_DIP<-resultconvert(dat = data_DIP, variable = "Phosphate-phosphorus", unit = "mg/l", out_unit = "ug/L", conv_factor = 326.1)

data_DIP$CharacteristicName<-"Phosphorus, soluable reactive orthophosphate"

#COMPLETED

```


```{r}
#phosphorus total

unique(data$CharacteristicName)

TP_params<-c("Phosphorus") #only values for total phosphorus
data_TP<-data[data$CharacteristicName%in%TP_params,] #want to match all records to the vector we created above which have TP
unique(data_TP$ResultSampleFractionText)
temp<-data_TP %>% filter(is.na(ResultSampleFractionText))
fractionkeep<-c("Total")
data_TP<-data_TP[which(data_TP$ResultSampleFractionText %in% fractionkeep | is.na(data_TP$ResultSampleFractionText)),] #keeping if it's ones we chose or NA
unique(data_TP$ResultSampleFractionText)


###create dataset to check for non numeric objects in dataset
temp<-data_TP %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values - if NA's not losing any other data - can change - 4NA's
data_TP<-data_TP %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_TP$ResultMeasure.MeasureUnitCode) #check units
unique(data_TP$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#working with phosphorus

temp<-data_TP %>% filter(CharacteristicName == "Phosphorus")
unique(temp$ResultMeasure.MeasureUnitCode)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#convert mg/l, mg/l as P and mg/l po4 to ug/l for resultsvalue and mg/l, mg/l as P for detectionlimits

data_TP<-resultconvert(dat = data_TP, variable = "Phosphorus", unit = "mg/l", out_unit = "ug/L", conv_factor = 1000)
data_TP<-detectconvert(dat = data_TP, variable = "Phosphorus", unit = "mg/l", out_unit = "ug/L", conv_factor = 1000)

data_TP<-resultconvert(dat = data_TP, variable = "Phosphorus", unit = "mg/l as P", out_unit = "ug/L", conv_factor = 1000)
data_TP<-detectconvert(dat = data_TP, variable = "Phosphorus", unit = "mg/l as P", out_unit = "ug/L", conv_factor = 1000)

data_TP<-resultconvert(dat = data_TP, variable = "Phosphorus", unit = "mg/l PO4", out_unit = "ug/L", conv_factor = 1000)


data_TP$CharacteristicName<-"Phosphorus, total"

#complete

```

```{r}
#phosphorus total dissolved 

unique(data$CharacteristicName)

TP_params<-c("Phosphorus") #only values for total phosphorus
data_TDP<-data[data$CharacteristicName%in%TP_params,] #want to match all records to the vector we created above which have TP
unique(data_TDP$ResultSampleFractionText)
temp<-data_TDP %>% filter(is.na(ResultSampleFractionText))
fractionkeep<-c("Dissolved")
data_TDP<-data_TDP[which(data_TDP$ResultSampleFractionText %in% fractionkeep | is.na(data_TDP$ResultSampleFractionText)),] #keeping if it's ones we chose or NA
unique(data_TDP$ResultSampleFractionText)


###create dataset to check for non numeric objects in dataset
temp<-data_TDP %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values - if NA's not losing any other data - can change - 4NA's
data_TDP<-data_TDP %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_TDP$ResultMeasure.MeasureUnitCode) #check units
unique(data_TDP$DetectionQuantitationLimitMeasure.MeasureUnitCode)



#convert mg/l and mg/l as P to ug/l for resultsvalue and detectionlimits


data_TDP<-resultconvert(dat = data_TDP, variable = "Phosphorus", unit = "mg/l", out_unit = "ug/L", conv_factor = 1000)
data_TDP<-detectconvert(dat = data_TDP, variable = "Phosphorus", unit = "mg/l", out_unit = "ug/L", conv_factor = 1000)


data_TDP<-resultconvert(dat = data_TDP, variable = "Phosphorus", unit = "mg/l as P", out_unit = "ug/L", conv_factor = 1000)
data_TDP<-detectconvert(dat = data_TDP, variable = "Phosphorus", unit = "mg/l as P", out_unit = "ug/L", conv_factor = 1000)


data_TDP$CharacteristicName<-"Phosphorus, total dissolved"

#complete

```



```{r}
#TKN #kjeldahl 

unique(data$CharacteristicName)

TKN_params<-c("Kjeldahl nitrogen", "Total Kjeldahl nitrogen") #only values for TKN
data_TKN<-data[data$CharacteristicName%in%TKN_params,] #want to match all records to the vector we created above which have TKN
unique(data_TKN$ResultSampleFractionText)
temp<-data_TKN %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep
fractionkeep<-c("Total")
data_TKN<-data_TKN[which(data_TKN$ResultSampleFractionText %in% fractionkeep | is.na(data_TKN$ResultSampleFractionText)),] #keeping if it's ones we chose or NA
unique(data_TKN$ResultSampleFractionText)


###create dataset to check for non numeric objects in dataset
temp<-data_TKN %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change - 15 NA's - can change
data_TKN<-data_TKN %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_TKN$ResultMeasure.MeasureUnitCode)
unique(data_TKN$DetectionQuantitationLimitMeasure.MeasureUnitCode)#checked units


#We have mg/l and mg/l as N - Need to make conversion for both into ug/L as N

data_TKN<-resultconvert(dat = data_TKN, variable = "Kjeldahl nitrogen", unit = "mg/l", out_unit = "ug/l", conv_factor = 1000)
data_TKN<-detectconvert(dat = data_TKN, variable = "Kjeldahl nitrogen", unit = "mg/l", out_unit = "ug/l", conv_factor = 1000)

data_TKN<-resultconvert(dat = data_TKN, variable = "Kjeldahl nitrogen", unit = "mg/l as N", out_unit = "ug/l", conv_factor = 1000)
data_TKN<-detectconvert(dat = data_TKN, variable = "Kjeldahl nitrogen", unit = "mg/l as N", out_unit = "ug/l", conv_factor = 1000)


data_TKN$CharacteristicName<-"Nitrogen, total Kjeldahl"

#COMPLETED
```


```{r}
#TDKN #kjeldahl 

unique(data$CharacteristicName)

TKN_params<-c("Kjeldahl nitrogen", "Total Kjeldahl nitrogen") #only values for TKN
data_TDKN<-data[data$CharacteristicName%in%TKN_params,] #want to match all records to the vector we created above which have TKN
unique(data_TDKN$ResultSampleFractionText)
temp<-data_TDKN %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep
fractionkeep<-c("Dissolved")
data_TDKN<-data_TDKN[which(data_TDKN$ResultSampleFractionText %in% fractionkeep | is.na(data_TDKN$ResultSampleFractionText)),] #keeping if it's ones we chose or NA
unique(data_TDKN$ResultSampleFractionText)


###create dataset to check for non numeric objects in dataset
temp<-data_TDKN %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change - 15 NA's - can change
data_TDKN<-data_TDKN %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_TDKN$ResultMeasure.MeasureUnitCode)
unique(data_TDKN$DetectionQuantitationLimitMeasure.MeasureUnitCode)#checked units


#We have mg/l and mg/l as N - Need to make conversion for both into ug/L as N

data_TDKN<-resultconvert(dat = data_TDKN, variable = "Kjeldahl nitrogen", unit = "mg/l", out_unit = "ug/l", conv_factor = 1000)
data_TDKN<-detectconvert(dat = data_TDKN, variable = "Kjeldahl nitrogen", unit = "mg/l", out_unit = "ug/l", conv_factor = 1000)

data_TDKN<-resultconvert(dat = data_TDKN, variable = "Kjeldahl nitrogen", unit = "mg/l as N", out_unit = "ug/l", conv_factor = 1000)
data_TDKN<-detectconvert(dat = data_TDKN, variable = "Kjeldahl nitrogen", unit = "mg/l as N", out_unit = "ug/l", conv_factor = 1000)


data_TDKN$CharacteristicName<-"Nitrogen, dissolved Kjeldahl"

#COMPLETED
```


```{r}
#Total Nitrogen

unique(data$CharacteristicName)

TN_params<-c("Nitrogen", "Nitrogen, mixed forms (NH3), (NH4), organic, (NO2) and (NO3)") #only values for TN
data_TN<-data[data$CharacteristicName%in%TN_params,] #want to match all records to the vector we created above which have TP
unique(data_TN$ResultSampleFractionText)
temp<-data_TN %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep
fractionkeep<-c("Total")
data_TN<-data_TN[which(data_TN$ResultSampleFractionText %in% fractionkeep | is.na(data_TN$ResultSampleFractionText)),] #keeping if it's ones we chose or NA
unique(data_TN$ResultSampleFractionText)

###create dataset to check for non numeric objects in dataset
temp<-data_TN %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change #2 NA's - can change
data_TN<-data_TN %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_TN$ResultMeasure.MeasureUnitCode) #checked units
unique(data_TN$DetectionQuantitationLimitMeasure.MeasureUnitCode)

###working with nitrogen

temp<-data_TN %>% filter(CharacteristicName == "Nitrogen")
unique(temp$ResultMeasure.MeasureUnitCode)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#convert resultmeasurevalue from mg/l to ug/l

data_TN<-resultconvert(dat = data_TN, variable = "Nitrogen", unit = "mg/l", out_unit = "ug/l", conv_factor = 1000)
data_TN<-detectconvert(dat = data_TN, variable = "Nitrogen", unit = "mg/l", out_unit = "ug/l", conv_factor = 1000)


###working with Nitrogen, mixed forms (NH3), (NH4), organic, (NO2) and (NO3)

temp<-data_TN %>% filter(CharacteristicName == "Nitrogen, mixed forms (NH3), (NH4), organic, (NO2) and (NO3)")
unique(temp$ResultMeasure.MeasureUnitCode)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)

temp2<-temp %>% filter(CharacteristicName == "Nitrogen, mixed forms (NH3), (NH4), organic, (NO2) and (NO3)") %>% filter(ResultMeasure.MeasureUnitCode == "mg/l")
unique(temp2$ResultAnalyticalMethod.MethodName)
unique(temp2$ResultAnalyticalMethod.MethodIdentifier)


#convert both results and detect from mg/l to ug/l and mg/l NO3 to ug/l N
#after checking methodidentifier above - found AKP01, ALGOR (didn't explain much), methodname - found persulfate - used in digestion of DOC and DON - turns to NO3
#therefore mg/l to ug/l conversion is 0.2259*1000


data_TN<-resultconvert(dat = data_TN, variable = "Nitrogen, mixed forms (NH3), (NH4), organic, (NO2) and (NO3)", unit = "mg/l", out_unit = "ug/l", conv_factor = 0.2259*1000)
data_TN<-detectconvert(dat = data_TN, variable = "Nitrogen, mixed forms (NH3), (NH4), organic, (NO2) and (NO3)", unit = "mg/l", out_unit = "ug/l", conv_factor = 0.2259*1000)


data_TN<-resultconvert(dat = data_TN, variable = "Nitrogen, mixed forms (NH3), (NH4), organic, (NO2) and (NO3)", unit = "mg/l NO3", out_unit = "ug/l", conv_factor = 0.2559*1000)
data_TN<-detectconvert(dat = data_TN, variable = "Nitrogen, mixed forms (NH3), (NH4), organic, (NO2) and (NO3)", unit = "mg/l NO3", out_unit = "ug/l", conv_factor = 0.2559*1000)

data_TN$CharacteristicName<-"Nitrogen, total"


#Completed

```


```{r}
#Total dissolved Nitrogen

unique(data$CharacteristicName)

TDN_params<-c("Nitrogen","Nitrogen, mixed forms (NH3), (NH4), organic, (NO2) and (NO3)") #only values for TN
data_TDN<-data[data$CharacteristicName%in%TDN_params,] #want to match all records to the vector we created above which have TP
unique(data_TDN$ResultSampleFractionText)
temp<-data_TDN %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep
fractionkeep<-c("Dissolved")
data_TDN<-data_TDN[which(data_TDN$ResultSampleFractionText %in% fractionkeep | is.na(data_TDN$ResultSampleFractionText)),] #keeping if it's ones we chose or NA
unique(data_TDN$ResultSampleFractionText)

###create dataset to check for non numeric objects in dataset
temp<-data_TDN %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change #2 NA's - can change
data_TDN<-data_TDN %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_TDN$ResultMeasure.MeasureUnitCode) #checked units
unique(data_TDN$DetectionQuantitationLimitMeasure.MeasureUnitCode)

###working with nitrogen

temp<-data_TDN %>% filter(CharacteristicName == "Nitrogen")
unique(temp$ResultMeasure.MeasureUnitCode)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#convert resultmeasurevalue and detection limits from mg/l to ug/l

data_TDN<-resultconvert(dat = data_TDN, variable = "Nitrogen", unit = "mg/l", out_unit = "ug/l", conv_factor = 1000)
data_TDN<-detectconvert(dat = data_TDN, variable = "Nitrogen", unit = "mg/l", out_unit = "ug/l", conv_factor = 1000)


###working with Nitrogen, mixed forms (NH3), (NH4), organic, (NO2) and (NO3)


temp<-data_TDN %>% filter(CharacteristicName == "Nitrogen, mixed forms (NH3), (NH4), organic, (NO2) and (NO3)")
unique(temp$ResultMeasure.MeasureUnitCode)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)

temp2<-temp %>% filter(CharacteristicName == "Nitrogen, mixed forms (NH3), (NH4), organic, (NO2) and (NO3)") %>% filter(ResultMeasure.MeasureUnitCode == "mg/l")
unique(temp2$ResultAnalyticalMethod.MethodName)
unique(temp2$ResultAnalyticalMethod.MethodIdentifier)

#convert both results and detect from mg/l to ug/l and mg/l NO3 to ug/l N
#0.2259 * 1000 - found methods to hvae persulfate digestion and method CL063 - also persulfate digestion


data_TDN<-resultconvert(dat = data_TDN, variable = "Nitrogen, mixed forms (NH3), (NH4), organic, (NO2) and (NO3)", unit = "mg/l", out_unit = "ug/l", conv_factor = 0.2259*1000)
data_TDN<-detectconvert(dat = data_TDN, variable = "Nitrogen, mixed forms (NH3), (NH4), organic, (NO2) and (NO3)", unit = "mg/l", out_unit = "ug/l", conv_factor = 0.2259*1000)

data_TDN$CharacteristicName<-"Nitrogen, total dissolved"

#Completed

```



```{r}
#Ammonia, ammonium

unique(data$CharacteristicName)

NH4_params<-c("Ammonia",  "Ammonia as NH3", "Ammonia and ammonium", "Ammonia-nitrogen as N", "Ammonia-nitrogen") #only values for NH4
data_ammonia<-data[data$CharacteristicName%in%NH4_params,] #want to match all records to the vector we created above which have TP
unique(data_ammonia$ResultSampleFractionText)
temp<-data_ammonia %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep
fractionkeep<-c("Dissolved")
data_ammonia<-data_ammonia[which(data_ammonia$ResultSampleFractionText %in% fractionkeep | is.na(data_ammonia$ResultSampleFractionText)),] #keeping if it's ones we chose or NA
unique(data_ammonia$ResultSampleFractionText)

###create dataset to check for non numeric objects in dataset
temp<-data_ammonia %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change #2 NA's - can change
data_ammonia<-data_ammonia %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_ammonia$ResultMeasure.MeasureUnitCode) #checked units
unique(data_ammonia$DetectionQuantitationLimitMeasure.MeasureUnitCode)

###working with "Ammonia"

temp<-data_ammonia %>% filter(CharacteristicName == "Ammonia")
unique(temp$ResultMeasure.MeasureUnitCode)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)


data_ammonia<-resultconvert(dat = data_ammonia, variable = "Ammonium", unit = "mg/l", out_unit = "ug/l", conv_factor = 0.7765*1000)
data_ammonia<-detectconvert(dat = data_ammonia, variable = "Ammonium", unit = "mg/l", out_unit = "ug/l", conv_factor = 0.7765*1000)


###working with "Ammonia and ammonium"

temp<-data_ammonia %>% filter(CharacteristicName == "Ammonia and ammonium")
unique(temp$ResultMeasure.MeasureUnitCode)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)

data_ammonia<-resultconvert(dat = data_ammonia, variable = "Ammonia and ammonium", unit = "mg/l as N", out_unit = "ug/l", conv_factor = 1000)
data_ammonia<-detectconvert(dat = data_ammonia, variable = "Ammonia and ammonium", unit = "mg/l as N", out_unit = "ug/l", conv_factor = 1000)

data_ammonia<-resultconvert(dat = data_ammonia, variable = "Ammonia and ammonium", unit = "mg/l NH4", out_unit = "ug/l", conv_factor = 0.7765*1000)
data_ammonia<-detectconvert(dat = data_ammonia, variable = "Ammonia and ammonium", unit = "mg/l NH4", out_unit = "ug/l", conv_factor = 0.7765*1000)

#working with Ammonia as NH3  ## values were dropped when cleaned above
temp<-data_ammonia %>% filter(CharacteristicName == "Ammonia as NH3")
unique(temp$ResultMeasure.MeasureUnitCode)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)




#working with Ammonia-nitrogen as N  #values were dropped when cleaned above
temp<-data_ammonia %>% filter(CharacteristicName == "Ammonia-nitrogen as N")
unique(temp$ResultMeasure.MeasureUnitCode)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)


#working with Ammonia-nitrogen
temp<-data_ammonia %>% filter(CharacteristicName == "Ammonia-nitrogen")
unique(temp$ResultMeasure.MeasureUnitCode)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)

temp2<-temp %>% filter(CharacteristicName == "Ammonia-nitrogen") %>% filter(ResultMeasure.MeasureUnitCode == "mg/l")
unique(temp2$ResultAnalyticalMethod.MethodName)
unique(temp2$ResultAnalyticalMethod.MethodIdentifier)
#method I2525 suggests its Nh3-N - reported as N - can do direct mg/l to ug/l conversion


data_ammonia<-resultconvert(dat = data_ammonia, variable = "Ammonia-nitrogen", unit = "mg/l as N", out_unit = "ug/l", conv_factor = 1000)
data_ammonia<-detectconvert(dat = data_ammonia, variable = "Ammonia-nitrogen", unit = "mg/l as N", out_unit = "ug/l", conv_factor = 1000)


data_ammonia$CharacteristicName<-"Nitrogen, NH4"


#Completed
```




```{r}
#no3 params

unique(data$CharacteristicName)

NO3_params<-c("Inorganic nitrogen (nitrate and nitrite)", "Inorganic nitrogen (nitrate and nitrite) as N", "Nitrate", "Nitrate as N") 
data_NO3<-data[data$CharacteristicName%in%NO3_params,] #want to match all records to the vector we created above 
unique(data_NO3$ResultSampleFractionText)

###create dataset to check for non numeric objects in dataset
temp<-data_NO3 %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change #391 NA's - can change
data_NO3<-data_NO3 %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_NO3$ResultMeasure.MeasureUnitCode)
unique(data_NO3$DetectionQuantitationLimitMeasure.MeasureUnitCode)


#working with "Inorganic nitrogen (nitrate and nitrite)"

temp<-data_NO3 %>% filter(CharacteristicName == "Inorganic nitrogen (nitrate and nitrite)")
unique(temp$ResultMeasure.MeasureUnitCode) 
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)  

  
data_NO3<-resultconvert(dat = data_NO3, variable = "Inorganic nitrogen (nitrate and nitrite)", unit = "mg/l as N", out_unit = "ug/l", conv_factor = 1000)
data_NO3<-detectconvert(dat = data_NO3, variable = "Inorganic nitrogen (nitrate and nitrite)", unit = "mg/l as N", out_unit = "ug/l", conv_factor = 1000)


temp2<-temp %>% filter(CharacteristicName == "Inorganic nitrogen (nitrate and nitrite)") %>% filter(ResultMeasure.MeasureUnitCode == "mg/l")
unique(temp2$ResultAnalyticalMethod.MethodName)
unique(temp2$ResultAnalyticalMethod.MethodIdentifier)
#shows method 353.2 - reported at N - can do direct mg/l to ug/l conversion

data_NO3<-resultconvert(dat = data_NO3, variable = "Inorganic nitrogen (nitrate and nitrite)", unit = "mg/l", out_unit = "ug/l", conv_factor = 1000)
data_NO3<-detectconvert(dat = data_NO3, variable = "Inorganic nitrogen (nitrate and nitrite)", unit = "mg/l", out_unit = "ug/l", conv_factor = 1000)


#working with Inorganic nitrogen (nitrate and nitrite) as N

temp<-data_NO3 %>% filter(CharacteristicName == "Inorganic nitrogen (nitrate and nitrite) as N")
unique(temp$ResultMeasure.MeasureUnitCode) 
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)  

temp2<-temp %>% filter(CharacteristicName == "Inorganic nitrogen (nitrate and nitrite) as N") %>% filter(ResultMeasure.MeasureUnitCode == "mg/l")
unique(temp2$ResultAnalyticalMethod.MethodName)
unique(temp2$ResultAnalyticalMethod.MethodIdentifier)
#4500-NO3 - suggests its a UV light technique for meeasuing NO3 as Nitrogen - can do direct conversion 

data_NO3<-resultconvert(dat = data_NO3, variable = "Inorganic nitrogen (nitrate and nitrite) as N", unit = "mg/l", out_unit = "ug/l", conv_factor = 1000)



#working with "Nitrate"

temp<-data_NO3 %>% filter(CharacteristicName == "Nitrate")
unique(temp$ResultMeasure.MeasureUnitCode) 
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)  

temp2<-temp %>% filter(CharacteristicName == "Nitrate") %>% filter(ResultMeasure.MeasureUnitCode == "mg/l")
unique(temp2$ResultAnalyticalMethod.MethodName)
unique(temp2$ResultAnalyticalMethod.MethodIdentifier)
#method 353.2 - reported as nitrogen - can do direct conversion from mg/l to ug/l

data_NO3<-resultconvert(dat = data_NO3, variable = "Nitrate", unit = "mg/l as N", out_unit = "ug/l", conv_factor = 1000)
data_NO3<-detectconvert(dat = data_NO3, variable = "Nitrate", unit = "mg/l as N", out_unit = "ug/l", conv_factor = 1000)

data_NO3<-resultconvert(dat = data_NO3, variable = "Nitrate", unit = "mg/l", out_unit = "ug/l", conv_factor = 1000)
data_NO3<-detectconvert(dat = data_NO3, variable = "Nitrate", unit = "mg/l", out_unit = "ug/l", conv_factor = 1000)


data_NO3<-resultconvert(dat = data_NO3, variable = "Nitrate", unit = "mg/l asNO3", out_unit = "ug/l", conv_factor = 0.2259*1000)
data_NO3<-detectconvert(dat = data_NO3, variable = "Nitrate", unit = "mg/l asNO3", out_unit = "ug/l", conv_factor = 0.2259*1000)


#working with Nitrate as N

temp<-data_NO3 %>% filter(CharacteristicName == "Nitrate as N")
unique(temp$ResultMeasure.MeasureUnitCode) 
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)
#nitrate as N - direct conversion

data_NO3<-resultconvert(dat = data_NO3, variable = "Nitrate as N", unit = "mg/l", out_unit = "ug/l", conv_factor = 1000)


data_NO3$CharacteristicName<-"Nitrogen, nitrite (NO2) + nitrate (NO3)"


#completed



```




```{r}

#nitrite

NO2_params<-c("Nitrite", "Nitrite as N") #only values 
data_NO2<-data[data$CharacteristicName%in%NO2_params,] #want to match all records to the vector we created above 
unique(data_NO2$ResultSampleFractionText)


###create dataset to check for non numeric objects in dataset
temp<-data_NO2 %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change #391 NA's - can change
data_NO2<-data_NO2 %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_NO2$ResultMeasure.MeasureUnitCode)
unique(data_NO2$DetectionQuantitationLimitMeasure.MeasureUnitCode)


#working with "Nitrite"

temp<-data_NO2 %>% filter(CharacteristicName == "Nitrite")
unique(temp$ResultMeasure.MeasureUnitCode) 
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)  

temp2<-temp %>% filter(CharacteristicName == "Nitrite") %>% filter(ResultMeasure.MeasureUnitCode == "mg/l")
unique(temp2$ResultAnalyticalMethod.MethodName)
unique(temp2$ResultAnalyticalMethod.MethodIdentifier)
#353.2 - repported as N - direct mg/l to ug/l conversion


data_NO2<-resultconvert(dat = data_NO2, variable = "Nitrite", unit = "mg/l as N", out_unit = "ug/l", conv_factor = 1000)
data_NO2<-detectconvert(dat = data_NO2, variable = "Nitrite", unit = "mg/l as N", out_unit = "ug/l", conv_factor = 1000)

data_NO2<-resultconvert(dat = data_NO2, variable = "Nitrite", unit = "mg/l", out_unit = "ug/l", conv_factor = 1000)
data_NO2<-detectconvert(dat = data_NO2, variable = "Nitrite", unit = "mg/l", out_unit = "ug/l", conv_factor = 1000)


data_NO2<-resultconvert(dat = data_NO2, variable = "Nitrite", unit = "mg/l asNO2", out_unit = "ug/l", conv_factor = 0.3044*1000)
data_NO2<-detectconvert(dat = data_NO2, variable = "Nitrite", unit = "mg/l asNO2", out_unit = "ug/l", conv_factor = 0.3044*1000)


#working with "Nitrite as N"

temp<-data_NO2 %>% filter(CharacteristicName == "Nitrite as N")
unique(temp$ResultMeasure.MeasureUnitCode) 
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)  

temp2<-temp %>% filter(CharacteristicName == "Nitrite as N") %>% filter(ResultMeasure.MeasureUnitCode == "mg/l")
unique(temp2$ResultAnalyticalMethod.MethodName)
unique(temp2$ResultAnalyticalMethod.MethodIdentifier)
#4500-no2 - uv method of measure of No2 nitrogen - reported as Nitrogen - can do mg/l to ug/l direct conversion 

data_NO2<-resultconvert(dat = data_NO2, variable = "Nitrite as N", unit = "mg/l", out_unit = "ug/l", conv_factor = 1000)



data_NO2$CharacteristicName<-"Nitrogen, nitrite (NO2)"

#completed



```



```{r}

alldata_ID<- rbind(data_depth, data_secchi, data_calcium, data_aluminum_total, data_aluminum_dissolved, data_mercury_total, data_mercury_dissolved, data_methylmercury_dissolved, data_magnesium, data_selenium_total, data_selenium_dissolved, data_arsenic_total, data_arsenic_dissovled, data_atrazine_dissolved, data_ecoli, data_silica, data_chloride, data_oxygen, data_chla, data_pH, data_temp, data_sulfate, data_turb, data_cond, data_tc, data_tdc, data_alk, data_tss, data_salinity, data_truecolor, data_apparentcolor, data_DIP, data_TP, data_TDP, data_TKN, data_TDKN, data_TN, data_TDN, data_ammonia, data_NO3, data_NO2) 

write.csv(alldata_ID, file = "alldata_ID.csv", row.names = FALSE)

```


