---
title: "Datacleaningcode"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r setup}
library(tidyverse)

non_numerics <- function(data=data_temp) {
  return(data %>% filter(is.na(as.numeric(ResultMeasureValue))) %>% 
      select(ResultMeasureValue,
         DetectionQuantitationLimitMeasure.MeasureValue,
         ResultMeasure.MeasureUnitCode,
         DetectionQuantitationLimitMeasure.MeasureUnitCode,
         ResultDetectionConditionText,
         ActivityBottomDepthHeightMeasure.MeasureValue,
         ActivityBottomDepthHeightMeasure.MeasureUnitCode,Obs_Id) %>% 
        drop_na(ResultMeasureValue))

}

`%notin%` <- Negate(`%in%`)


#here are functions
#for temperature

# resultconvert_celsius<-function(dat, variable, unit, out_unit) {
#   dat$ResultMeasureValue[which(dat$CharacteristicName == variable & dat$ResultMeasure.MeasureUnitCode == unit)] <- (dat$ResultMeasureValue[which(dat$CharacteristicName == variable & dat$ResultMeasure.MeasureUnitCode == unit)] -32)* 5/9
#   
# dat$ResultMeasure.MeasureUnitCode[which(dat$CharacteristicName == variable & dat$ResultMeasure.MeasureUnitCode == unit)] <- out_unit
# 
# return(dat)
#   
# }
# 
# 
# detectconvert_celsius<-function(dat, variable, unit, out_unit) {
#   dat$DetectionQuantitationLimitMeasure.MeasureValue[which(dat$CharacteristicName == variable & dat$DetectionQuantitationLimitMeasure.MeasureUnitCode == unit)] <- (dat$DetectionQuantitationLimitMeasure.MeasureValue[which(dat$CharacteristicName == variable & dat$DetectionQuantitationLimitMeasure.MeasureUnitCode == unit)] * -32)*5/9
#   
# dat$DetectionQuantitationLimitMeasure.MeasureUnitCode[which(dat$CharacteristicName == variable & dat$DetectionQuantitationLimitMeasure.MeasureUnitCode == unit)] <- out_unit
# 
# return(dat)
#   
# }
# 
# #for all other conversions
# 
# resultconvert<-function(dat, variable, unit, out_unit, conv_factor) {
#   dat$ResultMeasureValue[which(dat$CharacteristicName == variable & dat$ResultMeasure.MeasureUnitCode == unit)] <- dat$ResultMeasureValue[which(dat$CharacteristicName == variable & dat$ResultMeasure.MeasureUnitCode == unit)] * conv_factor
#   
# dat$ResultMeasure.MeasureUnitCode[which(dat$CharacteristicName == variable & dat$ResultMeasure.MeasureUnitCode == unit)] <- out_unit
# 
# return(dat)
#   
# }
# 
# 
# detectconvert<-function(dat, variable, unit, out_unit, conv_factor) {
#   dat$DetectionQuantitationLimitMeasure.MeasureValue[which(dat$CharacteristicName == variable & dat$DetectionQuantitationLimitMeasure.MeasureUnitCode == unit)] <- dat$DetectionQuantitationLimitMeasure.MeasureValue[which(dat$CharacteristicName == variable & dat$DetectionQuantitationLimitMeasure.MeasureUnitCode == unit)] * conv_factor
#   
# dat$DetectionQuantitationLimitMeasure.MeasureUnitCode[which(dat$CharacteristicName == variable & dat$DetectionQuantitationLimitMeasure.MeasureUnitCode == unit)] <- out_unit
# 
# return(dat)
#   
# }



```


```{r noah-read}
file.path <- "~/Lottig Dropbox/Noah Lottig/CL_LAGOSUS_exports/LAGOSUS_LIMNO/US_NEW/raw_data/" #Noah
```


```{r kait-read}
file.path <-"" #kait
```


```{r arnab-read}
file.path <-"~/Lagos Limno/" #arnab
```


```{r read-files}
read.csv("list of unique parameters to remove.csv") -> remove_params #update this

#NE STATES PULL

CTdatPull<-read.csv(paste0(file.path,"CT_cleaned.csv")) %>% filter(!CharacteristicName %in% remove_params$Unique.parameters)
CTdatPull$State<-c("CT")
CTdatPull$Id_num<-c(seq(1:nrow(CTdatPull)))
CTdatPull <- CTdatPull %>% 
  unite('Obs_Id', c(State, Id_num), sep = "-", remove = FALSE)
names(CTdatPull)
summary(CTdatPull)

IAdatPull<-read.csv(paste0(file.path,"IA_cleaned.csv")) %>% filter(!CharacteristicName %in% remove_params$Unique.parameters)
IAdatPull$State<-c("IA")
IAdatPull$Id_num<-c(seq(1:nrow(IAdatPull)))
IAdatPull <- IAdatPull %>% 
  unite('Obs_Id', c(State, Id_num), sep = "-", remove = FALSE)
names(IAdatPull)
summary(IAdatPull)

ILdatPull<-read.csv(paste0(file.path,"IL_cleaned.csv")) %>% filter(!CharacteristicName %in% remove_params$Unique.parameters)
ILdatPull$State<-c("IL")
ILdatPull$Id_num<-c(seq(1:nrow(ILdatPull)))
ILdatPull <- ILdatPull %>% 
  unite('Obs_Id', c(State, Id_num), sep = "-", remove = FALSE)
names(ILdatPull)
summary(ILdatPull)

INdatPull<-read.csv(paste0(file.path,"IN_cleaned.csv")) %>% filter(!CharacteristicName %in% remove_params$Unique.parameters)
INdatPull$State<-c("IN")
INdatPull$Id_num<-c(seq(1:nrow(INdatPull)))
INdatPull <- INdatPull %>% 
  unite('Obs_Id', c(State, Id_num), sep = "-", remove = FALSE)
names(INdatPull)
summary(INdatPull)

MAdatPull<-read.csv(paste0(file.path,"MA_cleaned.csv")) %>% filter(!CharacteristicName %in% remove_params$Unique.parameters)
MAdatPull$State<-c("MA")
MAdatPull$Id_num<-c(seq(1:nrow(MAdatPull)))
MAdatPull <- MAdatPull %>% 
  unite('Obs_Id', c(State, Id_num), sep = "-", remove = FALSE)
names(MAdatPull)
summary(MAdatPull)

MEdatPull<-read.csv(paste0(file.path,"ME_cleaned.csv")) %>% filter(!CharacteristicName %in% remove_params$Unique.parameters)
MEdatPull$State<-c("ME")
MEdatPull$Id_num<-c(seq(1:nrow(MEdatPull)))
MEdatPull <- MEdatPull %>% 
  unite('Obs_Id', c(State, Id_num), sep = "-", remove = FALSE)
names(MEdatPull)
summary(MEdatPull)

MIdatPull<-read.csv(paste0(file.path,"MI_cleaned.csv")) %>% filter(!CharacteristicName %in% remove_params$Unique.parameters)
MIdatPull$State<-c("MI")
MIdatPull$Id_num<-c(seq(1:nrow(MIdatPull)))
MIdatPull <- MIdatPull %>% 
  unite('Obs_Id', c(State, Id_num), sep = "-", remove = FALSE)
names(MIdatPull)
summary(MIdatPull)

MNdatPull<-read.csv(paste0(file.path,"MN_cleaned.csv")) %>% filter(!CharacteristicName %in% remove_params$Unique.parameters)
MNdatPull$State<-c("MN")
MNdatPull$Id_num<-c(seq(1:nrow(MNdatPull)))
MNdatPull <- MNdatPull %>% 
  unite('Obs_Id', c(State, Id_num), sep = "-", remove = FALSE)
names(MNdatPull)
summary(MNdatPull)

MOdatPull<-read.csv(paste0(file.path,"MO_cleaned.csv")) %>% filter(!CharacteristicName %in% remove_params$Unique.parameters)
MOdatPull$State<-c("MO")
MOdatPull$Id_num<-c(seq(1:nrow(MOdatPull)))
MOdatPull <- MOdatPull %>% 
  unite('Obs_Id', c(State, Id_num), sep = "-", remove = FALSE)
names(MOdatPull)
summary(MOdatPull)

NHdatPull<-read.csv(paste0(file.path,"NH_cleaned.csv")) %>% filter(!CharacteristicName %in% remove_params$Unique.parameters)
NHdatPull$State<-c("NH")
NHdatPull$Id_num<-c(seq(1:nrow(NHdatPull)))
NHdatPull <- NHdatPull %>% 
  unite('Obs_Id', c(State, Id_num), sep = "-", remove = FALSE)
names(NHdatPull)
summary(NHdatPull)

NJdatPull<-read.csv(paste0(file.path,"NJ_cleaned.csv")) %>% filter(!CharacteristicName %in% remove_params$Unique.parameters)
NJdatPull$State<-c("NJ")
NJdatPull$Id_num<-c(seq(1:nrow(NJdatPull)))
NJdatPull <- NJdatPull %>% 
  unite('Obs_Id', c(State, Id_num), sep = "-", remove = FALSE)
names(NJdatPull)
summary(NJdatPull)

NYdatPull<-read.csv(paste0(file.path,"NY_cleaned.csv")) %>% filter(!CharacteristicName %in% remove_params$Unique.parameters)
NYdatPull$State<-c("NY")
NYdatPull$Id_num<-c(seq(1:nrow(NYdatPull)))
NYdatPull <- NYdatPull %>% 
  unite('Obs_Id', c(State, Id_num), sep = "-", remove = FALSE)
names(NYdatPull)
summary(NYdatPull)

OHdatPull<-read.csv(paste0(file.path,"OH_cleaned.csv")) %>% filter(!CharacteristicName %in% remove_params$Unique.parameters)
OHdatPull$State<-c("OH")
OHdatPull$Id_num<-c(seq(1:nrow(OHdatPull)))
OHdatPull <- OHdatPull %>% 
  unite('Obs_Id', c(State, Id_num), sep = "-", remove = FALSE)
names(OHdatPull)
summary(OHdatPull)

PAdatPull<-read.csv(paste0(file.path,"PA_cleaned.csv")) %>% filter(!CharacteristicName %in% remove_params$Unique.parameters)
PAdatPull$State<-c("PA")
PAdatPull$Id_num<-c(seq(1:nrow(PAdatPull)))
PAdatPull <- PAdatPull %>% 
  unite('Obs_Id', c(State, Id_num), sep = "-", remove = FALSE)
names(PAdatPull)
summary(PAdatPull)

RIdatPull<-read.csv(paste0(file.path,"RI_cleaned.csv")) %>% filter(!CharacteristicName %in% remove_params$Unique.parameters)
RIdatPull$State<-c("RI")
RIdatPull$Id_num<-c(seq(1:nrow(RIdatPull)))
RIdatPull <- RIdatPull %>% 
  unite('Obs_Id', c(State, Id_num), sep = "-", remove = FALSE)
names(RIdatPull)
summary(RIdatPull)

VTdatPull<-read.csv(paste0(file.path,"VT_cleaned.csv")) %>% filter(!CharacteristicName %in% remove_params$Unique.parameters)
VTdatPull$State<-c("VT")
VTdatPull$Id_num<-c(seq(1:nrow(VTdatPull)))
VTdatPull <- VTdatPull %>% 
  unite('Obs_Id', c(State, Id_num), sep = "-", remove = FALSE)
names(VTdatPull)
summary(VTdatPull)

WIdatPull<-read.csv(paste0(file.path,"WI_cleaned.csv")) %>% filter(!CharacteristicName %in% remove_params$Unique.parameters)
WIdatPull$State<-c("WI")
WIdatPull$Id_num<-c(seq(1:nrow(WIdatPull)))
WIdatPull <- WIdatPull %>% 
  unite('Obs_Id', c(State, Id_num), sep = "-", remove = FALSE)
names(WIdatPull)
summary(WIdatPull)


#LAGOSUS STATES PULL

IDdatPull<-read.csv(paste0(file.path,"ID_alldata_1975_to_2020.csv")) %>% filter(!CharacteristicName %in% remove_params$Unique.parameters)
IDdatPull$State<-c("ID")
IDdatPull$Id_num<-c(seq(1:nrow(IDdatPull)))
IDdatPull <- IDdatPull %>% 
  unite('Obs_Id', c(State, Id_num), sep = "-", remove = FALSE)
names(IDdatPull)
summary(IDdatPull)

DEdatPull<-read.csv(paste0(file.path,"DE_alldata_1975_to_2020.csv")) %>% filter(!CharacteristicName %in% remove_params$Unique.parameters)
DEdatPull$State<-c("DE")
DEdatPull$Id_num<-c(seq(1:nrow(DEdatPull)))
DEdatPull <- DEdatPull %>% 
  unite('Obs_Id', c(State, Id_num), sep = "-", remove = FALSE)
names(DEdatPull)
summary(DEdatPull)

MDdatPull<-read.csv(paste0(file.path,"MD_alldata_1975_to_2020.csv")) %>% filter(!CharacteristicName %in% remove_params$Unique.parameters)
MDdatPull$State<-c("MD")
MDdatPull$Id_num<-c(seq(1:nrow(MDdatPull)))
MDdatPull <- MDdatPull %>% 
  unite('Obs_Id', c(State, Id_num), sep = "-", remove = FALSE)
names(MDdatPull)
summary(MDdatPull)

VAdatPull<-read.csv(paste0(file.path,"VA_alldata_1975_to_2020.csv")) %>% filter(!CharacteristicName %in% remove_params$Unique.parameters)
VAdatPull$State<-c("VA")
VAdatPull$Id_num<-c(seq(1:nrow(VAdatPull)))
VAdatPull <- VAdatPull %>% 
  unite('Obs_Id', c(State, Id_num), sep = "-", remove = FALSE)
names(VAdatPull)
summary(VAdatPull)

COdatPull<-read.csv(paste0(file.path,"CO_alldata_1975_to_2020.csv")) %>% filter(!CharacteristicName %in% remove_params$Unique.parameters)
COdatPull$State<-c("CO")
COdatPull$Id_num<-c(seq(1:nrow(COdatPull)))
COdatPull <- COdatPull %>% 
  unite('Obs_Id', c(State, Id_num), sep = "-", remove = FALSE)
names(COdatPull)
summary(COdatPull)

AZdatPull<-read.csv(paste0(file.path,"AZ_alldata_1975_to_2020.csv")) %>% filter(!CharacteristicName %in% remove_params$Unique.parameters)
AZdatPull$State<-c("AZ")
AZdatPull$Id_num<-c(seq(1:nrow(AZdatPull)))
AZdatPull <- AZdatPull %>% 
  unite('Obs_Id', c(State, Id_num), sep = "-", remove = FALSE)
names(AZdatPull)
summary(AZdatPull)

ARdatPull<-read.csv(paste0(file.path,"AR_alldata_1975_to_2020.csv")) %>% filter(!CharacteristicName %in% remove_params$Unique.parameters)
ARdatPull$State<-c("AR")
ARdatPull$Id_num<-c(seq(1:nrow(ARdatPull)))
ARdatPull <- ARdatPull %>% 
  unite('Obs_Id', c(State, Id_num), sep = "-", remove = FALSE)
names(ARdatPull)
summary(ARdatPull)

ALdatPull<-read.csv(paste0(file.path,"AL_alldata_1975_to_2020.csv")) %>% filter(!CharacteristicName %in% remove_params$Unique.parameters)
ALdatPull$State<-c("AL")
ALdatPull$Id_num<-c(seq(1:nrow(ALdatPull)))
ALdatPull <- ALdatPull %>% 
  unite('Obs_Id', c(State, Id_num), sep = "-", remove = FALSE)
names(ALdatPull)
summary(ALdatPull)

WYdatPull<-read.csv(paste0(file.path,"WY_alldata_1975_to_2020.csv")) %>% filter(!CharacteristicName %in% remove_params$Unique.parameters)
WYdatPull$State<-c("WY")
WYdatPull$Id_num<-c(seq(1:nrow(WYdatPull)))
WYdatPull <- WYdatPull %>% 
  unite('Obs_Id', c(State, Id_num), sep = "-", remove = FALSE)
names(WYdatPull)
summary(WYdatPull)

KYdatPull<-read.csv(paste0(file.path,"KY_alldata_1975_to_2020.csv")) %>% filter(!CharacteristicName %in% remove_params$Unique.parameters)
KYdatPull$State<-c("KY")
KYdatPull$Id_num<-c(seq(1:nrow(KYdatPull)))
KYdatPull <- KYdatPull %>% 
  unite('Obs_Id', c(State, Id_num), sep = "-", remove = FALSE)
names(KYdatPull)
summary(KYdatPull)

NVdatPull<-read.csv(paste0(file.path,"NV_alldata_1975_to_2020.csv")) %>% filter(!CharacteristicName %in% remove_params$Unique.parameters)
NVdatPull$State<-c("NV")
NVdatPull$Id_num<-c(seq(1:nrow(NVdatPull)))
NVdatPull <- NVdatPull %>% 
  unite('Obs_Id', c(State, Id_num), sep = "-", remove = FALSE)
names(NVdatPull)
summary(NVdatPull)

OKdatPull<-read.csv(paste0(file.path,"OK_alldata_1975_to_2020.csv")) %>% filter(!CharacteristicName %in% remove_params$Unique.parameters)
OKdatPull$State<-c("OK")
OKdatPull$Id_num<-c(seq(1:nrow(OKdatPull)))
OKdatPull <- OKdatPull %>% 
  unite('Obs_Id', c(State, Id_num), sep = "-", remove = FALSE)
names(OKdatPull)
summary(OKdatPull)

WAdatPull<-read.csv(paste0(file.path,"WA_alldata_1975_to_2020.csv")) %>% filter(!CharacteristicName %in% remove_params$Unique.parameters)
WAdatPull$State<-c("WA")
WAdatPull$Id_num<-c(seq(1:nrow(WAdatPull)))
WAdatPull <- WAdatPull %>% 
  unite('Obs_Id', c(State, Id_num), sep = "-", remove = FALSE)
names(WAdatPull)
summary(WAdatPull)

KSdatPull<-read.csv(paste0(file.path,"KS_alldata_1975_to_2020.csv")) %>% filter(!CharacteristicName %in% remove_params$Unique.parameters)
KSdatPull$State<-c("KS")
KSdatPull$Id_num<-c(seq(1:nrow(KSdatPull)))
KSdatPull <- KSdatPull %>% 
  unite('Obs_Id', c(State, Id_num), sep = "-", remove = FALSE)
names(KSdatPull)
summary(KSdatPull)

TNdatPull<-read.csv(paste0(file.path,"TN_alldata_1975_to_2020.csv")) %>% filter(!CharacteristicName %in% remove_params$Unique.parameters)
TNdatPull$State<-c("TN")
TNdatPull$Id_num<-c(seq(1:nrow(TNdatPull)))
TNdatPull <- TNdatPull %>% 
  unite('Obs_Id', c(State, Id_num), sep = "-", remove = FALSE)
names(TNdatPull)
summary(TNdatPull)

CAdatPull<-read.csv(paste0(file.path,"CA_alldata_1975_to_2020.csv")) %>% filter(!CharacteristicName %in% remove_params$Unique.parameters)
CAdatPull$State<-c("CA")
CAdatPull$Id_num<-c(seq(1:nrow(CAdatPull)))
CAdatPull <- CAdatPull %>% 
  unite('Obs_Id', c(State, Id_num), sep = "-", remove = FALSE)
names(CAdatPull)
summary(CAdatPull)

FLdatPull<-read.csv(paste0(file.path,"FL_alldata_1975_to_2020.csv")) %>% filter(!CharacteristicName %in% remove_params$Unique.parameters)
FLdatPull$State<-c("FL")
FLdatPull$Id_num<-c(seq(1:nrow(FLdatPull)))
FLdatPull <- FLdatPull %>% 
  unite('Obs_Id', c(State, Id_num), sep = "-", remove = FALSE)
names(FLdatPull)
summary(FLdatPull)

GAdatPull<-read.csv(paste0(file.path,"GA_alldata_1975_to_2020.csv")) %>% filter(!CharacteristicName %in% remove_params$Unique.parameters)
GAdatPull$State<-c("GA")
GAdatPull$Id_num<-c(seq(1:nrow(GAdatPull)))
GAdatPull <- GAdatPull %>% 
  unite('Obs_Id', c(State, Id_num), sep = "-", remove = FALSE)
names(GAdatPull)
summary(GAdatPull)

LAdatPull<-read.csv(paste0(file.path,"LA_alldata_1975_to_2020.csv")) %>% filter(!CharacteristicName %in% remove_params$Unique.parameters)
LAdatPull$State<-c("LA")
LAdatPull$Id_num<-c(seq(1:nrow(LAdatPull)))
LAdatPull <- LAdatPull %>% 
  unite('Obs_Id', c(State, Id_num), sep = "-", remove = FALSE)
names(LAdatPull)
summary(LAdatPull)

MSdatPull<-read.csv(paste0(file.path,"MS_alldata_1975_to_2020.csv")) %>% filter(!CharacteristicName %in% remove_params$Unique.parameters)
MSdatPull$State<-c("MS")
MSdatPull$Id_num<-c(seq(1:nrow(MSdatPull)))
MSdatPull <- MSdatPull %>% 
  unite('Obs_Id', c(State, Id_num), sep = "-", remove = FALSE)
names(MSdatPull)
summary(MSdatPull)

MTdatPull<-read.csv(paste0(file.path,"MT_alldata_1975_to_2020.csv")) %>% filter(!CharacteristicName %in% remove_params$Unique.parameters)
MTdatPull$State<-c("MT")
MTdatPull$Id_num<-c(seq(1:nrow(MTdatPull)))
MTdatPull <- MTdatPull %>% 
  unite('Obs_Id', c(State, Id_num), sep = "-", remove = FALSE)
names(MTdatPull)
summary(MTdatPull)

NEdatPull<-read.csv(paste0(file.path,"NE_alldata_1975_to_2020.csv")) %>% filter(!CharacteristicName %in% remove_params$Unique.parameters)
NEdatPull$State<-c("NE")
NEdatPull$Id_num<-c(seq(1:nrow(NEdatPull)))
NEdatPull <- NEdatPull %>% 
  unite('Obs_Id', c(State, Id_num), sep = "-", remove = FALSE)
names(NEdatPull)
summary(NEdatPull)

NMdatPull<-read.csv(paste0(file.path,"NM_alldata_1975_to_2020.csv")) %>% filter(!CharacteristicName %in% remove_params$Unique.parameters)
NMdatPull$State<-c("NM")
NMdatPull$Id_num<-c(seq(1:nrow(NMdatPull)))
NMdatPull <- NMdatPull %>% 
  unite('Obs_Id', c(State, Id_num), sep = "-", remove = FALSE)
names(NMdatPull)
summary(NMdatPull)

NCdatPull<-read.csv(paste0(file.path,"NC_alldata_1975_to_2020.csv")) %>% filter(!CharacteristicName %in% remove_params$Unique.parameters)
NCdatPull$State<-c("NC")
NCdatPull$Id_num<-c(seq(1:nrow(NCdatPull)))
NCdatPull <- NCdatPull %>% 
  unite('Obs_Id', c(State, Id_num), sep = "-", remove = FALSE)
names(NCdatPull)
summary(NCdatPull)

NDdatPull<-read.csv(paste0(file.path,"ND_alldata_1975_to_2020.csv")) %>% filter(!CharacteristicName %in% remove_params$Unique.parameters)
NDdatPull$State<-c("ND")
NDdatPull$Id_num<-c(seq(1:nrow(NDdatPull)))
NDdatPull <- NDdatPull %>% 
  unite('Obs_Id', c(State, Id_num), sep = "-", remove = FALSE)
names(NDdatPull)
summary(NDdatPull)

ORdatPull<-read.csv(paste0(file.path,"OR_alldata_1975_to_2020.csv")) %>% filter(!CharacteristicName %in% remove_params$Unique.parameters)
ORdatPull$State<-c("OR")
ORdatPull$Id_num<-c(seq(1:nrow(ORdatPull)))
ORdatPull <- ORdatPull %>% 
  unite('Obs_Id', c(State, Id_num), sep = "-", remove = FALSE)
names(ORdatPull)
summary(ORdatPull)

SCdatPull<-read.csv(paste0(file.path,"SC_alldata_1975_to_2020.csv")) %>% filter(!CharacteristicName %in% remove_params$Unique.parameters)
SCdatPull$State<-c("SC")
SCdatPull$Id_num<-c(seq(1:nrow(SCdatPull)))
SCdatPull <- SCdatPull %>% 
  unite('Obs_Id', c(State, Id_num), sep = "-", remove = FALSE)
names(SCdatPull)
summary(SCdatPull)

SDdatPull<-read.csv(paste0(file.path,"SD_alldata_1975_to_2020.csv")) %>% filter(!CharacteristicName %in% remove_params$Unique.parameters)
SDdatPull$State<-c("SD")
SDdatPull$Id_num<-c(seq(1:nrow(SDdatPull)))
SDdatPull <- SDdatPull %>% 
  unite('Obs_Id', c(State, Id_num), sep = "-", remove = FALSE)
names(SDdatPull)
summary(SDdatPull)

TXdatPull<-read.csv(paste0(file.path,"TX_alldata_1975_to_2020.csv")) %>% filter(!CharacteristicName %in% remove_params$Unique.parameters)
TXdatPull$State<-c("TX")
TXdatPull$Id_num<-c(seq(1:nrow(TXdatPull)))
TXdatPull <- TXdatPull %>% 
  unite('Obs_Id', c(State, Id_num), sep = "-", remove = FALSE)
names(TXdatPull)
summary(TXdatPull)

UTdatPull<-read.csv(paste0(file.path,"UT_alldata_1975_to_2020.csv")) %>% filter(!CharacteristicName %in% remove_params$Unique.parameters)
UTdatPull$State<-c("UT")
UTdatPull$Id_num<-c(seq(1:nrow(UTdatPull)))
UTdatPull <- UTdatPull %>% 
  unite('Obs_Id', c(State, Id_num), sep = "-", remove = FALSE)
names(UTdatPull)
summary(UTdatPull)


```


```{r}
allstates <- do.call("rbind", lapply(ls(pattern='datPull'),get))
allstates<-allstates %>% select(-ActivityStartTime.TimeZoneCode, -ActivityEndTime.Time, -ActivityEndTime.TimeZoneCode, -HydrologicCondition, -HydrologicEvent, -LaboratoryName, -AnalysisStartDate, -PreparationStartDate)
allstates<-allstates %>% select(-ActivityEndDate, -ResultTimeBasisText, -ResultParticleSizeBasisText, -ActivityStartDateTime, -ActivityEndDateTime)
#figure out how to autodelete files that contain datpull
merge1 <- allstates %>% group_by(State) %>% summarize(n=n())
rm(list=ls(pattern="datPull"))
```


```{r}
#removing data that have Y's instead of keeping data that have N's
read.csv("list of unique parameters to remove.csv") -> remove_params #update this
data<- allstates[allstates$CharacteristicName %notin% remove_params$Unique.parameters,]
rm(allstates)
gc()
merge2 <- data %>% group_by(State) %>% summarize(n=n())
data$ActivityStartDate<-lubridate:::ymd(data$ActivityStartDate)
data<-data %>% filter(ActivityStartDate >= lubridate:::ymd ("1975-01-01")) %>% filter(ActivityStartDate <= lubridate:::ymd("2020-11-20"))
write.csv(unique(data$CharacteristicName), file = "unique_characteristicnames.csv")

```

```{r}
data <- data %>% 
  unite('Method_Id', c(ResultAnalyticalMethod.MethodIdentifierContext, ResultAnalyticalMethod.MethodIdentifier), sep = " ", remove = FALSE)
data<-data %>% select(-ResultAnalyticalMethod.MethodIdentifierContext, -ResultAnalyticalMethod.MethodIdentifier)
#get only locations that have a lagoslakeid
lagos_link <- read_csv("lagos_wqp_20210920.csv") %>% 
    rename(MonitoringLocationIdentifier = wqp_monitoringlocationidentifier)
data <- data %>% left_join(lagos_link) %>% drop_na(lagoslakeid)
merge2 = data %>% group_by(State) %>% summarize(n=n())
rm(allstates)
rm(lagos_link)
gc()

str(data$ResultMeasureValue)
sum(is.na(data$ResultMeasureValue))
data1<-data %>% filter(!is.na(ResultMeasureValue))
data2<-data %>% filter(!is.na(DetectionQuantitationLimitMeasure.MeasureValue)) %>% filter(is.na(ResultMeasureValue))
data<-rbind(data1, data2)
rm(data1, data2)
gc()
```


```{r Check-for-Activity-type}
#looking at activity type codes #getting rid of quality control vars
unique(data$ActivityTypeCode)
remove_activity <- unique(data$ActivityTypeCode)
activitytype_keep<-c(
  "Quality Control Sample-Field Replicate", 
  "Quality Control Sample-Field Blank", 
  "Quality Control Field Replicate Msr/Obs", 
  "Quality Control Field Replicate Portable Data Logger", 
  "Quality Control Sample-Reference Sample", 
  "Quality Control Sample-Field Spike", 
  "Quality Control Sample-Lab Matrix Spike", 
  "Quality Control Field Sample Equipment Rinsate Blank", 
  "Quality Control Sample-Spike Solution",
  "Quality Control Sample-Measurement Precision Sample", 
  "Quality Control Sample-Other", 
  "Quality Control Sample-Equipment Blank",
  "Quality Control Sample-Inter-lab Split", 
  "Quality Control Sample-Lab Spike", 
  "Quality Control Sample-Lab Matrix Spike Duplicate",
  "Quality Control Sample-Lab Duplicate", 
  "Quality Control Sample-Blind Duplicate", 
  "Quality Control Sample-Trip Blank", 
  "Quality Control Alternative Measurement Sensitivity Plus", 
  "Quality Control Sample-Lab Blank", 
  "Quality Control Alternative Measurement Sensitivity Plus", 
  "Quality Control Sample-Lab Blank", 
  "Quality Control Sample-Blind", 
  "Quality Control Sample-Reagent Blank"
  )
remove_activity <- remove_activity[!remove_activity %in% activitytype_keep]
remove_activity

data<-data[which(data$ActivityTypeCode %notin% activitytype_keep),]
unique(data$ActivityTypeCode)
```


```{r }
#manually checking these columns to see if these is data we keep or can drop

unique(data$SubjectTaxonomicName) #expected it to be na - to make sure nothing we need is in there
data<-data %>% filter(is.na(SubjectTaxonomicName))
unique(data$SampleTissueAnatomyName) #also NA's - expected
unique(data$ActivityMediaSubdivisionName)
subdivision_remove<-c("Groundwater", 
                      "Elutriation", 
                      "Wastewater Treatment Plant Effluent", 
                      "Interstitial",
                      "Interstitial Water",
                      "Surface Soil/Sediment",
                      "Soil moisture",
                      "Landfill effluent",
                      "Bulk deposition", 
                      "Surface Water Sediment",
                      "Wet Fall Material",
                      "Stormwater"
                      )
data<-data %>% filter(!ActivityMediaSubdivisionName %in% subdivision_remove)
unique(data$ActivityMediaSubdivisionName)
rm(subdivision_remove)

#only keeping subdivision name with surface water and NA's - dropping everything else
#want to filter things out that are non-ambigouous - keep unknowns - eg. filter out tissue but keep uncertain data
#data<-data %>% filter(ActivityMediaSubdivisionName == "Surface Water" | is.na(ActivityMediaSubdivisionName))
#unique(data$ActivityMediaSubdivisionName)

unique(data$ResultStatusIdentifier)
data <- data %>% filter(ResultStatusIdentifier != "Rejected")

unique(data$ResultValueTypeName)
value_typename_remove<-c("Estimated",
                         "Calculated")
data<-data %>% filter(!ResultValueTypeName %in% value_typename_remove)
unique(data$ResultValueTypeName)
rm(value_typename_remove)

unique(data$ResultAnalyticalMethod.MethodName)
data <- data %>% filter(ResultAnalyticalMethod.MethodName !="Computation by NWIS algorithm" | is.na(ResultAnalyticalMethod.MethodName))

unique(data$ResultDetectionConditionText)
#filtered out vars we don't need in resultsdetection condition text - did it in multistep because R doesn't handle multiple OR statements well

data<-data %>% filter(ResultDetectionConditionText != "Systematic Contamination" | is.na(ResultDetectionConditionText))
unique(data$ResultDetectionConditionText)



unique(data$ResultSampleFractionText)
types_to_exclude<-c("Bed Sediment", 
                    "Recoverable", 
                    "Acid Soluble", 
                    "Total Recoverable", 
                    "Volatile", 
                    "Non-volatile", 
                    "Supernate",
                    "Total Recovrble",
                    "Total Residual",
                    "Extractable")

data<-data %>% filter(!ResultSampleFractionText %in% types_to_exclude)
unique(data$ResultSampleFractionText)
rm(types_to_exclude)
unique(data$SampleAquifer)
data<-data %>% filter(is.na(SampleAquifer))
unique(data$SampleAquifer)

data<-data %>% select(-ActivityMediaName, -ActivityMediaSubdivisionName, -SampleAquifer, -SubjectTaxonomicName, -SampleTissueAnatomyName)
gc()
merge2<-data %>% group_by(State) %>% summarise(n=n())
saveRDS(data, "USlimno.rds")
#data<-readRDS("USlimno.rds")

#depthheight conversions 

#ActivityDepthHeightMeasure.MeasureUnitCode
#ActivityDepthHeightMeasure.MeasureValue

unique(data$ActivityDepthHeightMeasure.MeasureUnitCode) 
data$ActivityDepthHeightMeasure.MeasureValue<-ifelse(data$ActivityDepthHeightMeasure.MeasureUnitCode == "ft", data$ActivityDepthHeightMeasure.MeasureValue*0.3048, data$ActivityDepthHeightMeasure.MeasureValue)
data$ActivityDepthHeightMeasure.MeasureValue<-ifelse(data$ActivityDepthHeightMeasure.MeasureUnitCode == "feet", data$ActivityDepthHeightMeasure.MeasureValue*0.3048, data$ActivityDepthHeightMeasure.MeasureValue)
data$ActivityDepthHeightMeasure.MeasureValue<-ifelse(data$ActivityDepthHeightMeasure.MeasureUnitCode == "cm", data$ActivityDepthHeightMeasure.MeasureValue*0.01, data$ActivityDepthHeightMeasure.MeasureValue)
data$ActivityDepthHeightMeasure.MeasureValue<-ifelse(data$ActivityDepthHeightMeasure.MeasureUnitCode == "mm", data$ActivityDepthHeightMeasure.MeasureValue*0.001, data$ActivityDepthHeightMeasure.MeasureValue)
data$ActivityDepthHeightMeasure.MeasureValue<-ifelse(data$ActivityDepthHeightMeasure.MeasureUnitCode == "in", data$ActivityDepthHeightMeasure.MeasureValue*0.0254, data$ActivityDepthHeightMeasure.MeasureValue)


unitstodrop<-c("FTU", "None")
data<-data %>% filter(!ActivityDepthHeightMeasure.MeasureUnitCode %in% unitstodrop)
unique(data$ActivityDepthHeightMeasure.MeasureUnitCode) 
data$ActivityDepthHeightMeasure.MeasureUnitCode[!is.na(data$ActivityDepthHeightMeasure.MeasureUnitCode)]<-"m"


#ResultDepthHeightMeasure.MeasureValue
#ResultDepthHeightMeasure.MeasureUnitCOde


unique(data$ResultDepthHeightMeasure.MeasureValue[is.na(as.numeric(data$ResultDepthHeightMeasure.MeasureValue))])

data$ResultDepthHeightMeasure.MeasureValue<-as.numeric(as.character(data$ResultDepthHeightMeasure.MeasureValue))
unique(data$ResultDepthHeightMeasure.MeasureValue) 

data$ResultDepthHeightMeasure.MeasureValue<-ifelse(data$ResultDepthHeightMeasure.MeasureUnitCode == "ft", data$ResultDepthHeightMeasure.MeasureValue*0.3048, data$ResultDepthHeightMeasure.MeasureValue)
data$ResultDepthHeightMeasure.MeasureValue<-ifelse(data$ResultDepthHeightMeasure.MeasureUnitCode == "cm", data$ResultDepthHeightMeasure.MeasureValue*0.01, data$ResultDepthHeightMeasure.MeasureValue)
data$ResultDepthHeightMeasure.MeasureValue<-ifelse(data$ResultDepthHeightMeasure.MeasureUnitCode == "in", data$ResultDepthHeightMeasure.MeasureValue*0.0254, data$ResultDepthHeightMeasure.MeasureValue)
data$ResultDepthHeightMeasure.MeasureUnitCode[!is.na(data$ResultDepthHeightMeasure.MeasureUnitCode)]<-"m"

#ActivityTopDepthHeightMeasure.MeasureValue
#ActivityTopDepthHeightMeasure.MeasureUnitCode
unique(data$ActivityTopDepthHeightMeasure.MeasureValue[is.na(as.numeric(data$ActivityTopDepthHeightMeasure.MeasureValue))])
data <- data %>% mutate(ActivityTopDepthHeightMeasure.MeasureValue = case_when(ActivityTopDepthHeightMeasure.MeasureValue=="0-2" ~ "0",TRUE ~ as.character(ActivityTopDepthHeightMeasure.MeasureValue)))

data <- data %>% mutate(ActivityTopDepthHeightMeasure.MeasureValue = case_when(ActivityTopDepthHeightMeasure.MeasureValue=="'0.85" ~ "0.85",TRUE ~ as.character(ActivityTopDepthHeightMeasure.MeasureValue)))


data$ActivityTopDepthHeightMeasure.MeasureValue<-as.numeric(as.character(data$ActivityTopDepthHeightMeasure.MeasureValue))

unique(data$ActivityTopDepthHeightMeasure.MeasureUnitCode) 
data$ActivityTopDepthHeightMeasure.MeasureValue<-ifelse(data$ActivityTopDepthHeightMeasure.MeasureUnitCode == "ft", data$ActivityTopDepthHeightMeasure.MeasureValue*0.3048, data$ActivityTopDepthHeightMeasure.MeasureValue)
data$ActivityTopDepthHeightMeasure.MeasureValue<-ifelse(data$ActivityTopDepthHeightMeasure.MeasureUnitCode == "feet", data$ActivityTopDepthHeightMeasure.MeasureValue*0.3048, data$ActivityTopDepthHeightMeasure.MeasureValue)
data$ActivityTopDepthHeightMeasure.MeasureUnitCode[!is.na(data$ActivityTopDepthHeightMeasure.MeasureUnitCode)]<-"m"


#ActivityBottomDepthHeightMeasure.MeasureUnitCode
#ActivityBottomDepthHeightMeasure.MeasureValue

unique(data$ActivityBottomDepthHeightMeasure.MeasureUnitCode)
unique(data$ActivityBottomDepthHeightMeasure.MeasureValue[is.na(as.numeric(data$ActivityBottomDepthHeightMeasure.MeasureValue))])

data <- data %>% mutate(ActivityBottomDepthHeightMeasure.MeasureValue = case_when(ActivityBottomDepthHeightMeasure.MeasureValue=="6.4-7.3" ~ "7.3",TRUE ~ as.character(ActivityBottomDepthHeightMeasure.MeasureValue)))

data <- data %>% mutate(ActivityBottomDepthHeightMeasure.MeasureValue = case_when(ActivityBottomDepthHeightMeasure.MeasureValue=="2-2.4" ~ "2.4",TRUE ~ as.character(ActivityBottomDepthHeightMeasure.MeasureValue)))

data <- data %>% mutate(ActivityBottomDepthHeightMeasure.MeasureValue = case_when(ActivityBottomDepthHeightMeasure.MeasureValue=="3-3.7" ~ "3.7",TRUE ~ as.character(ActivityBottomDepthHeightMeasure.MeasureValue)))

data <- data %>% mutate(ActivityBottomDepthHeightMeasure.MeasureValue = case_when(ActivityBottomDepthHeightMeasure.MeasureValue=="7.9-8.5" ~ "8.5",TRUE ~ as.character(ActivityBottomDepthHeightMeasure.MeasureValue)))

data <- data %>% mutate(ActivityBottomDepthHeightMeasure.MeasureValue = case_when(ActivityBottomDepthHeightMeasure.MeasureValue=="4.6-5.2" ~ "5.2",TRUE ~ as.character(ActivityBottomDepthHeightMeasure.MeasureValue)))

data <- data %>% mutate(ActivityBottomDepthHeightMeasure.MeasureValue = case_when(ActivityBottomDepthHeightMeasure.MeasureValue=="4.3-4.6" ~ "4.6",TRUE ~ as.character(ActivityBottomDepthHeightMeasure.MeasureValue)))

data <- data %>% mutate(ActivityBottomDepthHeightMeasure.MeasureValue = case_when(ActivityBottomDepthHeightMeasure.MeasureValue=="10.7-11" ~ "11",TRUE ~ as.character(ActivityBottomDepthHeightMeasure.MeasureValue)))

data <- data %>% mutate(ActivityBottomDepthHeightMeasure.MeasureValue = case_when(ActivityBottomDepthHeightMeasure.MeasureValue=="10.1-10.7" ~ "10.7",TRUE ~ as.character(ActivityBottomDepthHeightMeasure.MeasureValue)))

data <- data %>% mutate(ActivityBottomDepthHeightMeasure.MeasureValue = case_when(ActivityBottomDepthHeightMeasure.MeasureValue=="6.4-6.7" ~ "6.7",TRUE ~ as.character(ActivityBottomDepthHeightMeasure.MeasureValue)))

data <- data %>% mutate(ActivityBottomDepthHeightMeasure.MeasureValue = case_when(ActivityBottomDepthHeightMeasure.MeasureValue=="5.8-7" ~ "7",TRUE ~ as.character(ActivityBottomDepthHeightMeasure.MeasureValue)))






data <- data %>% mutate(ActivityBottomDepthHeightMeasure.MeasureValue = case_when(ActivityBottomDepthHeightMeasure.MeasureValue=="11.6-12.2" ~ "12.2",TRUE ~ as.character(ActivityBottomDepthHeightMeasure.MeasureValue)))

data <- data %>% mutate(ActivityBottomDepthHeightMeasure.MeasureValue = case_when(ActivityBottomDepthHeightMeasure.MeasureValue=="14-15.8" ~ "15.8",TRUE ~ as.character(ActivityBottomDepthHeightMeasure.MeasureValue)))

data <- data %>% mutate(ActivityBottomDepthHeightMeasure.MeasureValue = case_when(ActivityBottomDepthHeightMeasure.MeasureValue=="10.1-11" ~ "11",TRUE ~ as.character(ActivityBottomDepthHeightMeasure.MeasureValue)))

data <- data %>% mutate(ActivityBottomDepthHeightMeasure.MeasureValue = case_when(ActivityBottomDepthHeightMeasure.MeasureValue=="10.5-11" ~ "11",TRUE ~ as.character(ActivityBottomDepthHeightMeasure.MeasureValue)))

data <- data %>% mutate(ActivityBottomDepthHeightMeasure.MeasureValue = case_when(ActivityBottomDepthHeightMeasure.MeasureValue=="13.7-14.3" ~ "14.3",TRUE ~ as.character(ActivityBottomDepthHeightMeasure.MeasureValue)))

data <- data %>% mutate(ActivityBottomDepthHeightMeasure.MeasureValue = case_when(ActivityBottomDepthHeightMeasure.MeasureValue=="7.5-8.5" ~ "8.5",TRUE ~ as.character(ActivityBottomDepthHeightMeasure.MeasureValue)))

data <- data %>% mutate(ActivityBottomDepthHeightMeasure.MeasureValue = case_when(ActivityBottomDepthHeightMeasure.MeasureValue=="5.5-5.8" ~ "5.8",TRUE ~ as.character(ActivityBottomDepthHeightMeasure.MeasureValue)))

data <- data %>% mutate(ActivityBottomDepthHeightMeasure.MeasureValue = case_when(ActivityBottomDepthHeightMeasure.MeasureValue=="16.8-18" ~ "18",TRUE ~ as.character(ActivityBottomDepthHeightMeasure.MeasureValue)))

data <- data %>% mutate(ActivityBottomDepthHeightMeasure.MeasureValue = case_when(ActivityBottomDepthHeightMeasure.MeasureValue=="12.2-13.9" ~ "13.9",TRUE ~ as.character(ActivityBottomDepthHeightMeasure.MeasureValue)))

data <- data %>% mutate(ActivityBottomDepthHeightMeasure.MeasureValue = case_when(ActivityBottomDepthHeightMeasure.MeasureValue=="18-19" ~ "19",TRUE ~ as.character(ActivityBottomDepthHeightMeasure.MeasureValue)))

data <- data %>% mutate(ActivityBottomDepthHeightMeasure.MeasureValue = case_when(ActivityBottomDepthHeightMeasure.MeasureValue=="14.3-15.2" ~ "15.2",TRUE ~ as.character(ActivityBottomDepthHeightMeasure.MeasureValue)))




data <- data %>% mutate(ActivityBottomDepthHeightMeasure.MeasureValue = case_when(ActivityBottomDepthHeightMeasure.MeasureValue=="14-14.6" ~ "14.6",TRUE ~ as.character(ActivityBottomDepthHeightMeasure.MeasureValue)))

data <- data %>% mutate(ActivityBottomDepthHeightMeasure.MeasureValue = case_when(ActivityBottomDepthHeightMeasure.MeasureValue=="14-15.2" ~ "15.2",TRUE ~ as.character(ActivityBottomDepthHeightMeasure.MeasureValue)))

data <- data %>% mutate(ActivityBottomDepthHeightMeasure.MeasureValue = case_when(ActivityBottomDepthHeightMeasure.MeasureValue=="8.8-9.1" ~ "9.1",TRUE ~ as.character(ActivityBottomDepthHeightMeasure.MeasureValue)))

data <- data %>% mutate(ActivityBottomDepthHeightMeasure.MeasureValue = case_when(ActivityBottomDepthHeightMeasure.MeasureValue=="18-18.6" ~ "18.6",TRUE ~ as.character(ActivityBottomDepthHeightMeasure.MeasureValue)))

data <- data %>% mutate(ActivityBottomDepthHeightMeasure.MeasureValue = case_when(ActivityBottomDepthHeightMeasure.MeasureValue=="4.3-5.6" ~ "5.6",TRUE ~ as.character(ActivityBottomDepthHeightMeasure.MeasureValue)))

data <- data %>% mutate(ActivityBottomDepthHeightMeasure.MeasureValue = case_when(ActivityBottomDepthHeightMeasure.MeasureValue=="5.5-6.1" ~ "6.1",TRUE ~ as.character(ActivityBottomDepthHeightMeasure.MeasureValue)))

data <- data %>% mutate(ActivityBottomDepthHeightMeasure.MeasureValue = case_when(ActivityBottomDepthHeightMeasure.MeasureValue=="6.1-7.3" ~ "7.3",TRUE ~ as.character(ActivityBottomDepthHeightMeasure.MeasureValue)))

data <- data %>% mutate(ActivityBottomDepthHeightMeasure.MeasureValue = case_when(ActivityBottomDepthHeightMeasure.MeasureValue=="7.6-8.2" ~ "8.2",TRUE ~ as.character(ActivityBottomDepthHeightMeasure.MeasureValue)))

data <- data %>% mutate(ActivityBottomDepthHeightMeasure.MeasureValue = case_when(ActivityBottomDepthHeightMeasure.MeasureValue=="5.2-6.7" ~ "6.7",TRUE ~ as.character(ActivityBottomDepthHeightMeasure.MeasureValue)))

data <- data %>% mutate(ActivityBottomDepthHeightMeasure.MeasureValue = case_when(ActivityBottomDepthHeightMeasure.MeasureValue=="2.1-4.6" ~ "4.6",TRUE ~ as.character(ActivityBottomDepthHeightMeasure.MeasureValue)))

data <- data %>% mutate(ActivityBottomDepthHeightMeasure.MeasureValue = case_when(ActivityBottomDepthHeightMeasure.MeasureValue=="6.7-8.8" ~ "8.8",TRUE ~ as.character(ActivityBottomDepthHeightMeasure.MeasureValue)))





data <- data %>% mutate(ActivityBottomDepthHeightMeasure.MeasureValue = case_when(ActivityBottomDepthHeightMeasure.MeasureValue=="18.3-19.8" ~ "19.8",TRUE ~ as.character(ActivityBottomDepthHeightMeasure.MeasureValue)))

data <- data %>% mutate(ActivityBottomDepthHeightMeasure.MeasureValue = case_when(ActivityBottomDepthHeightMeasure.MeasureValue=="6.7-7.3" ~ "7.3",TRUE ~ as.character(ActivityBottomDepthHeightMeasure.MeasureValue)))

data <- data %>% mutate(ActivityBottomDepthHeightMeasure.MeasureValue = case_when(ActivityBottomDepthHeightMeasure.MeasureValue=="4.3-5.2" ~ "5.2",TRUE ~ as.character(ActivityBottomDepthHeightMeasure.MeasureValue)))

data <- data %>% mutate(ActivityBottomDepthHeightMeasure.MeasureValue = case_when(ActivityBottomDepthHeightMeasure.MeasureValue=="13.1-14.6" ~ "14.6",TRUE ~ as.character(ActivityBottomDepthHeightMeasure.MeasureValue)))

data <- data %>% mutate(ActivityBottomDepthHeightMeasure.MeasureValue = case_when(ActivityBottomDepthHeightMeasure.MeasureValue=="17.7-18.6" ~ "18.6",TRUE ~ as.character(ActivityBottomDepthHeightMeasure.MeasureValue)))

data <- data %>% mutate(ActivityBottomDepthHeightMeasure.MeasureValue = case_when(ActivityBottomDepthHeightMeasure.MeasureValue=="5.9-6.7" ~ "6.7",TRUE ~ as.character(ActivityBottomDepthHeightMeasure.MeasureValue)))

data <- data %>% mutate(ActivityBottomDepthHeightMeasure.MeasureValue = case_when(ActivityBottomDepthHeightMeasure.MeasureValue=="4.9-6.1" ~ "6.1",TRUE ~ as.character(ActivityBottomDepthHeightMeasure.MeasureValue)))

data <- data %>% mutate(ActivityBottomDepthHeightMeasure.MeasureValue = case_when(ActivityBottomDepthHeightMeasure.MeasureValue=="1.8-2.1" ~ "2.1",TRUE ~ as.character(ActivityBottomDepthHeightMeasure.MeasureValue)))

data <- data %>% mutate(ActivityBottomDepthHeightMeasure.MeasureValue = case_when(ActivityBottomDepthHeightMeasure.MeasureValue=="10.4-11.6" ~ "11.6",TRUE ~ as.character(ActivityBottomDepthHeightMeasure.MeasureValue)))

data <- data %>% mutate(ActivityBottomDepthHeightMeasure.MeasureValue = case_when(ActivityBottomDepthHeightMeasure.MeasureValue=="10.2-11.9" ~ "11.9",TRUE ~ as.character(ActivityBottomDepthHeightMeasure.MeasureValue)))

data <- data %>% mutate(ActivityBottomDepthHeightMeasure.MeasureValue = case_when(ActivityBottomDepthHeightMeasure.MeasureValue=="9.1-10.1" ~ "10.1",TRUE ~ as.character(ActivityBottomDepthHeightMeasure.MeasureValue)))





data <- data %>% mutate(ActivityBottomDepthHeightMeasure.MeasureValue = case_when(ActivityBottomDepthHeightMeasure.MeasureValue=="6.4-7" ~ "7",TRUE ~ as.character(ActivityBottomDepthHeightMeasure.MeasureValue)))

data <- data %>% mutate(ActivityBottomDepthHeightMeasure.MeasureValue = case_when(ActivityBottomDepthHeightMeasure.MeasureValue=="9.1-9.8" ~ "9.8",TRUE ~ as.character(ActivityBottomDepthHeightMeasure.MeasureValue)))

data <- data %>% mutate(ActivityBottomDepthHeightMeasure.MeasureValue = case_when(ActivityBottomDepthHeightMeasure.MeasureValue=="7.6-9.1" ~ "9.1",TRUE ~ as.character(ActivityBottomDepthHeightMeasure.MeasureValue)))

data <- data %>% mutate(ActivityBottomDepthHeightMeasure.MeasureValue = case_when(ActivityBottomDepthHeightMeasure.MeasureValue=="6.4-7.6" ~ "7.6",TRUE ~ as.character(ActivityBottomDepthHeightMeasure.MeasureValue)))

data <- data %>% mutate(ActivityBottomDepthHeightMeasure.MeasureValue = case_when(ActivityBottomDepthHeightMeasure.MeasureValue=="5.8-6.7" ~ "6.7",TRUE ~ as.character(ActivityBottomDepthHeightMeasure.MeasureValue)))

data <- data %>% mutate(ActivityBottomDepthHeightMeasure.MeasureValue = case_when(ActivityBottomDepthHeightMeasure.MeasureValue=="5.8-7.3" ~ "7.3",TRUE ~ as.character(ActivityBottomDepthHeightMeasure.MeasureValue)))

data <- data %>% mutate(ActivityBottomDepthHeightMeasure.MeasureValue = case_when(ActivityBottomDepthHeightMeasure.MeasureValue=="2.7-3.0" ~ "3.0",TRUE ~ as.character(ActivityBottomDepthHeightMeasure.MeasureValue)))

data <- data %>% mutate(ActivityBottomDepthHeightMeasure.MeasureValue = case_when(ActivityBottomDepthHeightMeasure.MeasureValue=="2.5-3" ~ "3",TRUE ~ as.character(ActivityBottomDepthHeightMeasure.MeasureValue)))

data <- data %>% mutate(ActivityBottomDepthHeightMeasure.MeasureValue = case_when(ActivityBottomDepthHeightMeasure.MeasureValue=="7.9-8.2" ~ "8.2",TRUE ~ as.character(ActivityBottomDepthHeightMeasure.MeasureValue)))

unique(data$ActivityBottomDepthHeightMeasure.MeasureValue[is.na(as.numeric(data$ActivityBottomDepthHeightMeasure.MeasureValue))])
data$ActivityBottomDepthHeightMeasure.MeasureValue<-as.numeric(as.character(data$ActivityBottomDepthHeightMeasure.MeasureValue))

unique(data$ActivityBottomDepthHeightMeasure.MeasureUnitCode)


data$ActivityBottomDepthHeightMeasure.MeasureValue<-ifelse(data$ActivityBottomDepthHeightMeasure.MeasureUnitCode == "ft", data$ActivityBottomDepthHeightMeasure.MeasureValue*0.3048, data$ActivityBottomDepthHeightMeasure.MeasureValue)
data$ActivityBottomDepthHeightMeasure.MeasureValue<-ifelse(data$ActivityBottomDepthHeightMeasure.MeasureUnitCode == "feet", data$ActivityBottomDepthHeightMeasure.MeasureValue*0.3048, data$ActivityBottomDepthHeightMeasure.MeasureValue)
data$ActivityBottomDepthHeightMeasure.MeasureUnitCode[!is.na(data$ActivityBottomDepthHeightMeasure.MeasureUnitCode)]<-"m"




#check
unique(data$ActivityDepthHeightMeasure.MeasureUnitCode)
unique(data$ResultDepthHeightMeasure.MeasureUnitCode)
unique(data$ActivityTopDepthHeightMeasure.MeasureUnitCode)
unique(data$ActivityBottomDepthHeightMeasure.MeasureUnitCode)

```


```{r backupvalues}

###creating new columns to preserve original pulled data

data$source_parameter<- data$CharacteristicName
data$source_value<- data$ResultMeasureValue
data$source_unit <- data$ResultMeasure.MeasureUnitCode
data$detectionlimit_legacy<- data$DetectionQuantitationLimitMeasure.MeasureValue
data$detectionlimit_unit_legacy<- data$DetectionQuantitationLimitMeasure.MeasureUnitCode

vars2process <- unique(data$CharacteristicName)#only once for first occurrence

write.csv(unique(data$CharacteristicName), file = "unique_characteristicnames.csv")

```


```{r depth}
#Depth
abbrev <- "depth"
lagos_name <- "Depth"
lagos_unit <- "m"
dataset_name <-"depth"

params<-c("Depth", "Depth, bottom", "Depth of water column", "Depth, data-logger (non-ported)", "Depth, data-logger (ported)")
vars2process<-vars2process[! vars2process %in% params] #remove grab samples from list
vars2process #check if any new varables to inlcude

data_temp<-data[data$CharacteristicName%in%params,] #want to match all records to the vector we created above 

###create dataset to check for non numeric objects in dataset
temp <- non_numerics()

source("unit_conversions.R")
#done
```


```{r secchi}
abbrev <- "secchi"
lagos_name <- "Secchi"
lagos_unit <- "m"
dataset_name <-"secchi"

params<-c("Depth, Secchi disk depth","Depth, Secchi disk depth (choice list)","Water transparency, Secchi disc", "Transparency, Secchi tube with disk", "Horizontal Secchi Disk") #values for secchi
vars2process<-vars2process[! vars2process %in% params] #remove grab samples from list
vars2process #che

data_temp<-data[data$CharacteristicName%in%params,] #want to match all records to the vector we created above 

###create dataset to check for non numeric objects in dataset
temp <- non_numerics()

{
#notes for processing non-numerics
#have to be able to assign a value and units to either result measure value and/or detection limit value to process
temp2 <- temp %>% 
  filter(grepl(">",ResultMeasureValue,fixed=TRUE)) %>% 
  filter(is.na(DetectionQuantitationLimitMeasure.MeasureValue))
#extract Values
vals <- gsub("[^0-9.-]", "", temp2$ResultMeasureValue)
data_temp$DetectionQuantitationLimitMeasure.MeasureValue[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- vals
data_temp$ResultDetectionConditionText[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- "Greater Than"
data_temp$ResultMeasureValue[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- NA

temp2 <- temp %>% 
  filter(ResultMeasureValue=="On Bottom") %>% 
  filter(is.na(DetectionQuantitationLimitMeasure.MeasureValue)) %>% 
  filter(!is.na(ActivityBottomDepthHeightMeasure.MeasureValue))
vals <- temp2$ActivityBottomDepthHeightMeasure.MeasureValue
data_temp$DetectionQuantitationLimitMeasure.MeasureValue[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- vals
data_temp$ResultDetectionConditionText[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- "Greater Than"
data_temp$ResultMeasureValue[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- NA

#check temp again to make sure everything is fixed that can be fixed
  }

source("unit_conversions.R")
```


```{r calcium}

abbrev <- "Calcium"
lagos_name <- "Calcium, dissolved"
lagos_unit <- "mg/l"
dataset_name <-"Calcium_dissolved"

vars2process
params<-c("Calcium")
vars2process<-vars2process[! vars2process %in% params] #remove grab samples from list
vars2process #check if any new varables to inlcude

data_temp<-data[data$CharacteristicName%in%params,] #want to match all records to the vector we created above 

unique(data_temp$ResultSampleFractionText)
data_temp <- data_temp %>% filter(ResultSampleFractionText=="Dissolved")
unique(data_temp$ResultSampleFractionText)

###create dataset to check for non numeric objects in dataset
temp <- non_numerics()


temp <- non_numerics()
temp2 <- temp %>% filter(grepl("<",temp$ResultMeasureValue,fixed=TRUE)==TRUE) %>%  
  filter(is.na(DetectionQuantitationLimitMeasure.MeasureValue)) #grab values with "<" from result measure value and NA in detection limit

vals <- gsub("[^0-9.-]", "", temp2$ResultMeasureValue) #extract only values from result measure value

data_temp$DetectionQuantitationLimitMeasure.MeasureValue[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- vals #place values in the detectionlim col

data_temp$ResultDetectionConditionText[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- "Less Than"

data_temp$ResultMeasureValue[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- NA

temp <- non_numerics()

source("unit_conversions.R")

```

```{r aluminum-total}
abbrev <- "tAl"
lagos_name <- "Aluminum, total"
lagos_unit <- "ug/l"
dataset_name <-"Aluminum_total"

vars2process
params<-c("Aluminum", "Aluminum, Organic + Inorganic Monomeric (reactive aluminum)")
vars2process<-vars2process[! vars2process %in% params] #remove grab samples from list
vars2process #check if any new varables to inlcude

data_temp<-data[data$CharacteristicName%in%params,] #want to match all records to the vector we created above 

unique(data_temp$ResultSampleFractionText)
data_temp <- data_temp %>% filter(ResultSampleFractionText=="Total")
unique(data_temp$ResultSampleFractionText)

###create dataset to check for non numeric objects in dataset
temp <- non_numerics()

temp2 <- temp %>% filter(grepl("<",temp$ResultMeasureValue,fixed=TRUE)==TRUE) %>%  
  filter(is.na(DetectionQuantitationLimitMeasure.MeasureValue)) #grab values with "<" from result measure value and NA in detection limit

vals <- gsub("[^0-9.-]", "", temp2$ResultMeasureValue) #extract only values from result measure value

data_temp$DetectionQuantitationLimitMeasure.MeasureValue[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- vals #place values in the detectionlim col

data_temp$ResultDetectionConditionText[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- "Less Than"

data_temp$ResultMeasureValue[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- NA

temp <- non_numerics()

source("unit_conversions.R")
```


```{r aluminum-dissolved}
abbrev <- "dAl"
lagos_name <- "Aluminum, dissolved"
lagos_unit <- "ug/l"
dataset_name <-"Aluminum_dissolved"

vars2process
params<-c("Aluminum", "Aluminum, Organic + Inorganic Monomeric (reactive aluminum)")
vars2process<-vars2process[! vars2process %in% params] #remove grab samples from list
vars2process #check if any new varables to inlcude

data_temp<-data[data$CharacteristicName%in%params,] #want to match all records to the vector we created above 

unique(data_temp$ResultSampleFractionText)
data_temp <- data_temp %>% filter(ResultSampleFractionText=="Dissolved")
unique(data_temp$ResultSampleFractionText)

###create dataset to check for non numeric objects in dataset
temp <- non_numerics()

temp2 <- temp %>% filter(grepl("<",temp$ResultMeasureValue,fixed=TRUE)==TRUE) %>%  
  filter(is.na(DetectionQuantitationLimitMeasure.MeasureValue)) #grab values with "<" from result measure value and NA in detection limit

vals <- gsub("[^0-9.-]", "", temp2$ResultMeasureValue) #extract only values from result measure value

data_temp$DetectionQuantitationLimitMeasure.MeasureValue[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- vals #place values in the detectionlim col

data_temp$ResultDetectionConditionText[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- "Less Than"

data_temp$ResultMeasureValue[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- NA

temp <- non_numerics()

source("unit_conversions.R")
```

```{r mercury-total}
abbrev <- "tMe"
lagos_name <- "Mercury, total"
lagos_unit <- "ng/l"
dataset_name <-"Mercury_total"

vars2process
params<-c("Mercury")
vars2process<-vars2process[! vars2process %in% params] #remove grab samples from list
vars2process #check if any new varables to inlcude

data_temp<-data[data$CharacteristicName%in%params,] #want to match all records to the vector we created above 

unique(data_temp$ResultSampleFractionText)
data_temp <- data_temp %>% filter(ResultSampleFractionText=="Total")
unique(data_temp$ResultSampleFractionText)

###create dataset to check for non numeric objects in dataset
temp <- non_numerics()

temp2 <- temp %>% filter(grepl("ng/L",temp$ResultMeasureValue,fixed=TRUE)==TRUE) 

vals <- gsub("[^0-9.-]", "", temp2$ResultMeasureValue) #extract only values from result measure value

data_temp$ResultMeasureValue[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- vals

temp <- non_numerics()

data_temp<-data_temp %>% filter(Obs_Id != "ID-163183" )

source("unit_conversions.R")
```

```{r mercury-dissolved}

abbrev <- "dMe"
lagos_name <- "Mercury, total dissolved"
lagos_unit <- "ng/l"
dataset_name <-"Mercury_dissolved"

vars2process
params<-c("Mercury")
vars2process<-vars2process[! vars2process %in% params] #remove grab samples from list
vars2process #check if any new varables to inlcude

data_temp<-data[data$CharacteristicName%in%params,] #want to match all records to the vector we created above 

unique(data_temp$ResultSampleFractionText)
data_temp <- data_temp %>% filter(ResultSampleFractionText=="Dissolved")
unique(data_temp$ResultSampleFractionText)

###create dataset to check for non numeric objects in dataset
temp <- non_numerics()

source("unit_conversions.R")

```

```{r methylmercury-total}
#commented out because sample fraction does not have a total - only has suspended and dissolved

# abbrev <- "mMe"
# lagos_name <- "Methylmercury"
# lagos_unit <- "ng/l"
# dataset_name <-"Methylmercury"
# 
# vars2process
# params<-c("Methylmercury(1+)")
# vars2process<-vars2process[! vars2process %in% params] #remove grab samples from list
# vars2process #check if any new varables to inlcude
# 
# data_temp<-data[data$CharacteristicName%in%params,] #want to match all records to the vector we created above 
# 
# unique(data_temp$ResultSampleFractionText)
# data_temp <- data_temp %>% filter(ResultSampleFractionText=="Total")
# unique(data_temp$ResultSampleFractionText)
# 
# ###create dataset to check for non numeric objects in dataset
# temp <- non_numerics()
# #has no data so far
# source("unit_conversions.R")
```

```{r methylmercury-dissolved}

abbrev <- "dmMe"
lagos_name <- "Methylmercury, dissolved"
lagos_unit <- "ng/l"
dataset_name <-"Methylmercury_dissolved"

vars2process
params<-c("Methylmercury(1+)")
vars2process<-vars2process[! vars2process %in% params] #remove grab samples from list
vars2process #check if any new varables to inlcude

data_temp<-data[data$CharacteristicName%in%params,] #want to match all records to the vector we created above 

unique(data_temp$ResultSampleFractionText)
data_temp <- data_temp %>% filter(ResultSampleFractionText=="Dissolved")
unique(data_temp$ResultSampleFractionText)

###create dataset to check for non numeric objects in dataset
temp <- non_numerics()

source("unit_conversions.R")
```

```{r Magnesium}
abbrev <- "Magnesium"
lagos_name <- "Magnesium, dissolved"
lagos_unit <- "mg/l"
dataset_name <-"Magnesium_dissolved"

vars2process
params<-c("Magnesium")
vars2process<-vars2process[! vars2process %in% params] #remove grab samples from list
vars2process #check if any new varables to inlcude

data_temp<-data[data$CharacteristicName%in%params,] #want to match all records to the vector we created above 

unique(data_temp$ResultSampleFractionText)
data_temp <- data_temp %>% filter(ResultSampleFractionText=="Dissolved")
unique(data_temp$ResultSampleFractionText)

###create dataset to check for non numeric objects in dataset
temp <- non_numerics()


temp2 <- temp %>% filter(grepl("<",temp$ResultMeasureValue,fixed=TRUE)==TRUE) %>%  
  filter(is.na(DetectionQuantitationLimitMeasure.MeasureValue)) #grab values with "<" from result measure value and NA in detection limit

vals <- gsub("[^0-9.-]", "", temp2$ResultMeasureValue) #extract only values from result measure value

data_temp$DetectionQuantitationLimitMeasure.MeasureValue[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- vals #place values in the detectionlim col

data_temp$ResultDetectionConditionText[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- "Less Than"

data_temp$ResultMeasureValue[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- NA

temp <- non_numerics()

source("unit_conversions.R")
```

```{r selenium-total}
abbrev <- "tSe"
lagos_name <- "Selenium, total"
lagos_unit <- "ug/l"
dataset_name <-"Selenium_total"

vars2process
params<-c("Selenium")
vars2process<-vars2process[! vars2process %in% params] #remove grab samples from list
vars2process #check if any new varables to inlcude

data_temp<-data[data$CharacteristicName%in%params,] #want to match all records to the vector we created above 

unique(data_temp$ResultSampleFractionText)
data_temp <- data_temp %>% filter(ResultSampleFractionText=="Total")
unique(data_temp$ResultSampleFractionText)

###create dataset to check for non numeric objects in dataset
temp <- non_numerics()

#No non_numerics that needed to be fixed
# temp2 <- temp %>% filter(grepl("<",temp$ResultMeasureValue,fixed=TRUE)==TRUE) %>%  
#   filter(is.na(DetectionQuantitationLimitMeasure.MeasureValue)) #grab values with "<" from result measure value and NA in detection limit
# 
# vals <- gsub("[^0-9.-]", "", temp2$ResultMeasureValue) #extract only values from result measure value
# 
# data_temp$DetectionQuantitationLimitMeasure.MeasureValue[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- vals #place values in the detectionlim col
# 
# data_temp$ResultDetectionConditionText[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- "Less Than"
# 
# data_temp$ResultMeasureValue[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- NA

source("unit_conversions.R")


```

```{r selenium-dissolved}
abbrev <- "dSe"
lagos_name <- "Selenium, dissolved"
lagos_unit <- "ug/l"
dataset_name <-"selenium_dissolved"

vars2process
params<-c("Selenium")
vars2process<-vars2process[! vars2process %in% params] #remove grab samples from list
vars2process #check if any new varables to inlcude

data_temp<-data[data$CharacteristicName%in%params,] #want to match all records to the vector we created above 
unique(data_temp$ResultSampleFractionText)
data_temp <- data_temp %>% filter(ResultSampleFractionText=="Dissolved")
unique(data_temp$ResultSampleFractionText)

###create dataset to check for non numeric objects in dataset
temp <- non_numerics()

temp2 <- temp %>% filter(grepl("<",temp$ResultMeasureValue,fixed=TRUE)==TRUE) %>%  
  filter(is.na(DetectionQuantitationLimitMeasure.MeasureValue)) #grab values with "<" from result measure value and NA in detection limit

vals <- gsub("[^0-9.-]", "", temp2$ResultMeasureValue) #extract only values from result measure value

data_temp$DetectionQuantitationLimitMeasure.MeasureValue[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- vals #place values in the detectionlim col

data_temp$ResultDetectionConditionText[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- "Less Than"

data_temp$ResultMeasureValue[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- NA

temp <- non_numerics()

source("unit_conversions.R")
```

```{r arsenic-total}
abbrev <- "tArsenic"
lagos_name <- "Arsenic, total"
lagos_unit <- "ug/l"
dataset_name <-"Arsenic_total"

vars2process
params<-c("Arsenic", "Arsenate", "Arsenite")
vars2process<-vars2process[! vars2process %in% params] #remove grab samples from list
vars2process #check if any new varables to inlcude

data_temp<-data[data$CharacteristicName%in%params,] #want to match all records to the vector we created above 

unique(data_temp$ResultSampleFractionText)
data_temp <- data_temp %>% filter(ResultSampleFractionText=="Total")
unique(data_temp$ResultSampleFractionText)

###create dataset to check for non numeric objects in dataset
temp <- non_numerics()

temp2 <- temp %>% filter(grepl("<",temp$ResultMeasureValue,fixed=TRUE)==TRUE) %>%  
  filter(is.na(DetectionQuantitationLimitMeasure.MeasureValue)) #grab values with "<" from result measure value and NA in detection limit

vals <- gsub("[^0-9.-]", "", temp2$ResultMeasureValue) #extract only values from result measure value

data_temp$DetectionQuantitationLimitMeasure.MeasureValue[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- vals #place values in the detectionlim col

data_temp$ResultDetectionConditionText[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- "Less Than"

data_temp$ResultMeasureValue[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- NA

temp <- non_numerics()

source("unit_conversions.R")
data_temp_temp_notes
rm(data_temp_temp_notes)



```

```{r arsenic-dissolved}
abbrev <- "dArsenic"
lagos_name <- "Arsenic, dissolved"
lagos_unit <- "ug/l"
dataset_name <-"Arsenic_dissolved"

vars2process
params<-c("Arsenic", "Arsenate", "Arsenite")
vars2process<-vars2process[! vars2process %in% params] #remove grab samples from list
vars2process #check if any new varables to inlcude

data_temp<-data[data$CharacteristicName%in%params,] #want to match all records to the vector we created above 

unique(data_temp$ResultSampleFractionText)
data_temp <- data_temp %>% filter(ResultSampleFractionText=="Dissolved")
unique(data_temp$ResultSampleFractionText)

###create dataset to check for non numeric objects in dataset
temp <- non_numerics()

temp2 <- temp %>% filter(grepl("<",temp$ResultMeasureValue,fixed=TRUE)==TRUE) %>%  
  filter(is.na(DetectionQuantitationLimitMeasure.MeasureValue)) #grab values with "<" from result measure value and NA in detection limit

vals <- gsub("[^0-9.-]", "", temp2$ResultMeasureValue) #extract only values from result measure value

data_temp$DetectionQuantitationLimitMeasure.MeasureValue[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- vals #place values in the detectionlim col

data_temp$ResultDetectionConditionText[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- "Less Than"

data_temp$ResultMeasureValue[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- NA

temp <- non_numerics()

source("unit_conversions.R")
```

```{r atrazine-dissolved}

abbrev <- "Atrazine"
lagos_name <- "Atrazine, dissolved"
lagos_unit <- "ug/l"
dataset_name <-"Atrazine_dissolved"

vars2process
params<-c("Atrazine")
vars2process<-vars2process[! vars2process %in% params] #remove grab samples from list
vars2process #check if any new varables to inlcude

data_temp<-data[data$CharacteristicName%in%params,] #want to match all records to the vector we created above 
unique(data_temp$ResultSampleFractionText)
data_temp <- data_temp %>% filter(ResultSampleFractionText=="Dissolved")
unique(data_temp$ResultSampleFractionText)

###create dataset to check for non numeric objects in dataset
temp <- non_numerics()

#0 non numerics

source("unit_conversions.R")

```

```{r ecoli #/100ml}

abbrev <- "Ecoli"
lagos_name <- "E. coli"
lagos_unit <- "#/100ml"
dataset_name <-"E_coli_100ml"

vars2process
params<-c("Escherichia coli", "Escherichia")
vars2process<-vars2process[! vars2process %in% params] #remove grab samples from list
vars2process #check if any new varables to inlcude

data_temp<-data[data$CharacteristicName%in%params,] #want to match all records to the vector we created above 
unique(data_temp$ResultSampleFractionText)

unique(data_temp$ResultMeasure.MeasureUnitCode)

###create dataset to check for non numeric objects in dataset
temp <- non_numerics()

temp2 <- temp %>% filter(grepl("<",temp$ResultMeasureValue,fixed=TRUE)==TRUE) %>%  
  filter(is.na(DetectionQuantitationLimitMeasure.MeasureValue)) #grab values with "<" from result measure value and NA in detection limit

vals <- gsub("[^0-9.-]", "", temp2$ResultMeasureValue) #extract only values from result measure value

data_temp$DetectionQuantitationLimitMeasure.MeasureValue[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- vals #place values in the detectionlim col

data_temp$ResultDetectionConditionText[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- "Less Than"

data_temp$ResultMeasureValue[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- NA

temp <- non_numerics()

source("unit_conversions.R")

```

```{r ecoli MPN}

abbrev <- "Ecoli_MPN"
lagos_name <- "E. coli-MPN"
lagos_unit <- "MPN"
dataset_name <-"E_coli_MPN"

vars2process
params<-c("Escherichia coli", "Escherichia")
vars2process<-vars2process[! vars2process %in% params] #remove grab samples from list
vars2process #check if any new varables to inlcude

data_temp<-data[data$CharacteristicName%in%params,] #want to match all records to the vector we created above 
unique(data_temp$ResultSampleFractionText)

unique(data_temp$ResultMeasure.MeasureUnitCode)

###create dataset to check for non numeric objects in dataset
temp <- non_numerics()

source("unit_conversions.R")

```

```{r ecoli CFU}

abbrev <- "Ecoli_CFU"
lagos_name <- "E. coli-CFU"
lagos_unit <- "CFU"
dataset_name <-"E_coli_CFU"

vars2process
params<-c("Escherichia coli","Escherichia")
vars2process<-vars2process[! vars2process %in% params] #remove grab samples from list
vars2process #check if any new varables to inlcude

data_temp<-data[data$CharacteristicName%in%params,] #want to match all records to the vector we created above 
unique(data_temp$ResultSampleFractionText)

unique(data_temp$ResultMeasure.MeasureUnitCode)

###create dataset to check for non numeric objects in dataset
temp <- non_numerics()

source("unit_conversions.R")

```

```{r chloride}
abbrev <- "Chloride"
lagos_name <- "Chloride, dissolved"
lagos_unit <- "mg/l"
dataset_name <-"Chloride_dissolved"

vars2process
params<-c("Chloride", "Chlorine")
vars2process<-vars2process[! vars2process %in% params] #remove grab samples from list
vars2process #check if any new varables to inlcude

data_temp<-data[data$CharacteristicName%in%params,] #want to match all records to the vector we created above 
unique(data_temp$ResultSampleFractionText)

data_temp <- data_temp %>% filter(ResultSampleFractionText=="Dissolved")
unique(data_temp$ResultSampleFractionText)

###create dataset to check for non numeric objects in dataset
temp <- non_numerics()

temp2 <- temp %>% filter(grepl("*",temp$ResultMeasureValue,fixed=TRUE)==TRUE)  
vals <- gsub("[^0-9.-]", "", temp2$ResultMeasureValue)
data_temp$ResultMeasureValue[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- vals

temp <- non_numerics()
temp2 <- temp %>% filter(grepl("<",temp$ResultMeasureValue,fixed=TRUE)==TRUE) %>%  
  filter(is.na(DetectionQuantitationLimitMeasure.MeasureValue))
vals <- gsub("[^0-9.-]", "", temp2$ResultMeasureValue)
data_temp$DetectionQuantitationLimitMeasure.MeasureValue[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- vals
data_temp$ResultDetectionConditionText[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- "Less Than"
data_temp$ResultMeasureValue[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- NA
temp <- non_numerics()

source("unit_conversions.R")
```

```{r oxygen}
abbrev <- "DO"
lagos_name <- "Oxygen, dissolved"
lagos_unit <- "mg/l"
dataset_name <-"Oxygen_dissolved"

vars2process
params<-c("Dissolved oxygen (DO)", "Oxygen")
vars2process<-vars2process[! vars2process %in% params] #remove grab samples from list
vars2process #check if any new varables to inlcude

data_temp<-data[data$CharacteristicName%in%params,] #want to match all records to the vector we created above 
#no need to filter DO based on fraction
unique(data_temp$ResultSampleFractionText)

###create dataset to check for non numeric objects in dataset
temp <- non_numerics()
data_temp$ResultDetectionConditionText[which(data_temp$Obs_Id %in% temp$Obs_Id)] <- "Less Than"

source("unit_conversions.R")
data_temp_temp_notes
rm(data_temp_temp_notes)

```

```{r chlorophyll}

abbrev <- "Chla"
lagos_name <- "Chlorophyll a"
lagos_unit <- "ug/l"
dataset_name <-"Chlorophyll_a"

vars2process
params<-c("Chlorophyll a, corrected for pheophytin", "Chlorophyll a", "Chlorophyll a, uncorrected for pheophytin", "Chlorophyll", "Chlorophyll a - Phytoplankton (suspended)", "Chlorophyll a, free of pheophytin")
vars2process<-vars2process[! vars2process %in% params] #remove grab samples from list
vars2process #check if any new varables to inlcude

data_temp<-data[data$CharacteristicName%in%params,] #want to match all records to the vector we created above 
#no need to filter DO based on fraction
unique(data_temp$ResultSampleFractionText)

###create dataset to check for non numeric objects in dataset
temp <- non_numerics()

temp2 <- temp %>% 
  filter(grepl("<",ResultMeasureValue,fixed=TRUE)) %>% 
  filter(is.na(DetectionQuantitationLimitMeasure.MeasureValue))
#extract Values
vals <- gsub("[^0-9.-]", "", temp2$ResultMeasureValue)
data_temp$DetectionQuantitationLimitMeasure.MeasureValue[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- vals
data_temp$ResultDetectionConditionText[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- "Less Than"
data_temp$ResultMeasureValue[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- vals

temp <- non_numerics()
unique(temp$ResultMeasureValue)

temp2 <- temp %>% 
  filter(grepl("<",ResultMeasureValue,fixed=TRUE))  
vals <- gsub("[^0-9.-]", "", temp2$ResultMeasureValue)
data_temp$ResultDetectionConditionText[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- "Less Than"
data_temp$ResultMeasureValue[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- vals

temp <- non_numerics()


source("unit_conversions.R")
data_temp_temp_notes
rm(data_temp_temp_notes)

```

```{r pH}

abbrev <- "pH"
lagos_name <- "pH, field or lab"
lagos_unit <- "pH"
dataset_name <-"pH"

vars2process
params<-c("pH", "pH, lab")
vars2process<-vars2process[! vars2process %in% params] #remove grab samples from list
vars2process #check if any new varables to inlcude

data_temp<-data[data$CharacteristicName%in%params,] #want to match all records to the vector we created above 

###create dataset to check for non numeric objects in dataset
temp <- non_numerics()
#can do direct conversion for pH 

source("unit_conversions.R")
```

```{r temperature}
abbrev <- "wtemp"
lagos_name <- "Temperature"
lagos_unit <- "deg C"
dataset_name <-"wtemp"

params<-c("Temperature, water", "Temperature, water, deg F")
vars2process<-vars2process[! vars2process %in% params] #remove grab samples from list
vars2process #che

data_temp<-data[data$CharacteristicName%in%params,] #want to match all records to the vector we created above 

###create dataset to check for non numeric objects in dataset
temp<-non_numerics()

unique(data_temp$ResultMeasure.MeasureUnitCode)
unique(data_temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)

data_temp$ResultMeasureValue <- as.numeric(data_temp$ResultMeasureValue)

#convert result measure value
data_temp$ResultMeasureValue[which(data_temp$ResultMeasure.MeasureUnitCode=="deg F")] <- 
  (data_temp$ResultMeasureValue[which(data_temp$ResultMeasure.MeasureUnitCode=="deg F")]-32)*(5/9)
data_temp$ResultMeasure.MeasureUnitCode[which(data_temp$ResultMeasure.MeasureUnitCode=="deg F")] <- "deg C"

#convert detection limit
```

```{r sulfate}
#sulfate is reported as SO4
abbrev <- "so4"
lagos_name <- "Sulfate, dissolved"
lagos_unit <- "mg/l"
dataset_name <-"so4"

vars2process
params<-c("Sulfate as S","Sulfate", "Sulfur Sulfate", "Sulfur", "Sulfur-34", "Sulfite")
vars2process<-vars2process[! vars2process %in% params] #remove grab samples from list
vars2process #che

data_temp<-data[data$CharacteristicName%in%params,] #want to match all records to the vector we created above 
unique(data_temp$ResultSampleFractionText)
data_temp <- data_temp %>% filter(ResultSampleFractionText=="Dissolved")
unique(data_temp$ResultSampleFractionText)

###create dataset to check for non numeric objects in dataset
temp<-non_numerics()

temp2 <- temp %>% filter(grepl("<",temp$ResultMeasureValue,fixed=TRUE)==TRUE) %>%  
  filter(is.na(DetectionQuantitationLimitMeasure.MeasureValue)) #grab values with "<" from result measure value and NA in detection limit

vals <- gsub("[^0-9.-]", "", temp2$ResultMeasureValue) #extract only values from result measure value

data_temp$DetectionQuantitationLimitMeasure.MeasureValue[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- vals #place values in the detectionlim col

data_temp$ResultDetectionConditionText[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- "Less Than"

data_temp$ResultMeasureValue[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- NA

temp <- non_numerics()

source("unit_conversions.R")
data_temp_temp_notes
rm(data_temp_temp_notes)
```

```{r turbidity}
abbrev <- "Turbidity"
lagos_name <- "Turbidity"
lagos_unit <- "NTU"
dataset_name <-"Turbidity"

vars2process
params<-c("Turbidity", "Turbidity Field")
vars2process<-vars2process[! vars2process %in% params] #remove grab samples from list
vars2process #check if any new varables to inlcude

data_temp<-data[data$CharacteristicName%in%params,] #want to match all records to the vector we created above 

###create dataset to check for non numeric objects in dataset
temp <- non_numerics()

temp2 <- temp %>% filter(grepl("<",temp$ResultMeasureValue,fixed=TRUE)==TRUE) %>%  
  filter(is.na(DetectionQuantitationLimitMeasure.MeasureValue)) #grab values with "<" from result measure value and NA in detection limit

vals <- gsub("[^0-9.-]", "", temp2$ResultMeasureValue) #extract only values from result measure value

data_temp$DetectionQuantitationLimitMeasure.MeasureValue[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- vals #place values in the detectionlim col

data_temp$ResultDetectionConditionText[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- "Less Than"

data_temp$ResultMeasureValue[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- NA

temp <- non_numerics()

source("unit_conversions.R")
```

```{r conductivity}
abbrev <- "Conductivity"
lagos_name <- "Conductivity"
lagos_unit <- "uS/cm"
dataset_name <-"Conductivity"

vars2process
params<-c("Conductivity", "Specific conductance")
vars2process<-vars2process[! vars2process %in% params] #remove grab samples from list
vars2process #check if any new varables to inlcude

data_temp<-data[data$CharacteristicName%in%params,] #want to match all records to the vector we created above 

###create dataset to check for non numeric objects in dataset
temp <- non_numerics()

temp2 <- temp %>% filter(grepl("<",temp$ResultMeasureValue,fixed=TRUE)==TRUE) %>%  
  filter(is.na(DetectionQuantitationLimitMeasure.MeasureValue)) #grab values with "<" from result measure value and NA in detection limit

vals <- gsub("[^0-9.-]", "", temp2$ResultMeasureValue) #extract only values from result measure value

data_temp$DetectionQuantitationLimitMeasure.MeasureValue[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- vals #place values in the detectionlim col

data_temp$ResultDetectionConditionText[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- "Less Than"

data_temp$ResultMeasureValue[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- NA

temp <- non_numerics()


source("unit_conversions.R")

```

```{r total-carbon}
abbrev <- "tCarbon"
lagos_name <- "Carbon, total organic"
lagos_unit <- "mg/l"
dataset_name <-"TOC"

vars2process
params<-c("Carbon", "Organic carbon", "Total carbon")
vars2process<-vars2process[! vars2process %in% params] #remove grab samples from list
vars2process #check if any new varables to inlcude

data_temp<-data[data$CharacteristicName%in%params,] #want to match all records to the vector we created above 
unique(data_temp$ResultSampleFractionText)

data_temp <- data_temp %>% filter(ResultSampleFractionText=="Total")
unique(data_temp$ResultSampleFractionText)

###create dataset to check for non numeric objects in dataset
temp <- non_numerics()

temp2 <- temp %>% filter(grepl("<",temp$ResultMeasureValue,fixed=TRUE)==TRUE) %>%  
  filter(is.na(DetectionQuantitationLimitMeasure.MeasureValue)) #grab values with "<" from result measure value and NA in detection limit

vals <- gsub("[^0-9.-]", "", temp2$ResultMeasureValue) #extract only values from result measure value

data_temp$DetectionQuantitationLimitMeasure.MeasureValue[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- vals #place values in the detectionlim col

data_temp$ResultDetectionConditionText[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- "Less Than"

data_temp$ResultMeasureValue[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- NA

temp <- non_numerics()


source("unit_conversions.R")
```


```{r total-dissolved-carbon}
abbrev <- "tdCarbon"
lagos_name <- "Carbon, dissolved organic"
lagos_unit <- "mg/l"
dataset_name <-"TOC"

vars2process
params<-c("Carbon", "Organic carbon", "Total carbon")
vars2process<-vars2process[! vars2process %in% params] #remove grab samples from list
vars2process #check if any new varables to inlcude

data_temp<-data[data$CharacteristicName%in%params,] #want to match all records to the vector we created above 
unique(data_temp$ResultSampleFractionText)

data_temp <- data_temp %>% filter(ResultSampleFractionText=="Dissolved")
unique(data_temp$ResultSampleFractionText)

###create dataset to check for non numeric objects in dataset
temp <- non_numerics()

temp2 <- temp %>% filter(grepl("<",temp$ResultMeasureValue,fixed=TRUE)==TRUE) %>%  
  filter(is.na(DetectionQuantitationLimitMeasure.MeasureValue)) #grab values with "<" from result measure value and NA in detection limit

vals <- gsub("[^0-9.-]", "", temp2$ResultMeasureValue) #extract only values from result measure value

data_temp$DetectionQuantitationLimitMeasure.MeasureValue[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- vals #place values in the detectionlim col

data_temp$ResultDetectionConditionText[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- "Less Than"

data_temp$ResultMeasureValue[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- NA

temp <- non_numerics()

source("unit_conversions.R")
```

```{r alkalinity}

abbrev <- "Alkalinity"
lagos_name <- "Alkalinity"
lagos_unit <- "ueq/l"
dataset_name <-"Alkalinity"

vars2process
params<-c("Alkalinity, total", "Alkalinity, Carbonate as CaCO3", "Alkalinity", "Alkalinity, carbonate", "Alkalinity, Bicarbonate as CaCO3", "Alkalinity, bicarbonate", "Alkalinity, Hydroxide as CaCO3")
vars2process<-vars2process[! vars2process %in% params] #remove grab samples from list
vars2process #check if any new varables to inlcude

data_temp<-data[data$CharacteristicName%in%params,] #want to match all records to the vector we created above 
unique(data_temp$ResultSampleFractionText)

###create dataset to check for non numeric objects in dataset
temp <- non_numerics()

#all existing non numerics can be converted to NAs (43)

source("unit_conversions.R")


```

```{r TSS}
abbrev <- "tss"
lagos_name <- "Solids, total suspended"
lagos_unit <- "mg/l"
dataset_name <-"Solids_total_suspended"

vars2process
params<-c("Total suspended solids", "Total dissolved solids", "Total solids")
vars2process<-vars2process[! vars2process %in% params] #remove grab samples from list
vars2process #check if any new varables to inlcude

data_temp<-data[data$CharacteristicName%in%params,] #want to match all records to the vector we created above 
unique(data_temp$ResultSampleFractionText)

data_temp <- data_temp %>% filter(ResultSampleFractionText=="Total" | ResultSampleFractionText == "Suspended")
unique(data_temp$ResultSampleFractionText)

###create dataset to check for non numeric objects in dataset
temp <- non_numerics()


temp2 <- temp %>% filter(grepl("<",temp$ResultMeasureValue,fixed=TRUE)==TRUE) %>%  
  filter(is.na(DetectionQuantitationLimitMeasure.MeasureValue)) #grab values with "<" from result measure value and NA in detection limit

vals <- gsub("[^0-9.-]", "", temp2$ResultMeasureValue) #extract only values from result measure value

data_temp$DetectionQuantitationLimitMeasure.MeasureValue[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- vals #place values in the detectionlim col

data_temp$ResultDetectionConditionText[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- "Less Than"

data_temp$ResultMeasureValue[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- NA

temp <- non_numerics()

source("unit_conversions.R")
data_temp_temp_notes
rm(data_temp_temp_notes)

```

```{r Salinity}
abbrev <- "Salinity"
lagos_name <- "Salinity"
lagos_unit <- "ppt"
dataset_name <-"Salinity"

vars2process
params<-c("Salinity")
vars2process<-vars2process[! vars2process %in% params] #remove grab samples from list
vars2process #check if any new varables to inlcude

data_temp<-data[data$CharacteristicName%in%params,] #want to match all records to the vector we created above 

###create dataset to check for non numeric objects in dataset
temp <- non_numerics()

#all non detects can be converted to NAs

source("unit_conversions.R")
```

```{r color-true}
abbrev <- "TColor"
lagos_name <- "Color, true"
lagos_unit <- "PCU"
dataset_name <-"Color_true"

vars2process
params<-c("True color", "Color")
vars2process<-vars2process[! vars2process %in% params] #remove grab samples from list
vars2process #check if any new varables to inlcude

data_temp<-data[data$CharacteristicName%in%params,] #want to match all records to the vector we created above 

###create dataset to check for non numeric objects in dataset
temp <- non_numerics()

temp2 <- temp %>% filter(grepl("<",temp$ResultMeasureValue,fixed=TRUE)==TRUE) %>%  
  filter(is.na(DetectionQuantitationLimitMeasure.MeasureValue)) #grab values with "<" from result measure value and NA in detection limit

vals <- gsub("[^0-9.-]", "", temp2$ResultMeasureValue) #extract only values from result measure value

data_temp$DetectionQuantitationLimitMeasure.MeasureValue[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- vals #place values in the detectionlim col

data_temp$ResultDetectionConditionText[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- "Less Than"

data_temp$ResultMeasureValue[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- NA

temp <- non_numerics()

source("unit_conversions.R")
```

```{r color-apparent}
abbrev <- "ApparColor"
lagos_name <- "Color, apparent"
lagos_unit <- "PCU"
dataset_name <-"Color_apparent"

vars2process
params<-c("Apparent color")
vars2process<-vars2process[! vars2process %in% params] #remove grab samples from list
vars2process #check if any new varables to inlcude

data_temp<-data[data$CharacteristicName%in%params,] #want to match all records to the vector we created above 

###create dataset to check for non numeric objects in dataset
temp <- non_numerics()


#can let all non numerics turn to NAs

source("unit_conversions.R")
```

```{r dissolved-inorganic-phosphorus}
abbrev <- "dip"
lagos_name <- "Phosphorus, soluble reactive orthophosphate"
lagos_unit <- "ug/l"
dataset_name <-"dip"

vars2process
params<-c("Orthophosphate", 
          "Orthophosphate as P", 
          "Phosphate-phosphorus",
          "Phosphate-phosphorus as P",
          "Phosphorus", 
          "Orthophosphate as PO4", 
          "Phosphate-phosphorus as PO4", 
          "Inorganic phosphorus", 
          "Soluble Reactive Phosphorus (SRP)")
vars2process<-vars2process[! vars2process %in% params] #remove grab samples from list
vars2process #che

data_temp<-data[data$CharacteristicName%in%params,] #want to match all records to the vector we created above 
unique(data_temp$ResultSampleFractionText)
data_temp <- data_temp %>% filter(ResultSampleFractionText=="Dissolved" | ResultSampleFractionText=="Filterable" | ResultSampleFractionText=="Inorganic")
unique(data_temp$ResultSampleFractionText)

###create dataset to check for non numeric objects in dataset
temp<-non_numerics()
temp2 <- temp %>% filter(grepl("<",temp$ResultMeasureValue,fixed=TRUE)==TRUE) %>%  
  filter(is.na(DetectionQuantitationLimitMeasure.MeasureValue)) #grab values with "<" from result measure value and NA in detection limit

vals <- gsub("[^0-9.-]", "", temp2$ResultMeasureValue) #extract only values from result measure value

data_temp$DetectionQuantitationLimitMeasure.MeasureValue[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- vals #place values in the detectionlim col

data_temp$ResultDetectionConditionText[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- "Less Than"

data_temp$ResultMeasureValue[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- NA

temp <- non_numerics()

source("unit_conversions.R")
```

```{r phosphorus-total}
abbrev <- "tp"
lagos_name <- "Phosphorus, total"
lagos_unit <- "ug/l"
dataset_name <-"tp"

vars2process
params<-c("Phosphorus",
          "Phosphate-phosphorus",
          "Total Phosphorus, mixed forms",
          "Phosphorus as P", 
          "Inorganic phosphorus")
vars2process<-vars2process[! vars2process %in% params] #remove grab samples from list
vars2process #che

data_temp<-data[data$CharacteristicName%in%params,] #want to match all records to the vector we created above 
unique(data_temp$ResultSampleFractionText)
data_temp <- data_temp %>% filter(ResultSampleFractionText=="Total")
unique(data_temp$ResultSampleFractionText)

###create dataset to check for non numeric objects in dataset
temp<-non_numerics()
temp2 <- temp %>% filter(grepl("<",temp$ResultMeasureValue,fixed=TRUE)==TRUE) %>%  
  filter(is.na(DetectionQuantitationLimitMeasure.MeasureValue)) #grab values with "<" from result measure value and NA in detection limit

vals <- gsub("[^0-9.-]", "", temp2$ResultMeasureValue) #extract only values from result measure value

data_temp$DetectionQuantitationLimitMeasure.MeasureValue[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- vals #place values in the detectionlim col

data_temp$ResultDetectionConditionText[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- "Less Than"

data_temp$ResultMeasureValue[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- NA

temp <- non_numerics()

source("unit_conversions.R")
```

```{r phosphorus-total-dissolved}
abbrev <- "tp"
lagos_name <- "Phosphorus, total dissolved"
lagos_unit <- "ug/l"
dataset_name <-"tdp"

params<-c("Phosphorus",
          "Phosphate-phosphorus",
          "Total Phosphorus, mixed forms",
          "Phosphorus as P")

data_temp<-data[data$CharacteristicName%in%params,] #want to match all records to the vector we created above 
unique(data_temp$ResultSampleFractionText)
data_temp <- data_temp %>% filter(ResultSampleFractionText=="Dissolved" | ResultSampleFractionText=="Filterable")
unique(data_temp$ResultSampleFractionText)

###create dataset to check for non numeric objects in dataset
temp<-non_numerics()
 #all non numerics can be coverted to NAs - nothing to save
source("unit_conversions.R")
```

```{r TKN-kjeldahl-total }
abbrev <- "kn"
lagos_name <- "Nitrogen, total Kjeldahl"
lagos_unit <- "ug/l"
dataset_name <-"tkn"

vars2process
params<-c("Total Kjeldahl nitrogen",
          "Kjeldahl nitrogen",
          "Total Kjeldahl nitrogen (Organic N & NH3)")
vars2process<-vars2process[! vars2process %in% params] #remove grab samples from list
vars2process #che

data_temp<-data[data$CharacteristicName%in%params,] #want to match all records to the vector we created above 
unique(data_temp$ResultSampleFractionText)
data_temp <- data_temp %>% filter(ResultSampleFractionText=="Total")
unique(data_temp$ResultSampleFractionText)

###create dataset to check for non numeric objects in dataset
temp<-non_numerics()
unique(temp$ResultMeasureValue)
vals <- gsub("[^0-9.-]", "", temp$ResultMeasureValue)
data_temp$ResultDetectionConditionText[which(data_temp$Obs_Id %in% temp$Obs_Id)] <- "Less Than"
data_temp$ResultMeasureValue[which(data_temp$Obs_Id %in% temp$Obs_Id)] <- vals

source("unit_conversions.R")
data_temp_temp_notes
rm(data_temp_temp_notes)
```

```{r TDKN-kjeldahl-dissolved}
abbrev <- "kn"
lagos_name <- "Nitrogen, dissolved Kjeldahl"
lagos_unit <- "ug/l"
dataset_name <-"dkn"

params<-c("Total Kjeldahl nitrogen",
          "Kjeldahl nitrogen")
vars2process<-vars2process[! vars2process %in% params] #remove grab samples from list
vars2process #che

data_temp<-data[data$CharacteristicName%in%params,] #want to match all records to the vector we created above 
unique(data_temp$ResultSampleFractionText)
data_temp <- data_temp %>% filter(ResultSampleFractionText=="Dissolved")
unique(data_temp$ResultSampleFractionText)

###create dataset to check for non numeric objects in dataset
temp<-non_numerics()
#all ND's can be converted to NAS

source("unit_conversions.R")
data_temp_temp_notes
rm(data_temp_temp_notes)
```


```{r nitrogen-total}
abbrev <- "tn"
lagos_name <- "Nitrogen, total"
lagos_unit <- "ug/l"
dataset_name <-"tn"

vars2process
params<-c("Total Nitrogen, mixed forms (NH3), (NH4), organic, (NO2) and (NO3)",
          "Nutrient-nitrogen",
          "Nitrogen, mixed forms (NH3), (NH4), organic, (NO2) and (NO3)",
          "Total Nitrogen, mixed forms",
          "Nitrogen")
vars2process<-vars2process[! vars2process %in% params] #remove grab samples from list
vars2process #che

data_temp<-data[data$CharacteristicName%in%params,] #want to match all records to the vector we created above 
unique(data_temp$ResultSampleFractionText)
data_temp <- data_temp %>% filter(ResultSampleFractionText=="Total")
unique(data_temp$ResultSampleFractionText)

###create dataset to check for non numeric objects in dataset
temp<-non_numerics()

unique(temp$ResultMeasureValue)
temp2 <- temp %>% filter(grepl("<",temp$ResultMeasureValue,fixed=TRUE)==TRUE) %>% 
  filter(is.na(DetectionQuantitationLimitMeasure.MeasureValue))
vals <- gsub("[^0-9.-]", "", temp2$ResultMeasureValue)
data_temp$DetectionQuantitationLimitMeasure.MeasureValue[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- vals
data_temp$ResultDetectionConditionText[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- "Less Than"
data_temp$ResultMeasureValue[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- NA

source("unit_conversions.R")
```

```{r total-dissolved-nitrogen}
abbrev <- "tn" #this should stay the same as tn
lagos_name <- "Nitrogen, total dissolved"
lagos_unit <- "ug/l"
dataset_name <-"tdn"

#remember this should get pulled down from TN
params<-c("Total Nitrogen, mixed forms (NH3), (NH4), organic, (NO2) and (NO3)",
          "Nutrient-nitrogen",
          "Nitrogen, mixed forms (NH3), (NH4), organic, (NO2) and (NO3)",
          "Total Nitrogen, mixed forms",
          "Nitrogen")

data_temp<-data[data$CharacteristicName%in%params,] #want to match all records to the vector we created above 
unique(data_temp$ResultSampleFractionText)
data_temp <- data_temp %>% filter(ResultSampleFractionText=="Dissolved" | ResultSampleFractionText=="Filterable")
unique(data_temp$ResultSampleFractionText)

###create dataset to check for non numeric objects in dataset
temp<-non_numerics()

temp2 <- temp %>% filter(grepl("<",temp$ResultMeasureValue,fixed=TRUE)==TRUE) %>%  
  filter(is.na(DetectionQuantitationLimitMeasure.MeasureValue)) #grab values with "<" from result measure value and NA in detection limit

vals <- gsub("[^0-9.-]", "", temp2$ResultMeasureValue) #extract only values from result measure value

data_temp$DetectionQuantitationLimitMeasure.MeasureValue[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- vals #place values in the detectionlim col

data_temp$ResultDetectionConditionText[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- "Less Than"

data_temp$ResultMeasureValue[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- NA

temp <- non_numerics()

source("unit_conversions.R")
```

```{r Ammonia-ammonium}

abbrev <- "NH3NH4" 
lagos_name <- "Nitrogen, NH4"
lagos_unit <- "ug/l"
dataset_name <-"NH3NH4"

vars2process
params<-c("Ammonium", "Ammonia", "Ammonia-nitrogen as N", "Ammonia and ammonium", "Ammonia-nitrogen", "Ammonia as NH3", "Ammonium as N", "Ammonium as NH4")
vars2process<-vars2process[! vars2process %in% params] #remove grab samples from list
vars2process

data_temp<-data[data$CharacteristicName%in%params,] #want to match all records to the vector we created above 
unique(data_temp$ResultSampleFractionText)
data_temp <- data_temp %>% filter(ResultSampleFractionText=="Dissolved")
unique(data_temp$ResultSampleFractionText)

###create dataset to check for non numeric objects in dataset
temp<-non_numerics()
#no nonnumerics
source("unit_conversions.R")
rm(data_temp_temp_notes)

```

```{r NO2-N}

abbrev <- "NO2" 
lagos_name <- "Nitrogen, nitrite (NO2)"
lagos_unit <- "ug/l"
dataset_name <-"NO2"

vars2process
params<-c("Nitrite", "Nitrite as N")
vars2process<-vars2process[! vars2process %in% params] #remove grab samples from list
vars2process



data_temp<-data[data$CharacteristicName%in%params,] #want to match all records to the vector we created above 
unique(data_temp$ResultSampleFractionText)
data_temp <- data_temp %>% filter(ResultSampleFractionText=="Dissolved")
unique(data_temp$ResultSampleFractionText)

###create dataset to check for non numeric objects in dataset
temp<-non_numerics()

temp2 <- temp %>% filter(grepl("<",temp$ResultMeasureValue,fixed=TRUE)==TRUE) %>%  
  filter(is.na(DetectionQuantitationLimitMeasure.MeasureValue)) #grab values with "<" from result measure value and NA in detection limit

vals <- gsub("[^0-9.-]", "", temp2$ResultMeasureValue) #extract only values from result measure value

data_temp$DetectionQuantitationLimitMeasure.MeasureValue[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- vals #place values in the detectionlim col

data_temp$ResultDetectionConditionText[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- "Less Than"

data_temp$ResultMeasureValue[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- NA

temp <- non_numerics()

 #all NDs - can be converted to NAS

source("unit_conversions.R")

```

```{r NO2NO3-N}
abbrev <- "NO3"
lagos_name <- "Nitrogen, nitrite (NO2) + nitrate (NO3)"
lagos_unit <- "ug/l"
dataset_name <-"no3"

params<-c("Inorganic nitrogen (nitrate and nitrite)", 
          "Inorganic nitrogen (nitrate and nitrite) as N", 
          "Nitrate", 
          "Nitrate as N",
          "Nitrate + Nitrite",
          "Nitrogen",
          "Total Nitrogen, mixed forms",
          "Total Nitrogen, mixed forms (NH3), (NH4), organic, (NO2) and (NO3)",
          "Inorganic nitrogen (NO2, NO3, & NH3)"
          )
vars2process<-vars2process[! vars2process %in% params] #remove grab samples from list
vars2process #che

data_temp<-data[data$CharacteristicName%in%params,] #want to match all records to the vector we created above 
unique(data_temp$ResultSampleFractionText)
data_temp <- data_temp %>% filter(ResultSampleFractionText=="Dissolved")
unique(data_temp$ResultSampleFractionText)

###create dataset to check for non numeric objects in dataset
temp<-non_numerics()

###create dataset to check for non numeric objects in dataset
temp<-data_temp %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change #391 NA's - can change
unique(temp$ResultMeasureValue)

temp2 <- temp %>% filter(grepl("<",temp$ResultMeasureValue,fixed=TRUE)==TRUE) %>% 
  filter(is.na(DetectionQuantitationLimitMeasure.MeasureValue))
#if there were na values in detection would need to transfer over obs values to detection limits

#overwrite < with NA
data_temp <- data_temp %>% 
  mutate(ResultMeasureValue = ifelse(grepl("<",ResultMeasureValue,fixed=TRUE),NA,ResultMeasureValue))

source("unit_conversions.R")
```

```{r Silica}
abbrev <- "Si"
lagos_name <- "Silica, dissolved"
lagos_unit <- "mg/l"
dataset_name <-"silica"

params <- c("Silica", "Silicate", "Silicon") 
vars2process<-vars2process[! vars2process %in% params] #remove grab samples from list
vars2process #check if there are any missed variable

data_temp<-data[data$CharacteristicName%in%params,] #want to match all records to the vector we created above 
unique(data_temp$ResultSampleFractionText)
data_temp <- data_temp %>% filter(ResultSampleFractionText=="Dissolved")
unique(data_temp$ResultSampleFractionText)


###create dataset to check for non numeric objects in dataset
temp<- non_numerics() #checks for non numeric values in result measure value - if NA's not losing any other data - can change #391 NA's - can change
temp2 <- temp %>% filter(grepl("<",temp$ResultMeasureValue,fixed=TRUE)==TRUE) %>%  
  filter(is.na(DetectionQuantitationLimitMeasure.MeasureValue)) #grab values with "<" from result measure value and NA in detection limit

vals <- gsub("[^0-9.-]", "", temp2$ResultMeasureValue) #extract only values from result measure value

data_temp$DetectionQuantitationLimitMeasure.MeasureValue[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- vals #place values in the detectionlim col

data_temp$ResultDetectionConditionText[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- "Less Than"

data_temp$ResultMeasureValue[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- NA

temp <- non_numerics()

unique(temp$ResultMeasureValue)

source("unit_conversions.R")
data_temp_temp_notes
rm(data_temp_temp_notes)

```

```{r}
abbrev <- "Microcystin"
lagos_name <- "Microcystin"
lagos_unit <- "ug/l"
dataset_name <-"Microcystin"

vars2process
params<-c("Microcystin", "Microcystin RR", "Microcystin LF", "Microcystins and nodularins", "Microcystis", "Microcystin LR", "Microcystin LA", "Microcystins", "Microcystin YR", "Microcystin WR", "Microcystin-HtyR", "Microcystin HtYR", "Total microcystins plus nodularins", "Microcystin-HilR", "Microcystin dRR", "Microcystin HiLR", "Microcystin LY", "Dissolved microcystins plus nodularins", "Microcystin dLR", "Microcystin LW", "Microcystin/nodularin genes mcyE/ndaf")
vars2process<-vars2process[! vars2process %in% params] #remove grab samples from list
vars2process #check if any new varables to inlcude

data_temp<-data[data$CharacteristicName%in%params,] #want to match all records to the vector we created above 

###create dataset to check for non numeric objects in dataset
temp <- non_numerics()

temp2 <- temp %>% filter(grepl("<",temp$ResultMeasureValue,fixed=TRUE)==TRUE) %>%  
  filter(is.na(DetectionQuantitationLimitMeasure.MeasureValue)) #grab values with "<" from result measure value and NA in detection limit

vals <- gsub("[^0-9.-]", "", temp2$ResultMeasureValue) #extract only values from result measure value

data_temp$DetectionQuantitationLimitMeasure.MeasureValue[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- vals #place values in the detectionlim col

data_temp$ResultDetectionConditionText[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- "Less Than"

data_temp$ResultMeasureValue[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- NA

temp <- non_numerics()

source("unit_conversions.R")
data_temp_temp_notes
rm(data_temp_temp_notes)
```


```{r}
abbrev <- "K"
lagos_name <- "Potassium"
lagos_unit <- "mg/l"
dataset_name <-"Potassium"

vars2process
params<-c("Potassium")
vars2process<-vars2process[! vars2process %in% params] #remove grab samples from list
vars2process #check if any new varables to inlcude

data_temp<-data[data$CharacteristicName%in%params,] #want to match all records to the vector we created above 

###create dataset to check for non numeric objects in dataset
temp <- non_numerics()

temp2 <- temp %>% filter(grepl("<",temp$ResultMeasureValue,fixed=TRUE)==TRUE) %>%  
  filter(is.na(DetectionQuantitationLimitMeasure.MeasureValue)) #grab values with "<" from result measure value and NA in detection limit

vals <- gsub("[^0-9.-]", "", temp2$ResultMeasureValue) #extract only values from result measure value

data_temp$DetectionQuantitationLimitMeasure.MeasureValue[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- vals #place values in the detectionlim col

data_temp$ResultDetectionConditionText[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- "Less Than"

data_temp$ResultMeasureValue[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- NA

temp <- non_numerics()

source("unit_conversions.R")
data_temp_temp_notes
rm(data_temp_temp_notes)
```


```{r}
abbrev <- "Na"
lagos_name <- "Sodium"
lagos_unit <- "mg/l"
dataset_name <-"Sodium"

vars2process
params<-c("Sodium")
vars2process<-vars2process[! vars2process %in% params] #remove grab samples from list
vars2process #check if any new varables to inlcude

data_temp<-data[data$CharacteristicName%in%params,] #want to match all records to the vector we created above 

###create dataset to check for non numeric objects in dataset
temp <- non_numerics()

temp2 <- temp %>% filter(grepl("<",temp$ResultMeasureValue,fixed=TRUE)==TRUE) %>%  
  filter(is.na(DetectionQuantitationLimitMeasure.MeasureValue)) #grab values with "<" from result measure value and NA in detection limit

vals <- gsub("[^0-9.-]", "", temp2$ResultMeasureValue) #extract only values from result measure value

data_temp$DetectionQuantitationLimitMeasure.MeasureValue[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- vals #place values in the detectionlim col

data_temp$ResultDetectionConditionText[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- "Less Than"

data_temp$ResultMeasureValue[which(data_temp$Obs_Id %in% temp2$Obs_Id)] <- NA

temp <- non_numerics()

source("unit_conversions.R")
data_temp_temp_notes
rm(data_temp_temp_notes)
```

```{r}
abbrev <- "IC"
lagos_name <- "Carbon, total inorganic"
lagos_unit <- "mg/l"
dataset_name <-"TIC"

vars2process
params<-c("Inorganic carbon")
vars2process<-vars2process[! vars2process %in% params] #remove grab samples from list
vars2process #check if any new varables to inlcude

data_temp<-data[data$CharacteristicName%in%params,] #want to match all records to the vector we created above 
unique(data_temp$ResultSampleFractionText)
data_temp <- data_temp %>% filter(ResultSampleFractionText=="Total")
unique(data_temp$ResultSampleFractionText)

###create dataset to check for non numeric objects in dataset
temp <- non_numerics()
#no non numerics to convert

source("unit_conversions.R")
data_temp_temp_notes
rm(data_temp_temp_notes)
```

```{r}
abbrev <- "IC"
lagos_name <- "Carbon, dissolved inorganic"
lagos_unit <- "mg/l"
dataset_name <-"DIC"

vars2process
params<-c("Inorganic carbon")
vars2process<-vars2process[! vars2process %in% params] #remove grab samples from list
vars2process #check if any new varables to inlcude

data_temp<-data[data$CharacteristicName%in%params,] #want to match all records to the vector we created above 
unique(data_temp$ResultSampleFractionText)
data_temp <- data_temp %>% filter(ResultSampleFractionText=="Dissolved" | ResultSampleFractionText=="Filterable")
unique(data_temp$ResultSampleFractionText)

###create dataset to check for non numeric objects in dataset
temp <- non_numerics()

source("unit_conversions.R")
data_temp_temp_notes
rm(data_temp_temp_notes)
```


```{r}
abbrev <- "anc"
lagos_name <- "ANC"
lagos_unit <- "ueq/l"
dataset_name <-"anc"

vars2process
params<-c("Gran acid neutralizing capacity")
vars2process<-vars2process[! vars2process %in% params] #remove grab samples from list
vars2process #check if any new varables to inlcude

data_temp<-data[data$CharacteristicName%in%params,] #want to match all records to the vector we created above 

###create dataset to check for non numeric objects in dataset
temp <- non_numerics()
#Can be converted to NAs
source("unit_conversions.R")
data_temp_temp_notes
rm(data_temp_temp_notes)
```





```{r}

vars2process
data_all <- do.call("rbind", lapply(ls(pattern='^data_'),get))
data_all$ResultMeasureValue<-data_all$Converted
data_all$DetectionQuantitationLimitMeasure.MeasureValue<-data_all$Converted_dl
data_all<-data_all %>% select(-Converted, -Converted_dl)
write_csv(data_all, file = "all_data_june10.csv")

# vals<-unique(data_all$MonitoringLocationIdentifier)
# 
# vals1<-data_all %>% select(MonitoringLocationIdentifier)
# temp<-vals1 %>% distinct() 
# vals1<-vals %>% distinct()
# 
#vals2<-data_all %>% select(lagoslakeid)
#temp<-vals2 %>% distinct() 
# 
# vals3<-data_all %>% select(wqp_monitoringlocationname)
# temp<-vals3 %>% distinct() 
# 
# lakelink<-read.csv("~/GitHub/lagos_database/lake_link.csv")
# 
# temp<-lakelink %>% filter(!is.na(wqp_monitoringlocationidentifier))
# n_lakes<-unique(temp$lagoslakeid)
# 
# n_lakes2<-unique(data_all$lagoslakeid)


#UniqueMonitoringLocationIdentifier<-data_all %>% distinct(MonitoringLocationIdentifier, .keep_all = T)

#write_csv(UniqueMonitoringLocationIdentifier, file = "UniqueMonitoringLocationIdentifier.csv")

# vars2process
# data_all <- do.call("rbind", lapply(ls(pattern='^data_'),get))
# data_all$ResultMeasureValue<-data_all$Converted
# data_all$DetectionQuantitationLimitMeasure.MeasureValue<-data_all$Converted_dl
# data_all<-data_all %>% select(-Converted, -Converted_dl)
# write_csv(data_all, file = "alldata_patrick.csv")
# 
# 
# 
# texas<-read.csv("~/Lagos Limno/TX_alldata_1975_to_2020.csv")

```


