---
title: "Datacleaningcode_AL"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
#here are functions
#for temperature
resultconvert_celsius<-function(dat, variable, unit, out_unit) {
  dat$ResultMeasureValue[which(dat$CharacteristicName == variable & dat$ResultMeasure.MeasureUnitCode == unit)] <- (dat$ResultMeasureValue[which(dat$CharacteristicName == variable & dat$ResultMeasure.MeasureUnitCode == unit)] -32)* 5/9
  
dat$ResultMeasure.MeasureUnitCode[which(dat$CharacteristicName == variable & dat$ResultMeasure.MeasureUnitCode == unit)] <- out_unit

return(dat)
  
}


detectconvert_celsius<-function(dat, variable, unit, out_unit) {
  dat$DetectionQuantitationLimitMeasure.MeasureValue[which(dat$CharacteristicName == variable & dat$DetectionQuantitationLimitMeasure.MeasureUnitCode == unit)] <- (dat$DetectionQuantitationLimitMeasure.MeasureValue[which(dat$CharacteristicName == variable & dat$DetectionQuantitationLimitMeasure.MeasureUnitCode == unit)] * -32)*5/9
  
dat$DetectionQuantitationLimitMeasure.MeasureUnitCode[which(dat$CharacteristicName == variable & dat$DetectionQuantitationLimitMeasure.MeasureUnitCode == unit)] <- out_unit

return(dat)
  
}

#for all other conversions

resultconvert<-function(dat, variable, unit, out_unit, conv_factor) {
  dat$ResultMeasureValue[which(dat$CharacteristicName == variable & dat$ResultMeasure.MeasureUnitCode == unit)] <- dat$ResultMeasureValue[which(dat$CharacteristicName == variable & dat$ResultMeasure.MeasureUnitCode == unit)] * conv_factor
  
dat$ResultMeasure.MeasureUnitCode[which(dat$CharacteristicName == variable & dat$ResultMeasure.MeasureUnitCode == unit)] <- out_unit

return(dat)
  
}


detectconvert<-function(dat, variable, unit, out_unit, conv_factor) {
  dat$DetectionQuantitationLimitMeasure.MeasureValue[which(dat$CharacteristicName == variable & dat$DetectionQuantitationLimitMeasure.MeasureUnitCode == unit)] <- dat$DetectionQuantitationLimitMeasure.MeasureValue[which(dat$CharacteristicName == variable & dat$DetectionQuantitationLimitMeasure.MeasureUnitCode == unit)] * conv_factor
  
dat$DetectionQuantitationLimitMeasure.MeasureUnitCode[which(dat$CharacteristicName == variable & dat$DetectionQuantitationLimitMeasure.MeasureUnitCode == unit)] <- out_unit

return(dat)
  
}


`%notin%` <- Negate(`%in%`)

ALdatPull<-read.csv("~/Lagos Limno/AL_alldata_1975_to_2020.csv")

names(ALdatPull)

summary(ALdatPull)

#removing data that have Y's instead of keeping data that have N's

read.csv("~/Lagos Limno/list of unique parameters to remove.csv") -> remove_params #update this


data<- ALdatPull[COdatPull$CharacteristicName %notin% remove_params$Unique.parameters,]
data<-data %>% mutate(obs_id = seq(1, nrow(data), 1))
                                                                                                            
tdata1<-data %>% filter(!is.na(ResultDepthHeightMeasure.MeasureValue)) #identified specified depth samples



tdata2<-data %>% filter(is.na(ResultDepthHeightMeasure.MeasureValue)) %>% filter(!is.na(ActivityTopDepthHeightMeasure.MeasureValue)) #these are potential integrated samples

unique(tdata2$SampleCollectionMethod.MethodName)
method_name<-c("WQCD Vertically Integrating Lake Sampling Procedure")

unique(tdata2$SampleCollectionMethod.MethodIdentifier)
method_identifier<-c("")

unique(tdata2$SampleCollectionMethod.MethodIdentifierContext)
method_context<-c("")

unique(tdata2$SampleCollectionEquipmentName)
method_equipment<-c("")

tdata2<-tdata2 %>% filter(SampleCollectionMethod.MethodName %in% method_name | 
                            SampleCollectionMethod.MethodIdentifier %in% method_identifier|
                            SampleCollectionMethod.MethodIdentifierContext %in% method_context|
                            SampleCollectionEquipmentName %in% method_equipment)  #all grab samples

tdata3<-data %>% filter(is.na(ResultDepthHeightMeasure.MeasureValue)) #identifying grab samples

unique(tdata3$SampleCollectionMethod.MethodName)
method_name<-c("Grab sample  (dip)", "Grab", "Grab Sample", "GRAB", "Standard Grab Method", "Single vertical", "Open-top bailer")

unique(tdata3$SampleCollectionMethod.MethodIdentifier)
method_identifier<-c("GRAB_WQX", "Grab", "GRAB", "BLCACURE_GRAB", "NPS_GRAB")

unique(tdata3$SampleCollectionMethod.MethodIdentifierContext)
method_context<-c("USGS parameter code 82398", "GRAB", "Grab")

unique(tdata3$SampleCollectionEquipmentName)
method_equipment<-c("Open-Mouth Bottle", "Grab sample", "Open-top bailer")

tdata3<-tdata3 %>% filter(SampleCollectionMethod.MethodName %in% method_name | 
                            SampleCollectionMethod.MethodIdentifier %in% method_identifier|
                            SampleCollectionMethod.MethodIdentifierContext %in% method_context|
                            SampleCollectionEquipmentName %in% method_equipment)  #all grab samples

data2<-rbind(tdata1, tdata2, tdata3)
rm(tdata1)
rm(tdata2)
rm(tdata3)

tdata4<-data %>% filter(obs_id %notin% data2$obs_id)#created object to look at all data not in datata2

unique(tdata4$CharacteristicName)
secchiparams<-c("Secchi, Horizontal Distance", "Depth, Secchi disk depth") #pulled out secchi data cuz it may not have depth data

tdata4<-tdata4 %>% filter(CharacteristicName %in% secchiparams) #filtered out only the secchi vars
data<-rbind(data2, tdata4) #combined everything back together

#will need to check for each state (the depth data)

rm(tdata4)
rm(data2)
data<-data %>% select(-obs_id)
rm(COdatPull)
unique(data$CharacteristicName)

data<-data %>% filter(!(is.na(ResultMeasureValue) & is.na(DetectionQuantitationLimitMeasure.MeasureValue)))



#unique organizations
unique(data$OrganizationIdentifier) #19 organizations data
table(data$OrganizationFormalName) #tells us number of obvs in each organization




#looking at activity type codes
unique(data$ActivityTypeCode)
activitytype_keep<-c( "Quality Control Sample-Field Replicate",
                      "Quality Control Field Replicate Msr/Obs",
                      "Quality Control Sample-Other", 
                      "Quality Control Sample-Reference Sample",
                      "Quality Control Sample-Field Blank",
                      "Quality Control Sample-Lab Matrix Spike",
                      "Quality Control Sample-Lab Duplicate","Quality Control Sample-Lab Matrix Spike Duplicate",
                      "Quality Control Sample-Blind Duplicate")
data<-data[which(data$ActivityTypeCode %notin% activitytype_keep),]
unique(data$ActivityTypeCode)

#manually checking these columns to see if these is data we keep or can drop

unique(data$SubjectTaxonomicName) #expected it to be na - to make sure nothing we need is in there
unique(data$SampleTissueAnatomyName) #also NA's - expected

unique(data$ActivityMediaSubdivisionName)
#only keeping subdivision name with surface water and NA's - dropping everything else 
data<-data %>% filter(ActivityMediaSubdivisionName == "Surface Water" | is.na(ActivityMediaSubdivisionName))
unique(data$ActivityMediaSubdivisionName)

unique(data$ResultStatusIdentifier)
unique(data$ResultValueTypeName)


unique(data$ResultDetectionConditionText)
#filtered out vars we don't need in resultsdetection condition text - did it in multistep because R doesn't handle multiple OR statements well


data<-data %>% filter(ResultDetectionConditionText != "Systematic Contamination" | is.na(ResultDetectionConditionText))

data<-data %>% filter(is.na(ResultDetectionConditionText) | ResultDetectionConditionText != "Not Reported")
unique(data$ResultDetectionConditionText)



unique(data$ResultSampleFractionText)

data<-data %>% filter(is.na(ResultSampleFractionText) | ResultSampleFractionText != "Bed Sediment")
unique(data$ResultSampleFractionText)


data<-data %>% select(-X,-ActivityMediaName, -ActivityMediaSubdivisionName, -ActivityStartTime.Time, -ActivityStartTime.TimeZoneCode, -ActivityEndTime.Time, -ActivityEndTime.TimeZoneCode, -SampleAquifer, -HydrologicCondition, -HydrologicEvent, -SubjectTaxonomicName, -SampleTissueAnatomyName, -LaboratoryName, -AnalysisStartDate, -PreparationStartDate)

```

```{r}
#list of unique parameters
unique(data$CharacteristicName)
write.table(unique(data$CharacteristicName), "unique_parameters.csv", row.names = FALSE)
getwd()

sum(is.na(data$ResultDepthHeightMeasure.MeasureValue))
unique(data$ActivityTypeCode)
unique(data$ResultDepthAltitudeReferencePointText)
temp<-data %>% filter(ResultDepthAltitudeReferencePointText == "Surface")
unique(data$SampleCollectionMethod.MethodName)

```

```{r}

###creating new columns to preserve original pulled data

data$source_parameter <- data$CharacteristicName
data$source_value<- data$ResultMeasureValue
data$source_unit <- data$ResultMeasure.MeasureUnitCode
data$detectionlimit_legacy <- data$DetectionQuantitationLimitMeasure.MeasureValue
data$detectionlimit_unit_legacy <- data$DetectionQuantitationLimitMeasure.MeasureUnitCode
```

```{r}
###Secchi
unique(data$CharacteristicName)

###set all the secchi params to read as secchi instead of the 6 objects below

secchi_params<-c("Depth, Secchi disk depth", "Secchi, Horizontal Distance", "Water transparency, Secchi disc")
data_secchi<-data[data$CharacteristicName%in%secchi_params,]
data_secchi$CharacteristicName<-"Secchi"

###checking for Na's
unique(data_secchi$ResultMeasure.MeasureUnitCode) #checked units
temp<-data_secchi %>% filter(is.na(ResultMeasure.MeasureUnitCode)) #checked how many na's we had #only 4
data_secchi<-data_secchi %>% filter(!is.na(ResultMeasure.MeasureUnitCode)) #filtered out NA's


###create dataset to check for non numeric objects in dataset
temp<-data_secchi %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in the results
data_secchi<-data_secchi %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

###convert inches to m for obvservations
data_secchi$ResultMeasureValue[which(data_secchi$ResultMeasure.MeasureUnitCode == "in")] <- data_secchi$ResultMeasureValue[which(data_secchi$ResultMeasure.MeasureUnitCode == "in")] * 0.0254

data_secchi[(!is.na(data_secchi$DetectionQuantitationLimitMeasure.MeasureUnitCode) & data_secchi$ResultMeasure.MeasureUnitCode != data_secchi$DetectionQuantitationLimitMeasure.MeasureUnitCode),] #checks to see if detection limit units same as obvs units

#convert inches to m for detectionlimits
data_secchi$DetectionQuantitationLimitMeasure.MeasureValue[which(data_secchi$ResultMeasure.MeasureUnitCode == "in")] <- data_secchi$DetectionQuantitationLimitMeasure.MeasureValue[which(data_secchi$ResultMeasure.MeasureUnitCode == "in")] * 0.0254


####convert ft to m's for values

data_secchi$ResultMeasureValue[which(data_secchi$ResultMeasureValue == "ft")] <-
  data_secchi$ResultMeasureValue[which(data_secchi$ResultMeasureValue == "ft")] * 0.3048

#convert ft to m's for detection limits

data_secchi$DetectionQuantitationLimitMeasure.MeasureValue[which(data_secchi$DetectionQuantitationLimitMeasure.MeasureValue == "ft")]<-
  data_secchi$DetectionQuantitationLimitMeasure.MeasureValue[which(data_secchi$DetectionQuantitationLimitMeasure.MeasureValue == "ft")] * 0.3048

#then change all the units to m

data_secchi$ResultMeasure.MeasureUnitCode<-"m" #for values

data_secchi$DetectionQuantitationLimitMeasure.MeasureUnitCode<-"m"  #for detection limit
#check to see if it worked
unique(data_secchi$ResultMeasure.MeasureUnitCode)
unique(data_secchi$DetectionQuantitationLimitMeasure.MeasureUnitCode)


```

```{r}
###calcium

unique(data$CharacteristicName)

calcium_params<-c("Calcium") #only values for Calcium
data_calcium<-data[data$CharacteristicName%in%calcium_params,] #want to match all records to the vector we created above which have Calcium

#checking and filtering out NA's
unique(data_calcium$ResultMeasure.MeasureUnitCode) #checked units
temp<-data_calcium %>% filter(is.na(ResultMeasure.MeasureUnitCode)) #checked how many na's we had #only 5
#data_calcium<-data_calcium %>% filter(!is.na(ResultMeasure.MeasureUnitCode)) #filtered out NA's

###create dataset to check for non numeric objects in dataset
temp<-data_calcium %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in the results # 4 non numeric values
data_calcium<-data_calcium %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA


data_calcium$CharacteristicName<-"Calcium"  #rename everything in the characteristics column as calcium

###convert ppm to mg/l for obvservations ##1ppm = 1mg/l
data_calcium$ResultMeasureValue[which(data_calcium$ResultMeasure.MeasureUnitCode == "ppm")] <- data_calcium$ResultMeasureValue[which(data_calcium$ResultMeasure.MeasureUnitCode == "ppm")] * 1

data_calcium[(!is.na(data_calcium$DetectionQuantitationLimitMeasure.MeasureUnitCode) & data_calcium$ResultMeasure.MeasureUnitCode != data_calcium$DetectionQuantitationLimitMeasure.MeasureUnitCode),] #checks to see if detection limit units same as obvs units

#convert ppm to mg/l for detectionlimits
data_calcium$DetectionQuantitationLimitMeasure.MeasureValue[which(data_calcium$ResultMeasure.MeasureUnitCode == "ppm")] <- data_calcium$DetectionQuantitationLimitMeasure.MeasureValue[which(data_calcium$ResultMeasure.MeasureUnitCode == "ppm")] * 1


####convert ug/l to mg/l for values

data_calcium$ResultMeasureValue[which(data_calcium$ResultMeasureValue == "ug/l")] <-
  data_calcium$ResultMeasureValue[which(data_calcium$ResultMeasureValue == "ug/l")] / 0.001

#convert ug/l to mg/l for detection limits

data_calcium$DetectionQuantitationLimitMeasure.MeasureValue[which(data_calcium$DetectionQuantitationLimitMeasure.MeasureValue == "ug/l")]<-
  data_calcium$DetectionQuantitationLimitMeasure.MeasureValue[which(data_calcium$DetectionQuantitationLimitMeasure.MeasureValue == "ug/l")] /0.001

#then change all the units to mg/l

data_calcium$ResultMeasure.MeasureUnitCode<-"mg/l" #for values
data_calcium$DetectionQuantitationLimitMeasure.MeasureUnitCode<-"mg/l"  #for detection limit

#check to see if it worked
unique(data_calcium$ResultMeasure.MeasureUnitCode)
unique(data_calcium$DetectionQuantitationLimitMeasure.MeasureUnitCode)

unique(data_calcium$ResultSampleFractionText) # we want to only keep dissolved 
data_calcium<-data_calcium %>% filter(ResultSampleFractionText == "Dissolved") 



```

```{r}
#aluminum

unique(data$CharacteristicName)

Aluminum_params<-c("Aluminum") #only values for aluminum
data_aluminum<-data[data$CharacteristicName%in%Aluminum_params,] #want to match all records to the vector we created above which have Calcium
data_aluminum$CharacteristicName<-"Aluminum"  #rename everything in the characteristics column as calcium

#checking and filtering out NA's
unique(data_aluminum$ResultMeasure.MeasureUnitCode) #checked units
temp<-data_aluminum %>% filter(is.na(ResultMeasure.MeasureUnitCode)) #had 521 - not filtering out in this case - check with NOAH
#data_aluminum<-data_aluminum %>% filter(!is.na(ResultMeasure.MeasureUnitCode)) #filtered out NA's

###create dataset to check for non numeric objects in dataset
temp<-data_aluminum %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in the results # 1332 non numeric values
data_aluminum$ResultDetectionConditionText[which(data_aluminum$ResultMeasureValue == "< 3")] <- "Not Detected"
data_aluminum<-data_aluminum %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA  -- CHECK WITH NOAH
unique(temp$ResultMeasureValue)


###convert ppm to mg/l for obvservations ##1ppm = 1mg/l
#data_aluminum$ResultMeasureValue[which(data_aluminum$ResultMeasure.MeasureUnitCode == "in")] <- data_aluminum$ResultMeasureValue[which(data_aluminum$ResultMeasure.MeasureUnitCode == "in")] * 1

#data_aluminum[(!is.na(data_aluminum$DetectionQuantitationLimitMeasure.MeasureUnitCode) & data_aluminum$ResultMeasure.MeasureUnitCode != data_aluminum$DetectionQuantitationLimitMeasure.MeasureUnitCode),] #checks to see if detection limit units same as obvs units

#convert ppm to mg/l for detectionlimits
#data_aluminum$DetectionQuantitationLimitMeasure.MeasureValue[which(data_aluminum$ResultMeasure.MeasureUnitCode == "in")] <- data_aluminum$DetectionQuantitationLimitMeasure.MeasureValue[which(data_aluminum$ResultMeasure.MeasureUnitCode == "in")] * 1


####convert mg/l to ug/l for values

data_aluminum$ResultMeasureValue[which(data_aluminum$ResultMeasureValue == "mg/l")] <-
  data_aluminum$ResultMeasureValue[which(data_aluminum$ResultMeasureValue == "mg/l")] *1000

#convert mg/l to ug/l for detection limits

data_aluminum$DetectionQuantitationLimitMeasure.MeasureValue[which(data_aluminum$DetectionQuantitationLimitMeasure.MeasureValue == "mg/l")]<-
data_aluminum$DetectionQuantitationLimitMeasure.MeasureValue[which(data_aluminum$DetectionQuantitationLimitMeasure.MeasureValue == "mg/l")] *1000

#then change all the units to ug/l

data_aluminum$ResultMeasure.MeasureUnitCode<-"ug/l" #for values
data_aluminum$DetectionQuantitationLimitMeasure.MeasureUnitCode<-"ug/l"  #for detection limit

#check to see if it worked
unique(data_aluminum$ResultMeasure.MeasureUnitCode)
unique(data_aluminum$DetectionQuantitationLimitMeasure.MeasureUnitCode)

unique(data_aluminum$ResultSampleFractionText)
data_aluminum$ResultSampleFractionText[which(data_aluminum$ResultSampleFractionText == "Recoverable")]<-"Total"  #add recoverable into total category


```

```{r}
###silica

unique(data$CharacteristicName)

silica_params<-c("Silica") #only values for Calcium
data_silica<-data[data$CharacteristicName%in%silica_params,] #want to match all records to the vector we created above which have silica
data_silica$CharacteristicName<-"Silica"  #rename everything in the characteristics column as silica

unique(data_silica$ResultSampleFractionText)

#checking and filtering out NA's
unique(data_silica$ResultMeasure.MeasureUnitCode) #checked units
temp<-data_silica %>% filter(is.na(ResultMeasure.MeasureUnitCode)) #checked how many na's we had #158
data_silica<-data_silica %>% filter(!is.na(ResultMeasure.MeasureUnitCode)) #filtered out NA's

###create dataset to check for non numeric objects in dataset
temp<-data_silica %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in the results # 2 non numeric values
data_silica<-data_silica %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA


data_silica[(!is.na(data_silica$DetectionQuantitationLimitMeasure.MeasureUnitCode) & data_silica$ResultMeasure.MeasureUnitCode != data_silica$DetectionQuantitationLimitMeasure.MeasureUnitCode),] #checks to see if detection limit units same as obvs units - equals 0 - expected

###convert ppm to mg/l for obvservations ##1ppm = 1mg/l
#data_silica$ResultMeasureValue[which(data_silica$ResultMeasure.MeasureUnitCode == "ppm")] <- data_silica$ResultMeasureValue[which(data_silica$ResultMeasure.MeasureUnitCode == "ppm")] * 1

#convert ppm to mg/l for detectionlimits
#data_silica$DetectionQuantitationLimitMeasure.MeasureValue[which(data_silica$ResultMeasure.MeasureUnitCode == "ppm")] <- data_silica$DetectionQuantitationLimitMeasure.MeasureValue[which(data_silica$ResultMeasure.MeasureUnitCode == "ppm")] * 1


####convert ug/l to mg/l for values

#data_silica$ResultMeasureValue[which(data_silica$ResultMeasureValue == "ug/l")] <-
#data_silica$ResultMeasureValue[which(data_silica$ResultMeasureValue == "ug/l")] / 0.001

#convert ug/l to mg/l for detection limits

#data_silica$DetectionQuantitationLimitMeasure.MeasureValue[which(data_silica$DetectionQuantitationLimitMeasure.MeasureValue == "ug/l")]<-
#data_silica$DetectionQuantitationLimitMeasure.MeasureValue[which(data_silica$DetectionQuantitationLimitMeasure.MeasureValue == "ug/l")] /0.001

#then change all the units to mg/l

data_silica$ResultMeasure.MeasureUnitCode<-"mg/l" #for values
data_silica$DetectionQuantitationLimitMeasure.MeasureUnitCode<-"mg/l"  #for detection limit

#check to see if it worked
unique(data_silica$ResultMeasure.MeasureUnitCode)
unique(data_silica$DetectionQuantitationLimitMeasure.MeasureUnitCode)


```

```{r}
#selenium

unique(data$CharacteristicName)

selenium_params<-c("Selenium") #only values for selenium
data_selenium<-data[data$CharacteristicName%in%selenium_params,] #want to match all records to the vector we created above which have selenium
data_selenium$CharacteristicName<-"selenium"  #rename everything in the characteristics column as selenium

unique(data_selenium$ResultSampleFractionText)
data_selenium$ResultSampleFractionText[which(data_selenium$ResultSampleFractionText == "Total Recoverable")] <- "Total"
unique(data_selenium$ResultSampleFractionText)

#checking and filtering out NA's
unique(data_selenium$ResultMeasure.MeasureUnitCode) #checked units
temp<-data_selenium %>% filter(is.na(ResultMeasure.MeasureUnitCode)) #checked how many na's we had #806
data_selenium<-data_selenium %>% filter(!is.na(ResultMeasure.MeasureUnitCode)) #filtered out NA's

###create dataset to check for non numeric objects in dataset
temp<-data_selenium %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in the results # 4 non numeric values
data_selenium<-data_selenium %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA


###convert ppm to mg/l for obvservations ##1ppm = 1mg/l
data_selenium$ResultMeasureValue[which(data_selenium$ResultMeasure.MeasureUnitCode == "ppm")] <- data_selenium$ResultMeasureValue[which(data_selenium$ResultMeasure.MeasureUnitCode == "ppm")] * 1

data_selenium[(!is.na(data_selenium$DetectionQuantitationLimitMeasure.MeasureUnitCode) & data_selenium$ResultMeasure.MeasureUnitCode != data_selenium$DetectionQuantitationLimitMeasure.MeasureUnitCode),] #checks to see if detection limit units same as obvs units

#convert ppm to mg/l for detectionlimits
data_selenium$DetectionQuantitationLimitMeasure.MeasureValue[which(data_selenium$ResultMeasure.MeasureUnitCode == "ppm")] <- data_selenium$DetectionQuantitationLimitMeasure.MeasureValue[which(data_selenium$ResultMeasure.MeasureUnitCode == "ppm")] * 1


####convert ug/l to mg/l for values

data_selenium$ResultMeasureValue[which(data_selenium$ResultMeasureValue == "ug/l")] <-
  data_selenium$ResultMeasureValue[which(data_selenium$ResultMeasureValue == "ug/l")] / 0.001

#convert ug/l to mg/l for detection limits

data_selenium$DetectionQuantitationLimitMeasure.MeasureValue[which(data_selenium$DetectionQuantitationLimitMeasure.MeasureValue == "ug/l")]<-
  data_selenium$DetectionQuantitationLimitMeasure.MeasureValue[which(data_selenium$DetectionQuantitationLimitMeasure.MeasureValue == "ug/l")] /0.001

#then change all the units to mg/l

data_selenium$ResultMeasure.MeasureUnitCode<-"mg/l" #for values
data_selenium$DetectionQuantitationLimitMeasure.MeasureUnitCode<-"mg/l"  #for detection limit

#check to see if it worked
unique(data_selenium$ResultMeasure.MeasureUnitCode)
unique(data_selenium$DetectionQuantitationLimitMeasure.MeasureUnitCode)
```

```{r}
###Arsenic

unique(data$CharacteristicName)

arsenic_params<-c("Arsenic") #only values for Arsenic
data_arsenic<-data[data$CharacteristicName%in%arsenic_params,] #want to match all records to the vector we created above which have Arsenic
data_arsenic$CharacteristicName<-"arsenic"  #rename everything in the characteristics column as Arsenic

unique(data_arsenic$ResultSampleFractionText)
data_arsenic$ResultSampleFractionText[which(data_arsenic$ResultSampleFractionText == "Total Recoverable")] <- "Total"
unique(data_arsenic$ResultSampleFractionText)


#checking and filtering out NA's
unique(data_arsenic$ResultMeasure.MeasureUnitCode) #checked units
temp<-data_arsenic %>% filter(is.na(ResultMeasure.MeasureUnitCode)) #checked how many na's we had #only 5
data_arsenic<-data_arsenic %>% filter(!is.na(ResultMeasure.MeasureUnitCode)) #filtered out NA's

###create dataset to check for non numeric objects in dataset
temp<-data_arsenic %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in the results # 4 non numeric values
data_arsenic<-data_arsenic %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA


###convert ppm to mg/l for obvservations ##1ppm = 1mg/l
data_arsenic$ResultMeasureValue[which(data_arsenic$ResultMeasure.MeasureUnitCode == "ppm")] <- data_arsenic$ResultMeasureValue[which(data_arsenic$ResultMeasure.MeasureUnitCode == "ppm")] * 1

data_arsenic[(!is.na(data_arsenic$DetectionQuantitationLimitMeasure.MeasureUnitCode) & data_arsenic$ResultMeasure.MeasureUnitCode != data_arsenic$DetectionQuantitationLimitMeasure.MeasureUnitCode),] #checks to see if detection limit units same as obvs units

#convert ppm to mg/l for detectionlimits
data_arsenic$DetectionQuantitationLimitMeasure.MeasureValue[which(data_arsenic$ResultMeasure.MeasureUnitCode == "ppm")] <- data_arsenic$DetectionQuantitationLimitMeasure.MeasureValue[which(data_arsenic$ResultMeasure.MeasureUnitCode == "ppm")] * 1


####convert ug/l to mg/l for values

data_arsenic$ResultMeasureValue[which(data_arsenic$ResultMeasureValue == "ug/l")] <-
  data_arsenic$ResultMeasureValue[which(data_arsenic$ResultMeasureValue == "ug/l")] / 0.001

#convert ug/l to mg/l for detection limits

data_arsenic$DetectionQuantitationLimitMeasure.MeasureValue[which(data_arsenic$DetectionQuantitationLimitMeasure.MeasureValue == "ug/l")]<-
  data_arsenic$DetectionQuantitationLimitMeasure.MeasureValue[which(data_arsenic$DetectionQuantitationLimitMeasure.MeasureValue == "ug/l")] /0.001

#then change all the units to mg/l

data_arsenic$ResultMeasure.MeasureUnitCode<-"mg/l" #for values
data_arsenic$DetectionQuantitationLimitMeasure.MeasureUnitCode<-"mg/l"  #for detection limit

#check to see if it worked
unique(data_arsenic$ResultMeasure.MeasureUnitCode)
unique(data_arsenic$DetectionQuantitationLimitMeasure.MeasureUnitCode)
```

```{r}
#turbidity

unique(data$CharacteristicName)

turbidity_params<-c("Turbidity") #only values for turbidity
data_turbidity<-data[data$CharacteristicName%in%turbidity_params,] #want to match all records to the vector we created above which have Calcium
data_turbidity$CharacteristicName<-"turbidity"  #rename everything in the characteristics column as calcium

unique(data_turbidity$ResultSampleFractionText)


#checking and filtering out NA's
unique(data_turbidity$ResultMeasure.MeasureUnitCode) #checked units
temp<-data_turbidity %>% filter(is.na(ResultMeasure.MeasureUnitCode)) #had 521 - not filtering out in this case - check with NOAH
#data_turbidity<-data_turbidity %>% filter(!is.na(ResultMeasure.MeasureUnitCode)) #filtered out NA's

###create dataset to check for non numeric objects in dataset
temp<-data_turbidity %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in the results # 1332 non numeric values
data_turbidity<-data_turbidity %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA  -- CHECK WITH NOAH
unique(temp$ResultMeasureValue)


###convert ppm to mg/l for obvservations ##1ppm = 1mg/l
#data_turbidity$ResultMeasureValue[which(data_turbidity$ResultMeasure.MeasureUnitCode == "in")] <- data_turbidity$ResultMeasureValue[which(data_turbidity$ResultMeasure.MeasureUnitCode == "in")] * 1

#data_turbidity[(!is.na(data_turbidity$DetectionQuantitationLimitMeasure.MeasureUnitCode) & data_turbidity$ResultMeasure.MeasureUnitCode != data_turbidity$DetectionQuantitationLimitMeasure.MeasureUnitCode),] #checks to see if detection limit units same as obvs units

#convert ppm to mg/l for detectionlimits
#data_turbidity$DetectionQuantitationLimitMeasure.MeasureValue[which(data_turbidity$ResultMeasure.MeasureUnitCode == "in")] <- data_turbidity$DetectionQuantitationLimitMeasure.MeasureValue[which(data_turbidity$ResultMeasure.MeasureUnitCode == "in")] * 1


####convert mg/l to ug/l for values

data_turbidity$ResultMeasureValue[which(data_turbidity$ResultMeasureValue == "mg/l")] <-
  data_turbidity$ResultMeasureValue[which(data_turbidity$ResultMeasureValue == "mg/l")] *1000

#convert mg/l to ug/l for detection limits

data_turbidity$DetectionQuantitationLimitMeasure.MeasureValue[which(data_turbidity$DetectionQuantitationLimitMeasure.MeasureValue == "mg/l")]<-
data_turbidity$DetectionQuantitationLimitMeasure.MeasureValue[which(data_turbidity$DetectionQuantitationLimitMeasure.MeasureValue == "mg/l")] *1000

#then change all the units to ug/l

data_turbidity$ResultMeasure.MeasureUnitCode<-"ug/l" #for values
data_turbidity$DetectionQuantitationLimitMeasure.MeasureUnitCode<-"ug/l"  #for detection limit

#check to see if it worked
unique(data_turbidity$ResultMeasure.MeasureUnitCode)
unique(data_turbidity$DetectionQuantitationLimitMeasure.MeasureUnitCode)

```


```{r}
#magnesium

unique(data$CharacteristicName)

magnesium_params<-c("Magnesium") #only values for magnesium
data_magnesium<-data[data$CharacteristicName%in%magnesium_params,] #want to match all records to the vector we created above which have Calcium
data_magnesium$CharacteristicName<-"magnesium"  #rename everything in the characteristics column as calcium

unique(data_magnesium$ResultSampleFractionText) #keep only dissolved
data_magnesium<-data_magnesium %>% filter(ResultSampleFractionText == "Dissolved")

#checking and filtering out NA's
unique(data_magnesium$ResultMeasure.MeasureUnitCode) #checked units
temp<-data_magnesium %>% filter(is.na(ResultMeasure.MeasureUnitCode)) #had 521 - not filtering out in this case - check with NOAH
#data_magnesium<-data_magnesium %>% filter(!is.na(ResultMeasure.MeasureUnitCode)) #filtered out NA's

###create dataset to check for non numeric objects in dataset
temp<-data_magnesium %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in the results # 1332 non numeric values
data_magnesium$ResultDetectionConditionText[which(data_magnesium$ResultMeasureValue == "< 3")] <- "Not Detected"
data_magnesium<-data_magnesium %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA  -- CHECK WITH NOAH
unique(temp$ResultMeasureValue)


###convert ppm to mg/l for obvservations ##1ppm = 1mg/l
#data_magnesium$ResultMeasureValue[which(data_magnesium$ResultMeasure.MeasureUnitCode == "in")] <- data_magnesium$ResultMeasureValue[which(data_magnesium$ResultMeasure.MeasureUnitCode == "in")] * 1

#data_magnesium[(!is.na(data_magnesium$DetectionQuantitationLimitMeasure.MeasureUnitCode) & data_magnesium$ResultMeasure.MeasureUnitCode != data_magnesium$DetectionQuantitationLimitMeasure.MeasureUnitCode),] #checks to see if detection limit units same as obvs units

#convert ppm to mg/l for detectionlimits
#data_magnesium$DetectionQuantitationLimitMeasure.MeasureValue[which(data_magnesium$ResultMeasure.MeasureUnitCode == "in")] <- data_magnesium$DetectionQuantitationLimitMeasure.MeasureValue[which(data_magnesium$ResultMeasure.MeasureUnitCode == "in")] * 1


####convert mg/l to ug/l for values

data_magnesium$ResultMeasureValue[which(data_magnesium$ResultMeasureValue == "mg/l")] <-
  data_magnesium$ResultMeasureValue[which(data_magnesium$ResultMeasureValue == "mg/l")] *1000

#convert mg/l to ug/l for detection limits

data_magnesium$DetectionQuantitationLimitMeasure.MeasureValue[which(data_magnesium$DetectionQuantitationLimitMeasure.MeasureValue == "mg/l")]<-
data_magnesium$DetectionQuantitationLimitMeasure.MeasureValue[which(data_magnesium$DetectionQuantitationLimitMeasure.MeasureValue == "mg/l")] *1000

#then change all the units to ug/l

data_magnesium$ResultMeasure.MeasureUnitCode<-"ug/l" #for values
data_magnesium$DetectionQuantitationLimitMeasure.MeasureUnitCode<-"ug/l"  #for detection limit

#check to see if it worked
unique(data_magnesium$ResultMeasure.MeasureUnitCode)
unique(data_magnesium$DetectionQuantitationLimitMeasure.MeasureUnitCode)

```


```{r}
#mercury

unique(data$CharacteristicName)

mercury_params<-c("Mercury") #only values for mercury
data_mercury<-data[data$CharacteristicName%in%mercury_params,] #want to match all records to the vector we created above which have Calcium
data_mercury$CharacteristicName<-"mercury"  #rename everything in the characteristics column as calcium

unique(data_mercury$ResultSampleFractionText) #combine total and recoverable
data_mercury$ResultSampleFractionText[which(data_mercury$ResultSampleFractionText == "Recoverable")] <- "Total" #combine total and recoverable
unique(data_mercury$ResultSampleFractionText)


#checking and filtering out NA's
unique(data_mercury$ResultMeasure.MeasureUnitCode) #checked units
temp<-data_mercury %>% filter(is.na(ResultMeasure.MeasureUnitCode)) #had 521 - not filtering out in this case - check with NOAH
#data_mercury<-data_mercury %>% filter(!is.na(ResultMeasure.MeasureUnitCode)) #filtered out NA's

###create dataset to check for non numeric objects in dataset
temp<-data_mercury %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in the results # 1332 non numeric values
data_mercury$ResultDetectionConditionText[which(data_mercury$ResultMeasureValue == "< 3")] <- "Not Detected"
data_mercury<-data_mercury %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA  -- CHECK WITH NOAH
unique(temp$ResultMeasureValue)


###convert ppm to mg/l for obvservations ##1ppm = 1mg/l
#data_mercury$ResultMeasureValue[which(data_mercury$ResultMeasure.MeasureUnitCode == "in")] <- data_mercury$ResultMeasureValue[which(data_mercury$ResultMeasure.MeasureUnitCode == "in")] * 1

#data_mercury[(!is.na(data_mercury$DetectionQuantitationLimitMeasure.MeasureUnitCode) & data_mercury$ResultMeasure.MeasureUnitCode != data_mercury$DetectionQuantitationLimitMeasure.MeasureUnitCode),] #checks to see if detection limit units same as obvs units

#convert ppm to mg/l for detectionlimits
#data_mercury$DetectionQuantitationLimitMeasure.MeasureValue[which(data_mercury$ResultMeasure.MeasureUnitCode == "in")] <- data_mercury$DetectionQuantitationLimitMeasure.MeasureValue[which(data_mercury$ResultMeasure.MeasureUnitCode == "in")] * 1


####convert mg/l to ug/l for values

data_mercury$ResultMeasureValue[which(data_mercury$ResultMeasureValue == "mg/l")] <-
  data_mercury$ResultMeasureValue[which(data_mercury$ResultMeasureValue == "mg/l")] *1000

#convert mg/l to ug/l for detection limits

data_mercury$DetectionQuantitationLimitMeasure.MeasureValue[which(data_mercury$DetectionQuantitationLimitMeasure.MeasureValue == "mg/l")]<-
data_mercury$DetectionQuantitationLimitMeasure.MeasureValue[which(data_mercury$DetectionQuantitationLimitMeasure.MeasureValue == "mg/l")] *1000

#then change all the units to ug/l

data_mercury$ResultMeasure.MeasureUnitCode<-"ug/l" #for values
data_mercury$DetectionQuantitationLimitMeasure.MeasureUnitCode<-"ug/l"  #for detection limit

#check to see if it worked
unique(data_mercury$ResultMeasure.MeasureUnitCode)
unique(data_mercury$DetectionQuantitationLimitMeasure.MeasureUnitCode)

```

```{r}
###DIP (dissolved inorganic phosphorus)

unique(data$CharacteristicName)

DIP_params<-c("Phosphate-phosphorus as P" , "Orthophosphate as P", "Phosphate-phosphorus", "Orthophosphate") #only values for DIP
data_DIP<-data[data$CharacteristicName%in%DIP_params,] #want to match all records to the vector we created above which have DIP
unique(data_DIP$ResultSampleFractionText)
temp<-data_DIP %>% filter(is.na(ResultSampleFractionText))
unique(temp$CharacteristicName) #this characteristic name is typically associated with dissolved 
fractionkeep<-c("Dissolved", "Filterable")
data_DIP<-data_DIP[which(data_DIP$ResultSampleFractionText %in% fractionkeep | is.na(data_DIP$ResultSampleFractionText)),]
unique(data_DIP$ResultSampleFractionText)


###create dataset to check for non numeric objects in dataset
temp<-data_DIP %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values - if NA's not losing any other data - can change
data_DIP<-data_DIP %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA
temp<-data_DIP %>% filter(CharacteristicName == "Orthophosphate")
unique(temp$ResultMeasure.MeasureUnitCode) #checked units
temp<-data_DIP[which(!is.na(data_DIP$DetectionQuantitationLimitMeasure.MeasureUnitCode) & data_DIP$ResultMeasure.MeasureUnitCode != data_DIP$DetectionQuantitationLimitMeasure.MeasureUnitCode),] #checks to see if detection limit units same as obvs units
temp<-data_DIP %>% filter(CharacteristicName == "Orthophosphate") %>% filter(is.na(ResultMeasure.MeasureUnitCode)) %>% filter(!is.na(ResultMeasureValue))


temp<-data_DIP %>% filter(CharacteristicName == "Orthophosphate")
unique(temp$ResultMeasure.MeasureUnitCode)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)
#convert orthophosphate mg/l as PO4 to ug/L
data_DIP<-resultconvert(dat = data_DIP, variable = "Orthophosphate", unit = "mg/l asPO4", out_unit = "ug/L_converted", conv_factor = 326.1)
data_DIP<-detectconvert(dat = data_DIP, variable = "Orthophosphate", unit = "mg/l asPO4", out_unit = "ug/L_converted", conv_factor = 326.1)

#convert orthophosphate mg/l as P to ug/L

data_DIP<-resultconvert(dat = data_DIP, variable = "Orthophosphate", unit = "mg/l as P", out_unit = "ug/L_converted", conv_factor = 1000)
data_DIP<-detectconvert(dat = data_DIP, variable = "Orthophosphate", unit = "mg/l as P", out_unit = "ug/L_converted", conv_factor = 1000)


#convert orthophosphate mg/l to ug/L #assuming it is PO4 even though it doesnt mention - we noticed it's dissolved - we;re assumming

data_DIP<-resultconvert(dat = data_DIP, variable = "Orthophosphate", unit = "mg/l", out_unit = "ug/L_converted", conv_factor = 326.1)
data_DIP<-detectconvert(dat = data_DIP, variable = "Orthophosphate", unit = "mg/l", out_unit = "ug/L_converted", conv_factor = 326.1)


#convert orthophosphate ug/l as P to ug/L # only for detection limit

data_DIP<-detectconvert(dat = data_DIP, variable = "Orthophosphate", unit = "ug/L as P", out_unit = "ug/L_converted", conv_factor = 1)


temp<-data_DIP %>% filter(CharacteristicName == "Orthophosphate")
unique(temp$ResultMeasure.MeasureUnitCode)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)

## we are finished here dealing with orthophosphate - now we're going to process the other P items

#now working with phosphate - phosphorus

temp<-data_DIP %>% filter(CharacteristicName == "Phosphate-phosphorus")  #phosphate - phosphorus means phosphate as P
unique(temp$ResultMeasure.MeasureUnitCode)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#converting mg/l to ug/l for phosphate - phosphorus # we dont need to do 326.1 conversion - it's already in P.  IF its po4 we do other conversion

data_DIP<-resultconvert(dat = data_DIP, variable = "Phosphate-phosphorus", unit = "mg/l", out_unit = "ug/L_converted", conv_factor = 1000)
data_DIP<-detectconvert(dat = data_DIP, variable = "Phosphate-phosphorus", unit = "mg/l", out_unit = "ug/L_converted", conv_factor = 1000)

#check to make sure it converted

temp<-data_DIP %>% filter(CharacteristicName == "Phosphate-phosphorus")  #phosphate - phosphorus means phosphate as P
unique(temp$ResultMeasure.MeasureUnitCode)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)


## working with "Orthophosphate as P"


temp<-data_DIP %>% filter(CharacteristicName == "Orthophosphate as P") 
unique(temp$ResultMeasure.MeasureUnitCode)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)


data_DIP<-resultconvert(dat = data_DIP, variable = "Orthophosphate as P", unit = "mg/l", out_unit = "ug/L_converted", conv_factor = 1000)
data_DIP<-detectconvert(dat = data_DIP, variable = "Orthophosphate as P", unit = "mg/l", out_unit = "ug/L_converted", conv_factor = 1000)

# check

temp<-data_DIP %>% filter(CharacteristicName == "Orthophosphate as P") 
unique(temp$ResultMeasure.MeasureUnitCode)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)

## working with "Phosphate-phosphorus as P"

temp<-data_DIP %>% filter(CharacteristicName == "Phosphate-phosphorus as P") 
unique(temp$ResultMeasure.MeasureUnitCode)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#converting mg/l to ug/l
data_DIP<-resultconvert(dat = data_DIP, variable = "Phosphate-phosphorus as P", unit = "mg/l", out_unit = "ug/L_converted", conv_factor = 1000)
data_DIP<-detectconvert(dat = data_DIP, variable = "Phosphate-phosphorus as P", unit = "mg/l", out_unit = "ug/L_converted", conv_factor = 1000)

#here we're only updating it to ug/l converted - already in P format and in ug/l

data_DIP<-resultconvert(dat = data_DIP, variable = "Phosphate-phosphorus as P", unit = "ug/l", out_unit = "ug/L_converted", conv_factor = 1)


# check
temp<-data_DIP %>% filter(CharacteristicName == "Phosphate-phosphorus as P") 
unique(temp$ResultMeasure.MeasureUnitCode)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#final check on entire data set
###
unique(data_DIP$ResultMeasure.MeasureUnitCode)
unique(data_DIP$DetectionQuantitationLimitMeasure.MeasureUnitCode)
unique(data_DIP$CharacteristicName)

#rewrite all to LAGOS standard nomenclature #use 41 variable spreadsheet column A

data_DIP$CharacteristicName<- "Phosphorus, soluable reactive orthophosphate"
#we used converted for our check - changing to ug/L now cuz that's how it is in LAGOS dataset
data_DIP$ResultMeasure.MeasureUnitCode[which(data_DIP$ResultMeasure.MeasureUnitCode == "ug/L_converted")] <- "ug/L"
data_DIP$DetectionQuantitationLimitMeasure.MeasureUnitCode[which(data_DIP$DetectionQuantitationLimitMeasure.MeasureUnitCode == "ug/L_converted")] <- "ug/L"

#check to see if everything changed

unique(data_DIP$ResultMeasure.MeasureUnitCode)
unique(data_DIP$DetectionQuantitationLimitMeasure.MeasureUnitCode)
unique(data_DIP$CharacteristicName)

#COMPLETED
  
```

```{r}
#total phosphorus


unique(data$CharacteristicName)

TP_params<-c("Phosphorus" , "Total Phosphorus, mixed forms") #only values for total phosphorus
data_TP<-data[data$CharacteristicName%in%TP_params,] #want to match all records to the vector we created above which have TP
unique(data_TP$ResultSampleFractionText)
temp<-data_TP %>% filter(is.na(ResultSampleFractionText))
fractionkeep<-c("Total", "Unfiltered")
data_TP<-data_TP[which(data_TP$ResultSampleFractionText %in% fractionkeep | is.na(data_TP$ResultSampleFractionText)),] #keeping if it's ones we chose or NA
unique(data_TP$ResultSampleFractionText)


###create dataset to check for non numeric objects in dataset
temp<-data_TP %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values - if NA's not losing any other data - can change
data_TP<-data_TP %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA
temp<-data_TP %>% filter(CharacteristicName == "Phosphorus") #filtered for just P to look at unique values after
unique(temp$ResultMeasure.MeasureUnitCode) #checked units

temp<-data_TP[which(!is.na(data_TP$DetectionQuantitationLimitMeasure.MeasureUnitCode) & data_TP$ResultMeasure.MeasureUnitCode != data_TP$DetectionQuantitationLimitMeasure.MeasureUnitCode),] #checks to see if detection limit units same as obvs units

temp<-data_TP %>% filter(CharacteristicName == "Phosphorus") %>% filter(is.na(ResultMeasure.MeasureUnitCode)) %>% filter(!is.na(ResultMeasureValue))


temp<-data_TP %>% filter(CharacteristicName == "Phosphorus")
unique(temp$ResultMeasure.MeasureUnitCode)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#convert Phosphorus mg/l PO4 to mg/L
data_TP<-resultconvert(dat = data_TP, variable = "Phosphorus", unit = "mg/l PO4", out_unit = "mg/L_converted", conv_factor = .33)
#data_TP<-detectconvert(dat = data_TP, variable = "Phosphorus", unit = "mg/l asPO4", out_unit = "ug/L_converted", conv_factor = 326.1) #don't need

#convert Phosphorus ug/l to mg/L

data_TP<-resultconvert(dat = data_TP, variable = "Phosphorus", unit = "ug/l", out_unit = "mg/L_converted", conv_factor = 0.001)
#data_TP<-detectconvert(dat = data_TP, variable = "Phosphorus", unit = "mg/l as P", out_unit = "ug/L_converted", conv_factor = 1000) #don't need


#convert Phosphorus mg/l to mg/L_converted, and mg/l as P to mg/L converted for resultsvalue and detection limits

data_TP<-resultconvert(dat = data_TP, variable = "Phosphorus", unit = "mg/l", out_unit = "mg/L_converted", conv_factor = 1)
data_TP<-resultconvert(dat = data_TP, variable = "Phosphorus", unit = "mg/l as P", out_unit = "mg/L_converted", conv_factor = 1)
data_TP<-detectconvert(dat = data_TP, variable = "Phosphorus", unit = "mg/l", out_unit = "mg/L_converted", conv_factor = 1)
data_TP<-detectconvert(dat = data_TP, variable = "Phosphorus", unit = "mg/l as P", out_unit = "mg/L_converted", conv_factor = 1)



temp<-data_TP %>% filter(CharacteristicName == "Phosphorus")
unique(temp$ResultMeasure.MeasureUnitCode)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)

############ we are finished here dealing with Phosphorus - now we're going to process Total phosphorus, mixed forms#######################


temp<-data_TP %>% filter(CharacteristicName == "Total Phosphorus, mixed forms") #filtered for just Total Phosphorus, mixed forms to look at unique values 
unique(temp$ResultMeasure.MeasureUnitCode) #checked units

temp<-data_TP[which(!is.na(data_TP$DetectionQuantitationLimitMeasure.MeasureUnitCode) & data_TP$ResultMeasure.MeasureUnitCode != data_TP$DetectionQuantitationLimitMeasure.MeasureUnitCode),] #checks to see if detection limit units same as obvs units - should be 0 

temp<-data_TP %>% filter(CharacteristicName == "Total Phosphorus, mixed forms") %>% filter(is.na(ResultMeasure.MeasureUnitCode)) %>% filter(!is.na(ResultMeasureValue))


temp<-data_TP %>% filter(CharacteristicName == "Total Phosphorus, mixed forms")
unique(temp$ResultMeasure.MeasureUnitCode)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#convert Total Phosphorus, mixed forms mg/l PO4 to mg/L
#data_TP<-resultconvert(dat = data_TP, variable = "Total Phosphorus, mixed forms", unit = "mg/l PO4", out_unit = "mg/L_converted", conv_factor = .33)
#data_TP<-detectconvert(dat = data_TP, variable = "Total Phosphorus, mixed forms", unit = "mg/l asPO4", out_unit = "ug/L_converted", conv_factor = 326.1) #don't need

#convert Total Phosphorus, mixed forms ug/l to mg/L

#data_TP<-resultconvert(dat = data_TP, variable = "Total Phosphorus, mixed forms", unit = "ug/l", out_unit = "mg/L_converted", conv_factor = 0.001)
#data_TP<-detectconvert(dat = data_TP, variable = "Total Phosphorus, mixed forms", unit = "mg/l as P", out_unit = "ug/L_converted", conv_factor = 1000) #don't need


#convert Total Phosphorus, mixed forms mg/l to mg/L_converted for resultsvalue and detection limits

data_TP<-resultconvert(dat = data_TP, variable = "Total Phosphorus, mixed forms", unit = "mg/l", out_unit = "mg/L_converted", conv_factor = 1)
data_TP<-detectconvert(dat = data_TP, variable = "Total Phosphorus, mixed forms", unit = "mg/l", out_unit = "mg/L_converted", conv_factor = 1)



temp<-data_TP %>% filter(CharacteristicName == "Total Phosphorus, mixed forms")
unique(temp$ResultMeasure.MeasureUnitCode)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#complete

```


```{r}
#TKN

unique(data$CharacteristicName)

TKN_params<-c("Kjeldahl nitrogen" , "Total Kjeldahl nitrogen (Organic N & NH3)") #only values for TKN
data_TKN<-data[data$CharacteristicName%in%TKN_params,] #want to match all records to the vector we created above which have TKN
unique(data_TKN$ResultSampleFractionText)
temp<-data_TKN %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep
fractionkeep<-c("Total", "Unfiltered")
data_TKN<-data_TKN[which(data_TKN$ResultSampleFractionText %in% fractionkeep | is.na(data_TKN$ResultSampleFractionText)),] #keeping if it's ones we chose or NA
unique(data_TKN$ResultSampleFractionText)


###create dataset to check for non numeric objects in dataset
temp<-data_TKN %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change
data_TKN<-data_TKN %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_TKN$ResultMeasure.MeasureUnitCode) #checked units
temp<-data_TKN[which(!is.na(data_TKN$DetectionQuantitationLimitMeasure.MeasureUnitCode) & data_TKN$ResultMeasure.MeasureUnitCode != data_TKN$DetectionQuantitationLimitMeasure.MeasureUnitCode),] #checks to see if detection limit units same as obvs units

#WORKING WITH Kjeldahl nitrogen

temp<-data_TKN %>% filter(CharacteristicName == "Kjeldahl nitrogen") %>% filter(is.na(ResultMeasure.MeasureUnitCode)) %>% filter(!is.na(ResultMeasureValue))


temp<-data_TKN %>% filter(CharacteristicName == "Kjeldahl nitrogen")
unique(temp$ResultMeasure.MeasureUnitCode)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#We have mg/l and mg/l as N - Need to make conversion for both into ug/L as N

data_TKN<-resultconvert(dat = data_TKN, variable = "Kjeldahl nitrogen", unit = "mg/l", out_unit = "ug/l_converted", conv_factor = 1000)
data_TKN<-detectconvert(dat = data_TKN, variable = "Kjeldahl nitrogen", unit = "mg/l", out_unit = "ug/l_converted", conv_factor = 1000)

data_TKN<-resultconvert(dat = data_TKN, variable = "Kjeldahl nitrogen", unit = "mg/l as N", out_unit = "ug/l_converted", conv_factor = 1000)
data_TKN<-detectconvert(dat = data_TKN, variable = "Kjeldahl nitrogen", unit = "mg/l as N", out_unit = "ug/l_converted", conv_factor = 1000)

#check to see everything converted 
temp<-data_TKN %>% filter(CharacteristicName == "Kjeldahl nitrogen")
unique(temp$ResultMeasure.MeasureUnitCode)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#WORKING WITH "Total Kjeldahl nitrogen (Organic N & NH3)"

temp<-data_TKN %>% filter(CharacteristicName == "Total Kjeldahl nitrogen (Organic N & NH3)")
unique(temp$ResultMeasure.MeasureUnitCode)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#need to convert mg/l to ug/l

data_TKN<-resultconvert(dat = data_TKN, variable = "Total Kjeldahl nitrogen (Organic N & NH3)", unit = "mg/l", out_unit = "ug/l_converted", conv_factor = 1000)
data_TKN<-detectconvert(dat = data_TKN, variable = "Total Kjeldahl nitrogen (Organic N & NH3)", unit = "mg/l", out_unit = "ug/l_converted", conv_factor = 1000)

#check to see if conversion worked

temp<-data_TKN %>% filter(CharacteristicName == "Total Kjeldahl nitrogen (Organic N & NH3)")
unique(temp$ResultMeasure.MeasureUnitCode)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#COMPLETED


```


```{r}
#Total Nitrogen

unique(data$CharacteristicName)

TN_params<-c("Nitrogen", "Nitrogen, mixed forms (NH3), (NH4), organic, (NO2) and (NO3)") #only values for TN
data_TN<-data[data$CharacteristicName%in%TN_params,] #want to match all records to the vector we created above which have TP
unique(data_TN$ResultSampleFractionText)
temp<-data_TN %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep
fractionkeep<-c("Total")
data_TN<-data_TN[which(data_TN$ResultSampleFractionText %in% fractionkeep | is.na(data_TN$ResultSampleFractionText)),] #keeping if it's ones we chose or NA
unique(data_TN$ResultSampleFractionText)

temp<-data_TN %>% filter(CharacteristicName == "Nitrogen, mixed forms (NH3), (NH4), organic, (NO2) and (NO3)")
unique(temp$USGSPCode)
temp<-data_TN %>% filter(CharacteristicName == "Nitrogen, mixed forms (NH3), (NH4), organic, (NO2) and (NO3)") %>% filter(is.na(USGSPCode))
unique(temp$ResultAnalyticalMethod.MethodIdentifier)
unique(data_TN$ResultMeasure.MeasureUnitCode) # will need to convert NO3 to N

###create dataset to check for non numeric objects in dataset
temp<-data_TN %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change
data_TN<-data_TN %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_TN$ResultMeasure.MeasureUnitCode) #checked units
temp<-data_TN[which(!is.na(data_TN$DetectionQuantitationLimitMeasure.MeasureUnitCode) & data_TN$ResultMeasure.MeasureUnitCode != data_TN$DetectionQuantitationLimitMeasure.MeasureUnitCode),] #checks to see if detection limit units same as obvs units


#WORKING WITH "Nitrogen, mixed forms (NH3), (NH4), organic, (NO2) and (NO3)" - convert mg/l NO3 to ug/l N = *0.2259*1000

data_TN<-resultconvert(dat = data_TN, variable = "Nitrogen, mixed forms (NH3), (NH4), organic, (NO2) and (NO3)", unit = "mg/l NO3", out_unit = "ug/l_converted", conv_factor = 0.2259*1000)

data_TN<-detectconvert(dat = data_TN, variable = "Nitrogen, mixed forms (NH3), (NH4), organic, (NO2) and (NO3)", unit = "mg/l NO3", out_unit = "ug/l_converted", conv_factor = 0.2259*1000)


temp<-data_TN %>% filter(CharacteristicName == "Nitrogen, mixed forms (NH3), (NH4), organic, (NO2) and (NO3)")
unique(temp$ResultMeasure.MeasureUnitCode)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)


#WORKING WITH "Nitrogen" 

temp<-data_TN %>% filter(CharacteristicName == "Nitrogen")
unique(temp$ResultMeasure.MeasureUnitCode) #convert mg/l to ug/l
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode) - #all NA's - don't need to convert

  
data_TN<-resultconvert(dat = data_TN, variable = "Nitrogen", unit = "mg/l", out_unit = "ug/l_converted", conv_factor = 1000)

temp<-data_TN %>% filter(CharacteristicName == "Nitrogen")
unique(temp$ResultMeasure.MeasureUnitCode) 


#Completed
```



```{r}

#DIN

unique(data$CharacteristicName)

DIN_params<-c("Inorganic nitrogen (nitrate and nitrite)", "Nitrate
", "Nitrate + Nitrite", "Inorganic nitrogen (nitrate and nitrite) as N") #only values for DIN
data_DIN<-data[data$CharacteristicName%in%DIN_params,] #want to match all records to the vector we created above which have DIN
unique(data_DIN$ResultSampleFractionText)

temp<-data_DIN %>% filter(ResultSampleFractionText == "Total" | CharacteristicName == "Unfiltered") #it's all inorganic - checked to see if there total, but there isnt any
unique(temp$CharacteristicName)

#working with dissolved

temp<-data_DIN %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep
fractionkeep<-c("Dissolved")
data_DIN<-data_DIN[which(data_DIN$ResultSampleFractionText %in% fractionkeep | is.na(data_DIN$ResultSampleFractionText)),] #keeping if it's ones we chose or NA
unique(data_DIN$ResultSampleFractionText)

unique(data_DIN$ResultMeasure.MeasureUnitCode) #check units
temp<-data_DIN %>% filter(is.na(ResultMeasure.MeasureUnitCode)) #
unique(temp$ResultMeasureValue)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)

temp<-data_DIN %>% filter(CharacteristicName == "Nitrogen, mixed forms (NH3), (NH4), organic, (NO2) and (NO3)") #total dissolved nitrogen not lagos var
unique(temp$USGSPCode) #got 602 and 62854 - they're the same - and we don't want either - moved to total

```




```{r}
#chloride

unique(data$CharacteristicName)

#cleaning dataset to keep samplefraction we want, checking for NA's in sample fraction text

Cl_params<-c("Chloride") #only values for Cl
data_Cl<-data[data$CharacteristicName%in%Cl_params,] #want to match all records to the vector we created above which have Cl
unique(data_Cl$ResultSampleFractionText) #there is dissolved and total - we will only keep dissolved
temp<-data_Cl %>% filter(is.na(ResultSampleFractionText)) #to check if there are NA's in sample fraction type 
fractionkeep<-c("Dissolved")
data_Cl<-data_Cl[which(data_Cl$ResultSampleFractionText %in% fractionkeep | is.na(data_Cl$ResultSampleFractionText)),] #keeping if it's ones we chose or NA
unique(data_Cl$ResultSampleFractionText)

#checks for non numeric values in results measures value - if NA's - manually checking to see that we're not losing other key data -> if met - changing to numeric can change

temp<-data_Cl %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values - if NA's not losing any other data (cuz already NA's)
#found 19 - all non detects - will keep
data_Cl<-data_Cl %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

#check units for observations and detection limits - see if they match

unique(data_Cl$ResultMeasure.MeasureUnitCode) #checked units
temp<-data_Cl[which(!is.na(data_Cl$DetectionQuantitationLimitMeasure.MeasureUnitCode) & data_Cl$ResultMeasure.MeasureUnitCode != data_Cl$DetectionQuantitationLimitMeasure.MeasureUnitCode),] #checks to see if detection limit units same as obvs units - came out as 0 - all match


#units already in mg/l - don't need to do any conversion - COMPLETE
```


```{r}
#conductivity

unique(data$CharacteristicName)

#cleaning dataset to keep samplefraction we want, checking for NA's in sample fraction text

CO_params<-c("Conductivity") #only values for Conductivity
data_CO<-data[data$CharacteristicName%in%CO_params,] #want to match all records to the vector we created above which have CO
unique(data_CO$ResultSampleFractionText) #there is dissolved and total - we will only keep dissolved
temp<-data_CO %>% filter(is.na(ResultSampleFractionText)) #to check if there are NA's in sample fraction type - there are 6
unique(temp$ResultSampleFractionText)
fractionkeep<-c("Dissolved")
data_Cl<-data_Cl[which(data_Cl$ResultSampleFractionText %in% fractionkeep | is.na(data_Cl$ResultSampleFractionText)),] #keeping if it's ones we chose or NA
unique(data_Cl$ResultSampleFractionText)

#comeback to

```

```{r}
#ammonia/ammonium - falls in a DIN var - filtered = dissolved

NH4_params<-c("Ammonia-nitrogen", "Ammonia and ammonium", "Ammonia", "Ammonia-nitrogen as N") #only values for Ammonia
data_NH4<-data[data$CharacteristicName%in%NH4_params,] #want to match all records to the vector we created above which have Ammonia
unique(data_NH4$ResultSampleFractionText)

temp<-data_NH4 %>% filter(is.na(ResultSampleFractionText)) #to check if there are NA's in sample fraction type 
unique(temp$ResultSampleFractionText)
fractionkeep<-c("Dissolved")
data_NH4<-data_NH4[which(data_NH4$ResultSampleFractionText %in% fractionkeep | is.na(data_NH4$ResultSampleFractionText)),] #keeping if it's ones we chose or NA
unique(data_NH4$ResultSampleFractionText)

unique(data_NH4$ResultMeasure.MeasureUnitCode) #check units
temp<-data_NH4 %>% filter(is.na(ResultMeasure.MeasureUnitCode)) # missing resultmeasurevalues but has detection limits
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)
unique(temp$ResultMeasureValue)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)


#finish up

```

```{r}
#carbon

DOC_params<-c("Organic carbon", "Carbon") #only values for carbon
data_DOC<-data[data$CharacteristicName%in%DOC_params,] #want to match all records to the vector we created above which have Ammonia
unique(data_DOC$ResultSampleFractionText) #only keeping dissolved

temp<-data_DOC %>% filter(is.na(ResultSampleFractionText)) #to check if there are NA's in sample fraction type - we don't need in this case cuz no NAs
unique(temp$ResultSampleFractionText)
fractionkeep<-c("Dissolved")
data_DOC<-data_DOC[which(data_DOC$ResultSampleFractionText %in% fractionkeep | is.na(data_DOC$ResultSampleFractionText)),] #keeping if it's ones we chose or NA
unique(data_DOC$ResultSampleFractionText)


unique(data_DOC$ResultMeasure.MeasureUnitCode) #check units

temp<-data_DOC %>% filter(CharacteristicName == "Carbon") #carbon is ambigous - is it organic or inorganic - checked - carbon got dropped when we did samplefreaction text filter - kept dissolved - left with only organic
unique(data_DOC$CharacteristicName)

temp<-data_DOC %>% filter(is.na(ResultMeasure.MeasureUnitCode)) # missing resultmeasurevalues but has detection limits - keep
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)
unique(temp$ResultMeasureValue)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)


#finish up

```

```{r}
#chlorophyll

Chl_params<-c("Chlorophyll a, corrected for pheophytin", "Chlorophyll a, uncorrected for pheophytin", "Chlorophyll a", "Chlorophyll") #only values for chloropyll
data_Chl<-data[data$CharacteristicName%in%Chl_params,] #want to match all records to the vector we created above which have Chl
unique(data_Chl$ResultSampleFractionText) #checked but DOES NOT MATTER for Chl

#temp<-data_DOC %>% filter(is.na(ResultSampleFractionText)) #to check if there are NA's in sample fraction type - we don't need in this case cuz no NAs
#unique(temp$ResultSampleFractionText)
#fractionkeep<-c("Dissolved")
#data_DOC<-data_DOC[which(data_DOC$ResultSampleFractionText %in% fractionkeep | is.na(data_DOC$ResultSampleFractionText)),] #keeping if it's ones we chose or NA
#unique(data_DOC$ResultSampleFractionText)


unique(data_Chl$ResultMeasure.MeasureUnitCode) #check units

temp<-data_Chl %>% filter(CharacteristicName == "Chlorophyll") #Chl is ambigous - check with USGSPcode to find out what it is - it is chla - keep
temp<-data_Chl %>% filter(CharacteristicName == "Chlorophyll a")
unique(temp$USGSPCode)
temp<-temp %>% filter(is.na(USGSPCode))
unique(temp$ResultAnalyticalMethod.MethodIdentifier) #checked result analytical method. method identifier - googled what 10200-H means

temp<-data_DOC %>% filter(is.na(ResultMeasure.MeasureUnitCode)) # missing resultmeasurevalues but has detection limits - keep
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)
unique(temp$ResultMeasureValue)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)
 # can process them as is - will deal with corrected and uncorrected flags later

```

```{r}
Ecoli_params<-c("Escherichia coli") #only values for carbon
data_Ecoli<-data[data$CharacteristicName%in%Ecoli_params,] #want to match all records to the vector we created above which have Ammonia
unique(data_Ecoli$ResultSampleFractionText) #only keeping dissolved

#temp<-data_DOC %>% filter(is.na(ResultSampleFractionText)) #to check if there are NA's in sample fraction type - we don't need in this case cuz no NAs
#unique(temp$ResultSampleFractionText)
#fractionkeep<-c("Dissolved")
#data_DOC<-data_DOC[which(data_DOC$ResultSampleFractionText %in% fractionkeep | is.na(data_DOC$ResultSampleFractionText)),] #keeping if it's ones we chose or NA
#unique(data_DOC$ResultSampleFractionText)


unique(data_Ecoli$ResultMeasure.MeasureUnitCode) #check units

temp<-data_DOC %>% filter(CharacteristicName == "Carbon") #carbon is ambigous - is it organic or inorganic - checked - carbon got dropped when we did samplefreaction text filter - kept dissolved - left with only organic
unique(data_DOC$CharacteristicName)

temp<-data_Ecoli %>% filter(is.na(ResultMeasure.MeasureUnitCode)) # missing resultmeasurevalues but has detection limits - keep
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)
unique(temp$ResultMeasureValue)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#finish

```

```{r}
#temperature
unique(data$CharacteristicName)

temperature_params<-c("Temperature, water") #only values for temperature
data_temperature<-data[data$CharacteristicName%in%temperature_params,] #want to match all records to the vector we created above which have temperature
unique(data_temperature$ResultSampleFractionText) #temp doesn't have any sample fraction text - has NA and none (ask about none)

temp<-data_temperature %>% filter(is.na(ResultSampleFractionText)) #check the NA's in sample fraction type - 1807/27179
unique(temp$ResultSampleFractionText) #all NA's
#fractionkeep<-c("Dissolved") - don't need - no other sameple fraction texts
#data_DOC<-data_DOC[which(data_DOC$ResultSampleFractionText %in% fractionkeep | is.na(data_DOC$ResultSampleFractionText)),] #keeping if it's ones we chose or NA
#unique(data_DOC$ResultSampleFractionText)

#checks for non numeric values in results measures value - if NA's - manually checking to see that we're not losing other key data -> if met - changing to numeric 

temp<-data_temperature %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values - if NA's not losing any other data (cuz already NA's)
#found 0
data_temperature<-data_temperature %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

#check units for observations and detection limits - see if they match

unique(data_temperature$ResultMeasure.MeasureUnitCode) #checked units
unique(data_temperature$DetectionQuantitationLimitMeasure.MeasureUnitCode) # all detection limit info are NAs
temp<-data_temperature[which(!is.na(data_temperature$DetectionQuantitationLimitMeasure.MeasureUnitCode) & data_temperature$ResultMeasure.MeasureUnitCode != data_temperature$DetectionQuantitationLimitMeasure.MeasureUnitCode),] #checks to see if detection limit units same as obvs units - came out as 0 - cuz NAs

#we have units in deg C and deg F - need to convert the degree F to degree C for obvs and detection limts

data_temperature<-resultconvert_celsius(dat = data_temperature, variable = "Temperature, water", unit = "deg F", out_unit = "deg C_converted")
unique(data_temperature$ResultMeasure.MeasureUnitCode) #it worked

#don't need to convert detection limit info - doesn't exist
data_temperature<-detectconvert_celsius(dat = data_temperature, variable = "Temperature, water", unit = "deg F", out_unit = "deg C_converted")
unique(data_temperature$DetectionQuantitationLimitMeasure.MeasureUnitCode)


#convert Phosphorus mg/l to mg/L_converted, and mg/l as P to mg/L converted for resultsvalue and detection limits

data_TP<-resultconvert(dat = data_TP, variable = "Phosphorus", unit = "mg/l", out_unit = "mg/L_converted", conv_factor = 1)
data_TP<-resultconvert(dat = data_TP, variable = "Phosphorus", unit = "mg/l as P", out_unit = "mg/L_converted", conv_factor = 1)
data_TP<-detectconvert(dat = data_TP, variable = "Phosphorus", unit = "mg/l", out_unit = "mg/L_converted", conv_factor = 1)
data_TP<-detectconvert(dat = data_TP, variable = "Phosphorus", unit = "mg/l as P", out_unit = "mg/L_converted", conv_factor = 1)

```