---
title: "Datacleaningcode_VA"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
#here are functions
#for temperature

resultconvert_celsius<-function(dat, variable, unit, out_unit) {
  dat$ResultMeasureValue[which(dat$CharacteristicName == variable & dat$ResultMeasure.MeasureUnitCode == unit)] <- (dat$ResultMeasureValue[which(dat$CharacteristicName == variable & dat$ResultMeasure.MeasureUnitCode == unit)] -32)* 5/9
  
dat$ResultMeasure.MeasureUnitCode[which(dat$CharacteristicName == variable & dat$ResultMeasure.MeasureUnitCode == unit)] <- out_unit

return(dat)
  
}


detectconvert_celsius<-function(dat, variable, unit, out_unit) {
  dat$DetectionQuantitationLimitMeasure.MeasureValue[which(dat$CharacteristicName == variable & dat$DetectionQuantitationLimitMeasure.MeasureUnitCode == unit)] <- (dat$DetectionQuantitationLimitMeasure.MeasureValue[which(dat$CharacteristicName == variable & dat$DetectionQuantitationLimitMeasure.MeasureUnitCode == unit)] * -32)*5/9
  
dat$DetectionQuantitationLimitMeasure.MeasureUnitCode[which(dat$CharacteristicName == variable & dat$DetectionQuantitationLimitMeasure.MeasureUnitCode == unit)] <- out_unit

return(dat)
  
}

#for all other conversions

resultconvert<-function(dat, variable, unit, out_unit, conv_factor) {
  dat$ResultMeasureValue[which(dat$CharacteristicName == variable & dat$ResultMeasure.MeasureUnitCode == unit)] <- dat$ResultMeasureValue[which(dat$CharacteristicName == variable & dat$ResultMeasure.MeasureUnitCode == unit)] * conv_factor
  
dat$ResultMeasure.MeasureUnitCode[which(dat$CharacteristicName == variable & dat$ResultMeasure.MeasureUnitCode == unit)] <- out_unit

return(dat)
  
}


detectconvert<-function(dat, variable, unit, out_unit, conv_factor) {
  dat$DetectionQuantitationLimitMeasure.MeasureValue[which(dat$CharacteristicName == variable & dat$DetectionQuantitationLimitMeasure.MeasureUnitCode == unit)] <- dat$DetectionQuantitationLimitMeasure.MeasureValue[which(dat$CharacteristicName == variable & dat$DetectionQuantitationLimitMeasure.MeasureUnitCode == unit)] * conv_factor
  
dat$DetectionQuantitationLimitMeasure.MeasureUnitCode[which(dat$CharacteristicName == variable & dat$DetectionQuantitationLimitMeasure.MeasureUnitCode == unit)] <- out_unit

return(dat)
  
}


`%notin%` <- Negate(`%in%`)

VAdatPull<-read.csv("~/Lagos Limno/VA_alldata_1975_to_2020.csv")

names(VAdatPull)

summary(VAdatPull)

#removing data that have Y's instead of keeping data that have N's

read.csv("~/Lagos Limno/list of unique parameters to remove.csv") -> remove_params #update this


data<- VAdatPull[VAdatPull$CharacteristicName %notin% remove_params$Unique.parameters,]
data<-data %>% mutate(obs_id = seq(1, nrow(data), 1))


tdata1<-data %>% filter(!is.na(ResultDepthHeightMeasure.MeasureValue)) #identified specified depth samples


tdata2<-data %>% filter(is.na(ResultDepthHeightMeasure.MeasureValue)) %>% filter(!is.na(ActivityTopDepthHeightMeasure.MeasureValue)) #these are potential integrated samples

unique(tdata2$SampleCollectionMethod.MethodName)
method_name<-c("Ambient Water Quality Monitoring QAPP and SOP")

unique(tdata2$SampleCollectionMethod.MethodIdentifier)
method_identifier<-c("")

unique(tdata2$SampleCollectionMethod.MethodIdentifierContext)
method_context<-c("")

unique(tdata2$SampleCollectionEquipmentName)
method_equipment<-c("")

tdata2<-tdata2 %>% filter(SampleCollectionMethod.MethodName %in% method_name | 
                            SampleCollectionMethod.MethodIdentifier %in% method_identifier|
                            SampleCollectionMethod.MethodIdentifierContext %in% method_context|
                            SampleCollectionEquipmentName %in% method_equipment)  #all grab samples

tdata3<-data %>% filter(is.na(ResultDepthHeightMeasure.MeasureValue)) #identifying grab samples

unique(tdata3$SampleCollectionMethod.MethodName)
method_name<-c("Ambient Water Quality Monitoring QAPP and SOP", "Grab", "Unspecified Standard Grab Sample Procedure", "Grab sample  (dip)", "Grab sample collection")

unique(tdata3$SampleCollectionMethod.MethodIdentifier)
method_identifier<-c("000002", "NPS_GRAB", "Grab")

unique(tdata3$SampleCollectionMethod.MethodIdentifierContext)
method_context<-c("USGS parameter code 82398")

unique(tdata3$SampleCollectionEquipmentName)
method_equipment<-c("Bucket", "Open-Mouth Bottle", "Grab sample")

tdata3<-tdata3 %>% filter(SampleCollectionMethod.MethodName %in% method_name | 
                            SampleCollectionMethod.MethodIdentifier %in% method_identifier|
                            SampleCollectionMethod.MethodIdentifierContext %in% method_context|
                            SampleCollectionEquipmentName %in% method_equipment)  #all grab samples

data2<-rbind(tdata1, tdata2, tdata3)
rm(tdata1)
rm(tdata2)
rm(tdata3)

tdata4<-data %>% filter(obs_id %notin% data2$obs_id)#created object to look at all data not in datata2

unique(tdata4$CharacteristicName)
secchiparams<-c("Secchi, Horizontal Distance", "Depth, Secchi disk depth") #pulled out secchi data cuz it may not have depth data

tdata4<-tdata4 %>% filter(CharacteristicName %in% secchiparams) #filtered out only the secchi vars
data<-rbind(data2, tdata4) #combined everything back together

#will need to check for each state (the depth data)

rm(tdata4)
rm(data2)
data<-data %>% select(-obs_id)
rm(VAdatPull)
unique(data$CharacteristicName)

data<-data %>% filter(!(is.na(ResultMeasureValue) & is.na(DetectionQuantitationLimitMeasure.MeasureValue)))



#unique organizations
unique(data$OrganizationIdentifier) #19 organizations data
table(data$OrganizationFormalName) #tells us number of obvs in each organization




#looking at activity type codes
unique(data$ActivityTypeCode)
activitytype_keep<-c("Quality Control Sample-Field Replicate", "Quality Control Sample-Field Replicate", "Quality Control Sample-Field Blank", "Quality Control Sample-Equipment Blank")
activitytype_keep<-c("Quality Control Sample-Equipment Blank")
data<-data[which(data$ActivityTypeCode %notin% activitytype_keep),]
unique(data$ActivityTypeCode)

#manually checking these columns to see if these is data we keep or can drop

unique(data$SubjectTaxonomicName) #expected it to be na - to make sure nothing we need is in there
unique(data$SampleTissueAnatomyName) #also NA's - expected

unique(data$ActivityMediaSubdivisionName)
#only keeping subdivision name with surface water and NA's - dropping everything else 
data<-data %>% filter(ActivityMediaSubdivisionName == "Surface Water" | is.na(ActivityMediaSubdivisionName))
unique(data$ActivityMediaSubdivisionName)

unique(data$ResultStatusIdentifier)
unique(data$ResultValueTypeName)


unique(data$ResultDetectionConditionText)
#filtered out vars we don't need in resultsdetection condition text - did it in multistep because R doesn't handle multiple OR statements well


data<-data %>% filter(ResultDetectionConditionText != "Systematic Contamination" | is.na(ResultDetectionConditionText))

data<-data %>% filter(is.na(ResultDetectionConditionText) | ResultDetectionConditionText != "Not Reported")
unique(data$ResultDetectionConditionText)



unique(data$ResultSampleFractionText)

data<-data %>% filter(is.na(ResultSampleFractionText) | ResultSampleFractionText != "Bed Sediment")
unique(data$ResultSampleFractionText)


data<-data %>% select(-ActivityMediaName, -ActivityMediaSubdivisionName, -ActivityStartTime.Time, -ActivityStartTime.TimeZoneCode, -ActivityEndTime.Time, -ActivityEndTime.TimeZoneCode, -SampleAquifer, -HydrologicCondition, -HydrologicEvent, -SubjectTaxonomicName, -SampleTissueAnatomyName, -LaboratoryName, -AnalysisStartDate, -PreparationStartDate)
```

```{r}
#list of unique parameters
#unique(data$CharacteristicName)
#write.table(unique(data$CharacteristicName), "unique_parameters_VA.csv", row.names = FALSE)
#unique_parameters_VA<-read.csv("~/Lagos Limno/unique_parameters_VA.csv")
#data<-data[data$CharacteristicName %in% unique_parameters_VA$Unique_params,]
#unique(data$CharacteristicName)


```

```{r}

###creating new columns to preserve original pulled data

data$source_parameter <- data$CharacteristicName
data$source_value<- data$ResultMeasureValue
data$source_unit <- data$ResultMeasure.MeasureUnitCode
data$detectionlimit_legacy <- data$DetectionQuantitationLimitMeasure.MeasureValue
data$detectionlimit_unit_legacy <- data$DetectionQuantitationLimitMeasure.MeasureUnitCode

#spreadsheet for VA variables
#write.table(unique(data$CharacteristicName), "Va_vars.csv", row.names = FALSE)
```



```{r}
#secchi

unique(data$CharacteristicName)

Secchi_params<-c("Depth", "Depth, Secchi disk depth", "Secchi, Horizontal Distance") #values for secchi
data_secchi<-data[data$CharacteristicName%in%Secchi_params,]
data_secchi$CharacteristicName<-"Secchi"  #set all secchi params as secchi

data_secchi<-data[data$CharacteristicName%in%Secchi_params,] #want to match all records to the vector we created above which have TKN
unique(data_secchi$ResultSampleFractionText)
temp<-data_secchi %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep


###create dataset to check for non numeric objects in dataset
temp<-data_secchi %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change
data_secchi<-data_secchi %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_secchi$ResultMeasure.MeasureUnitCode) #checked units
temp<-data_secchi[which(!is.na(data_secchi$DetectionQuantitationLimitMeasure.MeasureUnitCode) & data_secchi$ResultMeasure.MeasureUnitCode != data_secchi$DetectionQuantitationLimitMeasure.MeasureUnitCode),] #checks to see if detection limit units same as obvs units



###convert inches to m for obvservations
data_secchi$ResultMeasureValue[which(data_secchi$ResultMeasure.MeasureUnitCode == "in")] <- data_secchi$ResultMeasureValue[which(data_secchi$ResultMeasure.MeasureUnitCode == "in")] * 0.0254

data_secchi[(!is.na(data_secchi$DetectionQuantitationLimitMeasure.MeasureUnitCode) & data_secchi$ResultMeasure.MeasureUnitCode != data_secchi$DetectionQuantitationLimitMeasure.MeasureUnitCode),] #checks to see if detection limit units same as obvs units

#convert inches to m for detectionlimits
data_secchi$DetectionQuantitationLimitMeasure.MeasureValue[which(data_secchi$ResultMeasure.MeasureUnitCode == "in")] <- data_secchi$DetectionQuantitationLimitMeasure.MeasureValue[which(data_secchi$ResultMeasure.MeasureUnitCode == "in")] * 0.0254


####convert ft to m's for values

data_secchi$ResultMeasureValue[which(data_secchi$ResultMeasureValue == "ft")] <-
  data_secchi$ResultMeasureValue[which(data_secchi$ResultMeasureValue == "ft")] * 0.3048

#convert ft to m's for detection limits

data_secchi$DetectionQuantitationLimitMeasure.MeasureValue[which(data_secchi$DetectionQuantitationLimitMeasure.MeasureValue == "ft")]<-
  data_secchi$DetectionQuantitationLimitMeasure.MeasureValue[which(data_secchi$DetectionQuantitationLimitMeasure.MeasureValue == "ft")] * 0.3048

#then change all the units to m

data_secchi$ResultMeasure.MeasureUnitCode<-"m" #for values

data_secchi$DetectionQuantitationLimitMeasure.MeasureUnitCode<-"m"  #for detection limit
#check to see if it worked
unique(data_secchi$ResultMeasure.MeasureUnitCode)
unique(data_secchi$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#done
```



```{r}
#calcium

Calcium_params<-c("Calcium") #only values for calcium
data_calcium<-data[data$CharacteristicName%in%Calcium_params,] #want to match all records to the vector we created above which have calcium
unique(data_calcium$ResultSampleFractionText)
temp<-data_calcium %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep



###create dataset to check for non numeric objects in dataset
temp<-data_calcium %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change
data_calcium<-data_calcium %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_calcium$ResultMeasure.MeasureUnitCode) #checked units
unique(data_calcium$DetectionQuantitationLimitMeasure.MeasureUnitCode)


#convert mg/l CaCO3 to mg/l Ca

data_calcium<-resultconvert(dat = data_calcium, variable = "Calcium", unit = "mg/l CaCO3", out_unit = "mg/l", conv_factor = 1/2.5)
data_calcium<-detectconvert(dat = data_calcium, variable = "Calcium", unit = "mg/l CacO3", out_unit = "mg/l", conv_factor = 1/2.5)

temp<- filter(data_calcium, ResultMeasure.MeasureUnitCode == "ueq/L") #check to see if ueq/l is for calcium or caco3 - it's for calcium

#need to convert ueq/l to meq/l (*1/000), then meq/l to mg/l (*20.04) - do this for resultconvert and detectconvert - 

data_calcium<-resultconvert(dat = data_calcium, variable = "Calcium", unit = "ueq/L", out_unit = "meq/l_converted", conv_factor = 1/1000)
data_calcium<-resultconvert(dat = data_calcium, variable = "Calcium", unit = "meq/l_converted", out_unit = "mg/l", conv_factor = 20.04)

#do the same for detect convert

data_calcium<-detectconvert(dat = data_calcium, variable = "Calcium", unit = "ueq/L", out_unit = "meq/l_converted", conv_factor = 1/1000)
data_calcium<-detectconvert(dat = data_calcium, variable = "Calcium", unit = "meq/l_converted", out_unit = "mg/l", conv_factor = 20.04)

#check to see everything converted 
temp<-data_calcium %>% filter(CharacteristicName == "Calcium")
unique(temp$ResultMeasure.MeasureUnitCode)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#COMPLETED
```
```{r}
#aluminum

Aluminum_params<-c("Aluminum") #only values for aluminum
data_aluminum<-data[data$CharacteristicName%in%Aluminum_params,] #want to match all records to the vector we created above which have calcium
unique(data_aluminum$ResultSampleFractionText)
temp<-data_aluminum %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep



###create dataset to check for non numeric objects in dataset
temp<-data_aluminum %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change
data_aluminum<-data_aluminum %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_aluminum$ResultMeasure.MeasureUnitCode) #checked units
unique(data_aluminum$DetectionQuantitationLimitMeasure.MeasureUnitCode) #checked units - all NA's - won't have to convert any detection limits
temp<-data_aluminum[which(!is.na(data_aluminum$DetectionQuantitationLimitMeasure.MeasureUnitCode) & data_aluminum$ResultMeasure.MeasureUnitCode != data_aluminum$DetectionQuantitationLimitMeasure.MeasureUnitCode),] #checks to see if detection limit units same as obvs units

#resultmeasurecode - all in ug/l which is lagos units - no conversion needed

#completed


```

```{r}
#mercury


Mercury_params<-c("Mercury") #only values for mercury
data_mercury<-data[data$CharacteristicName%in%Mercury_params,] #want to match all records to the vector we created above which have calcium
unique(data_mercury$ResultSampleFractionText)
temp<-data_mercury %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep



###create dataset to check for non numeric objects in dataset
temp<-data_mercury %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change #found 7 objects - all NA's - safe to convert
data_mercury<-data_mercury %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_mercury$ResultMeasure.MeasureUnitCode) #checked units
unique(data_mercury$DetectionQuantitationLimitMeasure.MeasureUnitCode)#checked units - same as resultmeasurevalues

#need to convert resultmeasurevalue and detection limits to ng/l - this is lagos units
#checked dataset manually - likely a recording error - only 1 ug/l value but the number is 0.2 - likely value is correct - unit wrong - change all units to ng/l
#same issue with detection limit - manually fixed detection limit unit code 


data_mercury$ResultMeasure.MeasureUnitCode <- "ng/l"
data_mercury$DetectionQuantitationLimitMeasure.MeasureUnitCode <- "ng/l"

#check to make sure they worked

unique(data_mercury$ResultMeasure.MeasureUnitCode) #checked units
unique(data_mercury$DetectionQuantitationLimitMeasure.MeasureUnitCode)#checked units - same as resultmeasurevalues


#completed

```

```{r}
#Magnesium

Magnesium_params<-c("Magnesium") #only values for magnesium
data_magnesium<-data[data$CharacteristicName%in%Magnesium_params,] #want to match all records to the vector we created above which have calcium
unique(data_magnesium$ResultSampleFractionText)
temp<-data_magnesium %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep



###create dataset to check for non numeric objects in dataset
temp<-data_magnesium %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change
data_magnesium<-data_magnesium %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_magnesium$ResultMeasure.MeasureUnitCode) #checked units
unique(data_magnesium$DetectionQuantitationLimitMeasure.MeasureUnitCode) #checked units

#need to convert ueq/l to mg/l - 2 step process - need to do this for results and detectionlimits


data_magnesium<-resultconvert(dat = data_magnesium, variable = "Magnesium", unit = "ueq/L", out_unit = "meq/l_converted", conv_factor = 1/1000)
data_magnesium<-resultconvert(dat = data_magnesium, variable = "Magnesium", unit = "meq/l_converted", out_unit = "mg/l", conv_factor = 20.04)

#do the same for detect convert

data_magnesium<-detectconvert(dat = data_magnesium, variable = "Magnesium", unit = "ueq/L", out_unit = "meq/l_converted", conv_factor = 1/1000)
data_magnesium<-detectconvert(dat = data_magnesium, variable = "Magnesium", unit = "meq/l_converted", out_unit = "mg/l", conv_factor = 20.04)

#check to see everything converted 
temp<-data_magnesium %>% filter(CharacteristicName == "Magnesium")
unique(temp$ResultMeasure.MeasureUnitCode)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#completed
```

```{r}
#selenium

Selenium_params<-c("Selenium") #only values for selenium
data_selenium<-data[data$CharacteristicName%in%Selenium_params,] #want to match all records to the vector we created above which have calcium
unique(data_selenium$ResultSampleFractionText)
temp<-data_selenium %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep



###create dataset to check for non numeric objects in dataset
temp<-data_selenium %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change # 1 NA - can change
data_selenium<-data_selenium %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_selenium$ResultMeasure.MeasureUnitCode)#checked units
unique(data_selenium$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#units matched - all ug/l - this is lagos units - no conversions needed

#completed
```

```{r}
#arsenic

Arsenic_params<-c("Arsenic") #only values for arsenic
data_arsenic<-data[data$CharacteristicName%in%Arsenic_params,] #want to match all records to the vector we created above which have calcium
unique(data_arsenic$ResultSampleFractionText)
temp<-data_arsenic %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep



###create dataset to check for non numeric objects in dataset
temp<-data_arsenic %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change #2 NA's - can change
data_arsenic<-data_arsenic %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_arsenic$ResultMeasure.MeasureUnitCode)#checked units
unique(data_arsenic$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#already in ug/l - lagos units 

#completed

```
```{r}
#atrazine

Atrazine_params<-c("Atrazine") #only values for atrazine
data_atrazine<-data[data$CharacteristicName%in%Atrazine_params,] #want to match all records to the vector we created above which have calcium
unique(data_atrazine$ResultSampleFractionText)
temp<-data_atrazine %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep



###create dataset to check for non numeric objects in dataset
temp<-data_atrazine %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change #3 NA's - can change
data_atrazine<-data_atrazine %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_atrazine$ResultMeasure.MeasureUnitCode)#checked units
unique(data_atrazine$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#both in ug/l - lagos units - no conversion needed
#completed
```

```{r}
#ecoli
unique(data$CharacteristicName)

Ecoli_params<-c("Escherichia coli") #only values for Escherichia coli
data_ecoli<-data[data$CharacteristicName%in%Ecoli_params,] #want to match all records to the vector we created above which have calcium
unique(data_ecoli$ResultSampleFractionText)
temp<-data_ecoli %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep



###create dataset to check for non numeric objects in dataset
temp<-data_ecoli %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change #1 NA - can change
data_ecoli<-data_ecoli %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_ecoli$ResultMeasure.MeasureUnitCode) #checked units
unique(data_ecoli$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#already in lagos units - MNP/100ml and cfu/100ml 

#completed
```

```{r}
#silica

Silica_params<-c("Silica") #only values for silica
data_silica<-data[data$CharacteristicName%in%Silica_params,] #want to match all records to the vector we created above which have calcium
unique(data_silica$ResultSampleFractionText)
temp<-data_silica %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep



###create dataset to check for non numeric objects in dataset
temp<-data_silica %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change
data_silica<-data_silica %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_silica$ResultMeasure.MeasureUnitCode) #checked units
unique(data_silica$DetectionQuantitationLimitMeasure.MeasureUnitCode)
temp<-data_silica[which(!is.na(data_silica$DetectionQuantitationLimitMeasure.MeasureUnitCode) & data_silica$ResultMeasure.MeasureUnitCode != data_silica$DetectionQuantitationLimitMeasure.MeasureUnitCode),] #checks to see if detection limit units same as obvs units

#lagos units for silica is mg/l - need to convert units for resultmeasurevalue from umol/L to mg/l = *0.1151


data_silica<-resultconvert(dat = data_silica, variable = "Silica", unit = "umol/L", out_unit = "mg/l", conv_factor = 0.1151)
data_silica<-detectconvert(dat = data_silica, variable = "Silica", unit = "umol/L", out_unit = "mg/l", conv_factor = 0.1151)

#check to see everything converted 
temp<-data_silica %>% filter(CharacteristicName == "Silica")
unique(temp$ResultMeasure.MeasureUnitCode)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#completed

```

```{r}
#chloride

Chloride_params<-c("Chloride") #only values for chloride
data_chloride<-data[data$CharacteristicName%in%Chloride_params,] #want to match all records to the vector we created above which have calcium
unique(data_chloride$ResultSampleFractionText)
temp<-data_chloride %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep



###create dataset to check for non numeric objects in dataset
temp<-data_chloride %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change
data_chloride<-data_chloride %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_chloride$ResultMeasure.MeasureUnitCode) #checked units
unique(data_chloride$DetectionQuantitationLimitMeasure.MeasureUnitCode)



#need to convert ueq/l to meq/l (*1/000), then meq/l to mg/l (*20.04) - do this for resultconvert and detectconvert - 

data_chloride<-resultconvert(dat = data_chloride, variable = "Chloride", unit = "ueq/L", out_unit = "meq/l_converted", conv_factor = 1/1000)
data_chloride<-resultconvert(dat = data_chloride, variable = "Chloride", unit = "meq/l_converted", out_unit = "mg/l", conv_factor = 20.04)

#do the same for detect convert

data_chloride<-detectconvert(dat = data_chloride, variable = "Chloride", unit = "ueq/L", out_unit = "meq/l_converted", conv_factor = 1/1000)
data_chloride<-detectconvert(dat = data_chloride, variable = "Chloride", unit = "meq/l_converted", out_unit = "mg/l", conv_factor = 20.04)

#check to see everything converted 
temp<-data_chloride %>% filter(CharacteristicName == "Chloride")
unique(temp$ResultMeasure.MeasureUnitCode)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)

```
```{r}
#oxygen

Oxygen_params<-c("Oxygen", "Dissolved oxygen (DO)") #only values for oxygen
data_oxygen<-data[data$CharacteristicName%in%Oxygen_params,] #want to match all records to the vector we created above which have oxygen
unique(data_oxygen$ResultSampleFractionText)
temp<-data_oxygen %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep
#both types are dissolved oxygen - convert all characteristic names to oxygen
data_oxygen$CharacteristicName<-"Oxygen"
unique(data_oxygen$CharacteristicName)



###create dataset to check for non numeric objects in dataset
temp<-data_oxygen %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change #1 NA observation - can change
data_oxygen<-data_oxygen %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_oxygen$ResultMeasure.MeasureUnitCode) #checked units
unique(data_oxygen$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#resultmeasurevalue has ppm, mg/l, and % saturation - need all in mg/l - detection limits all in mg/l - no need to change 

temp<-filter(data_oxygen, ResultMeasure.MeasureUnitCode == "% saturatn")
#1ppm = 1mg/l, and 1 DO% saturation = 0.08 mg/l

data_oxygen<-resultconvert(dat = data_oxygen, variable = "Oxygen", unit = "ppm", out_unit = "mg/l", conv_factor = 1)
data_oxygen<-resultconvert(dat = data_oxygen, variable = "Oxygen", unit = "% saturatn", out_unit = "mg/l", conv_factor = 0.08)

#check to see everything converted 
temp<-data_oxygen %>% filter(CharacteristicName == "Oxygen")
unique(temp$ResultMeasure.MeasureUnitCode)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#completed

```


```{r}
#chlorophyll

unique(data$CharacteristicName)


Chla_params<-c("Chlorophyll a, corrected for pheophytin", "Chlorophyll a", "Chlorophyll a, uncorrected for pheophytin", "Chlorophyll") #only values for Chl
data_chla<-data[data$CharacteristicName%in%Chla_params,] #want to match all records to the vector we created above which have chl
unique(data_chla$ResultSampleFractionText)
temp<-data_chla %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep



###create dataset to check for non numeric objects in dataset
temp<-data_chla %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change #2 NA's - can change
data_chla<-data_chla%>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_chla$ResultMeasure.MeasureUnitCode) #checked units
unique(data_chla$DetectionQuantitationLimitMeasure.MeasureUnitCode)
#results and detection limit both in ug/l - Lagos units - no conversions needed
#completed
```
```{r}
# pH

pH_params<-c("pH") #only values for pH
data_pH<-data[data$CharacteristicName%in%pH_params,] #want to match all records to the vector we created above which have pH
unique(data_pH$ResultSampleFractionText)
temp<-data_pH %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep



###create dataset to check for non numeric objects in dataset
temp<-data_pH %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change
data_pH<-data_pH %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_pH$ResultMeasure.MeasureUnitCode) #checked units
unique(data_pH$DetectionQuantitationLimitMeasure.MeasureUnitCode)

temp<-filter(data_pH, DetectionQuantitationLimitMeasure.MeasureUnitCode == "None")

#convert text - from std units to pH and none to pH - (for detection limits) data is correct, but mislabelled - same for resultsmeasurevalue

data_pH$DetectionQuantitationLimitMeasure.MeasureUnitCode<-"pH"
unique(data_pH$DetectionQuantitationLimitMeasure.MeasureUnitCode)

data_pH$ResultMeasure.MeasureUnitCode<-"pH"
unique(data_pH$ResultMeasure.MeasureUnitCode)

#completed
```

```{r}
#temperature

Temp_params<-c("Temperature, water") #only values for water temp
data_temp<-data[data$CharacteristicName%in%Temp_params,] #want to match all records to the vector we created above which have calcium
unique(data_temp$ResultSampleFractionText)
temp<-data_temp %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep



###create dataset to check for non numeric objects in dataset
temp<-data_temp %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change
data_temp<-data_temp %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_temp$ResultMeasure.MeasureUnitCode) #checked units
unique(data_temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#temp is in deg C - already lagos units - no need to change
#completed
```
```{r}
#sulfate
Sulfate_params<-c("Sulfate") #only values for sulfate
data_sulfate<-data[data$CharacteristicName%in%Sulfate_params,] #want to match all records to the vector we created above which have calcium
unique(data_sulfate$ResultSampleFractionText)
temp<-data_sulfate %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep



###create dataset to check for non numeric objects in dataset
temp<-data_sulfate %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change
data_sulfate<-data_sulfate %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_sulfate$ResultMeasure.MeasureUnitCode) #checked units
unique(data_sulfate$DetectionQuantitationLimitMeasure.MeasureUnitCode)



#need to convert ueq/l to meq/l (*1/000), then meq/l to mg/l (*20.04) - do this for resultconvert and detectconvert - 

data_sulfate<-resultconvert(dat = data_sulfate, variable = "Sulfate", unit = "ueq/L", out_unit = "meq/l_converted", conv_factor = 1/1000)
data_sulfate<-resultconvert(dat = data_sulfate, variable = "Sulfate", unit = "meq/l_converted", out_unit = "mg/l", conv_factor = 20.04)

#do the same for detect convert

data_sulfate<-detectconvert(dat = data_sulfate, variable = "Sulfate", unit = "ueq/L", out_unit = "meq/l_converted", conv_factor = 1/1000)
data_sulfate<-detectconvert(dat = data_sulfate, variable = "Sulfate", unit = "meq/l_converted", out_unit = "mg/l", conv_factor = 20.04)

#check to see everything converted 
temp<-data_sulfate %>% filter(CharacteristicName == "Sulfate")
unique(temp$ResultMeasure.MeasureUnitCode)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)

```

```{r}
#turbidity

Turbidity_params<-c("Turbidity") #only values for turbidity
data_turb<-data[data$CharacteristicName%in%Turbidity_params,] #want to match all records to the vector we created above which have calcium
unique(data_turb$ResultSampleFractionText)
temp<-data_turb %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep



###create dataset to check for non numeric objects in dataset
temp<-data_turb %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change
data_turb<-data_turb %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_turb$ResultMeasure.MeasureUnitCode) #checked units
unique(data_turb$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#detection limit is in NTU - lagos units - don't need to change
#resultmeasurevalue has FTU and FNU - need to convert to NTU

#FTU= NTU, and FNU= NTU ( suggested at similar/comparable - no direct conversion)
#converting both readings to NTU

data_turb$ResultMeasure.MeasureUnitCode<-"NTU"
unique(data_turb$ResultMeasure.MeasureUnitCode)
#completed

```

```{r}
#conductivity

Cond_params<-c("Specific conductance") #only values for conductivity
data_cond<-data[data$CharacteristicName%in%Cond_params,] #want to match all records to the vector we created above which have calcium
unique(data_cond$ResultSampleFractionText)
temp<-data_cond %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep



###create dataset to check for non numeric objects in dataset
temp<-data_cond %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change
data_cond<-data_cond %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_cond$ResultMeasure.MeasureUnitCode) #checked units
unique(data_cond$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#detectionlimit already in lagos units - uS/cm - need to convert resultmeasure from umho/cm to us/cm - conversion = 1:1 - will change text(unit code)- no conversion needed

data_cond<-resultconvert(dat = data_cond, variable = "Specific conductance", unit = "umho/cm", out_unit = "uS/cm", conv_factor = 1)
unique(data_cond$ResultMeasure.MeasureUnitCode)

#changing us/cm @25C to us/cm for resultmeasure and detection limits

data_cond<-resultconvert(dat = data_cond, variable = "Specific conductance", unit = "uS/cm @25C", out_unit = "uS/cm", conv_factor = 1)
data_cond<-detectconvert(dat = data_cond, variable = "Specific conductance", unit = "uS/cm @25C", out_unit = "uS/cm", conv_factor = 1)


#check to see if properly converted

unique(data_cond$ResultMeasure.MeasureUnitCode)
unique(data_cond$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#completed
```
```{r}
#carbon

Carbon_params<-c("Carbon", "Organic carbon") #only values for carbon
data_carbon<-data[data$CharacteristicName%in%Carbon_params,] #want to match all records to the vector we created above which have calcium
unique(data_carbon$ResultSampleFractionText)
temp<-data_carbon %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep
fractionkeep<-c("Dissolved") #only want dissolved organic carbon - not total or suspended
data_carbon<-data_carbon[which(data_carbon$ResultSampleFractionText %in% fractionkeep | is.na(data_carbon$ResultSampleFractionText)),] #keeping if it's ones we chose or NA
unique(data_carbon$ResultSampleFractionText)

#carbon is ambigous - check to see if it's organic 
temp<-data_carbon %>% filter(CharacteristicName == "Carbon") #carbon is ambigous - is it organic or inorganic - checked - carbon got dropped when we did samplefreaction text filter - kept dissolved - left with only organic
unique(data_carbon$CharacteristicName)


###create dataset to check for non numeric objects in dataset
temp<-data_carbon %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change
data_carbon<-data_carbon %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_carbon$ResultMeasure.MeasureUnitCode) #checked units
unique(data_carbon$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#units are mg/l - this is lagos units - no need for conversion

#completed
```
```{r}
#alkalinity


Alk_params<-c("Alkalinity", "Alkalinity, total") #only values for alkalinity
data_alk<-data[data$CharacteristicName%in%Alk_params,] #want to match all records to the vector we created above which have calcium
unique(data_alk$ResultSampleFractionText) #keeping both total and dissolved
temp<-data_alk %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep



###create dataset to check for non numeric objects in dataset
temp<-data_alk %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change
data_alk<-data_alk %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_alk$ResultMeasure.MeasureUnitCode) #checked units
unique(data_alk$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#need to convert mg/l CaCO3 to ueq/l - multiply caco3*19.98, will be converting mg/l to ueql the same way - *19.98


temp<-filter(data_alk, ResultMeasure.MeasureUnitCode == "mg/l") 
unique(temp$CharacteristicName) #all alkalinity totals have mg/l - will be converting alk total and alk seperately

#converting alk total from mg/l to ueq/l
data_alk<-resultconvert(dat = data_alk, variable = "Alkalinity, total", unit = "mg/l", out_unit = "ueq/l", conv_factor = 19.98)
unique(data_alk$ResultMeasure.MeasureUnitCode)

temp<-filter(data_alk, ResultMeasure.MeasureUnitCode == "mg/l CaCO3") #these are also alk total - so will be converting alk total again

#converting alk total from mg/l caco3 to ueq/l
data_alk<-resultconvert(dat = data_alk, variable = "Alkalinity, total", unit = "mg/l CaCO3", out_unit = "ueq/l", conv_factor = 19.98)
unique(data_alk$ResultMeasure.MeasureUnitCode)

#convert mg/l caco3 to ueq/l for detection limits

data_alk<-detectconvert(dat = data_alk, variable = "Alkalinity", unit = "mg/l CaCO3", out_unit = "ueq/L", conv_factor = 19.98)
unique(data_alk$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#completed

```

```{r}
#TSS

Tss_params<-c("Total suspended solids", "Total solids", "Total dissolved solids") #only values for tss
data_tss<-data[data$CharacteristicName%in%Tss_params,] #want to match all records to the vector we created above which have calcium
unique(data_tss$ResultSampleFractionText)
temp<-data_tss %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep
#we only want suspended and total
fractionkeep<-c("Suspended", "Total") 
data_tss<-data_tss[which(data_tss$ResultSampleFractionText %in% fractionkeep | is.na(data_tss$ResultSampleFractionText)),] #keeping if it's ones we chose or NA
unique(data_tss$ResultSampleFractionText)




###create dataset to check for non numeric objects in dataset
temp<-data_tss %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change #3 NA's - can change
data_tss<-data_tss %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_tss$ResultMeasure.MeasureUnitCode) #checked units
unique(data_tss$DetectionQuantitationLimitMeasure.MeasureUnitCode)

temp<-filter(data_tss, ResultMeasure.MeasureUnitCode == "%") #2 weird values measured in perentage rather than mg/l - drop these 2 from records
data_tss<-filter(data_tss, ResultMeasure.MeasureUnitCode != "%")
temp<-filter(data_tss, ResultMeasure.MeasureUnitCode == "%") #checked and it worked  

unique(data_tss$ResultMeasure.MeasureUnitCode) #checked units
unique(data_tss$DetectionQuantitationLimitMeasure.MeasureUnitCode)  
  
#units in mg/l - lagos units - no conversions needed
#completed

```
```{r}
###DIP (dissolved inorganic phosphorus)

unique(data$CharacteristicName)

DIP_params<-c("Orthophosphate") #only values for DIP
data_DIP<-data[data$CharacteristicName%in%DIP_params,] #want to match all records to the vector we created above which have DIP
unique(data_DIP$ResultSampleFractionText)
temp<-data_DIP %>% filter(is.na(ResultSampleFractionText))
#unique(temp$CharacteristicName) #this characteristic name is typically associated with dissolved 
#fractionkeep<-c("Dissolved")
#data_DIP<-data_DIP[which(data_DIP$ResultSampleFractionText %in% fractionkeep | is.na(data_DIP$ResultSampleFractionText)),]
#unique(data_DIP$ResultSampleFractionText)


###create dataset to check for non numeric objects in dataset
temp<-data_DIP %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values - if NA's not losing any other data - can change
#235 NA's - can change
data_DIP<-data_DIP %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA


unique(data_DIP$ResultMeasure.MeasureUnitCode) #check units
unique(data_DIP$DetectionQuantitationLimitMeasure.MeasureUnitCode)


#convert orthophosphate mg/l as PO4 to ug/L
data_DIP<-resultconvert(dat = data_DIP, variable = "Orthophosphate", unit = "mg/l asPO4", out_unit = "ug/L", conv_factor = 326.1)
data_DIP<-detectconvert(dat = data_DIP, variable = "Orthophosphate", unit = "mg/l asPO4", out_unit = "ug/L", conv_factor = 326.1)

#convert orthophosphate mg/l as P to ug/L

data_DIP<-resultconvert(dat = data_DIP, variable = "Orthophosphate", unit = "mg/l as P", out_unit = "ug/L", conv_factor = 1000)
data_DIP<-detectconvert(dat = data_DIP, variable = "Orthophosphate", unit = "mg/l as P", out_unit = "ug/L", conv_factor = 1000)


#convert orthophosphate mg/l to ug/L #assuming it is PO4 even though it doesnt mention - we noticed it's dissolved - we;re assumming

data_DIP<-resultconvert(dat = data_DIP, variable = "Orthophosphate", unit = "mg/l", out_unit = "ug/L", conv_factor = 326.1)


temp<-filter(data_DIP, ResultMeasure.MeasureUnitCode == "ueq/L")
temp<-filter(data_DIP, DetectionQuantitationLimitMeasure.MeasureUnitCode == "ueq/L")
#only 21 observations of each - drop them

data_DIP<-filter(data_DIP, ResultMeasure.MeasureUnitCode != "ueq/L")

#COMPLETED

```
```{r}
unique(data$CharacteristicName)

TP_params<-c("Phosphorus") #only values for total phosphorus
data_TP<-data[data$CharacteristicName%in%TP_params,] #want to match all records to the vector we created above which have TP
unique(data_TP$ResultSampleFractionText)
temp<-data_TP %>% filter(is.na(ResultSampleFractionText))
fractionkeep<-c("Total")
data_TP<-data_TP[which(data_TP$ResultSampleFractionText %in% fractionkeep | is.na(data_TP$ResultSampleFractionText)),] #keeping if it's ones we chose or NA
unique(data_TP$ResultSampleFractionText)


###create dataset to check for non numeric objects in dataset
temp<-data_TP %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values - if NA's not losing any other data - can change
data_TP<-data_TP %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_TP$ResultMeasure.MeasureUnitCode) #check units
unique(data_TP$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#convert mg/l as P and mg/l to ug/l for resultsvalue and detectionlimits

data_TP<-resultconvert(dat = data_TP, variable = "Phosphorus", unit = "mg/l as P", out_unit = "ug/L", conv_factor = 1000)
data_TP<-detectconvert(dat = data_TP, variable = "Phosphorus", unit = "mg/l as P", out_unit = "ug/L", conv_factor = 1000)

data_TP<-resultconvert(dat = data_TP, variable = "Phosphorus", unit = "mg/l", out_unit = "ug/L", conv_factor = 1000)
data_TP<-detectconvert(dat = data_TP, variable = "Phosphorus", unit = "mg/l", out_unit = "ug/L", conv_factor = 1000)

unique(data_TP$ResultMeasure.MeasureUnitCode) #check units
unique(data_TP$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#complete

```

```{r}
#TKN #kjeldahl and organic nitrogen

unique(data$CharacteristicName)

TKN_params<-c("Kjeldahl nitrogen" , "Organic Nitrogen") #only values for TKN
data_TKN<-data[data$CharacteristicName%in%TKN_params,] #want to match all records to the vector we created above which have TKN
unique(data_TKN$ResultSampleFractionText)
temp<-data_TKN %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep
fractionkeep<-c("Total")
data_TKN<-data_TKN[which(data_TKN$ResultSampleFractionText %in% fractionkeep | is.na(data_TKN$ResultSampleFractionText)),] #keeping if it's ones we chose or NA
unique(data_TKN$ResultSampleFractionText)


###create dataset to check for non numeric objects in dataset
temp<-data_TKN %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change - 52 NA's - can change
data_TKN<-data_TKN %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_TKN$ResultMeasure.MeasureUnitCode)
unique(data_TKN$DetectionQuantitationLimitMeasure.MeasureUnitCode)#checked units



#WORKING WITH Kjeldahl nitrogen

temp<-data_TKN %>% filter(CharacteristicName == "Kjeldahl nitrogen") %>% filter(is.na(ResultMeasure.MeasureUnitCode)) %>% filter(!is.na(ResultMeasureValue))


temp<-data_TKN %>% filter(CharacteristicName == "Kjeldahl nitrogen")
unique(temp$ResultMeasure.MeasureUnitCode)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#We have mg/l and mg/l as N - Need to make conversion for both into ug/L as N

data_TKN<-resultconvert(dat = data_TKN, variable = "Kjeldahl nitrogen", unit = "mg/l", out_unit = "ug/l", conv_factor = 1000)
data_TKN<-detectconvert(dat = data_TKN, variable = "Kjeldahl nitrogen", unit = "mg/l", out_unit = "ug/l", conv_factor = 1000)

data_TKN<-resultconvert(dat = data_TKN, variable = "Kjeldahl nitrogen", unit = "mg/l as N", out_unit = "ug/l", conv_factor = 1000)
data_TKN<-detectconvert(dat = data_TKN, variable = "Kjeldahl nitrogen", unit = "mg/l as N", out_unit = "ug/l", conv_factor = 1000)

#check to see everything converted 
temp<-data_TKN %>% filter(CharacteristicName == "Kjeldahl nitrogen")
unique(temp$ResultMeasure.MeasureUnitCode)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#WORKING WITH "Organic Nitrogen"

temp<-data_TKN %>% filter(CharacteristicName == "Organic Nitrogen")
unique(temp$ResultMeasure.MeasureUnitCode)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#need to convert mg/l to ug/l

data_TKN<-resultconvert(dat = data_TKN, variable = "Organic Nitrogen", unit = "mg/l", out_unit = "ug/l", conv_factor = 1000)
data_TKN<-detectconvert(dat = data_TKN, variable = "Organic Nitrogen", unit = "mg/l", out_unit = "ug/l", conv_factor = 1000)

#check to see if conversion worked

temp<-data_TKN %>% filter(CharacteristicName == "Organic Nitrogen")
unique(temp$ResultMeasure.MeasureUnitCode)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#COMPLETED


```


```{r}
#Total Nitrogen

unique(data$CharacteristicName)

TN_params<-c("Nitrogen", "Ammonia", "Ammonia and ammonium", "Nitrogen, mixed forms (NH3), (NH4), organic, (NO2) and (NO3)", "Ammonium", "Ammonia-nitrogen") #only values for TN
data_TN<-data[data$CharacteristicName%in%TN_params,] #want to match all records to the vector we created above which have TP
unique(data_TN$ResultSampleFractionText)
temp<-data_TN %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep
fractionkeep<-c("Total")
data_TN<-data_TN[which(data_TN$ResultSampleFractionText %in% fractionkeep | is.na(data_TN$ResultSampleFractionText)),] #keeping if it's ones we chose or NA
unique(data_TN$ResultSampleFractionText)

###create dataset to check for non numeric objects in dataset
temp<-data_TN %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change #56 NA's - can change
data_TN<-data_TN %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_TN$ResultMeasure.MeasureUnitCode) #checked units
unique(data_TN$DetectionQuantitationLimitMeasure.MeasureUnitCode)


#WORKING WITH "Nitrogen, mixed forms (NH3), (NH4), organic, (NO2) and (NO3)" - convert mg/l NO3 to ug/l N = *0.2259*1000

data_TN<-resultconvert(dat = data_TN, variable = "Nitrogen, mixed forms (NH3), (NH4), organic, (NO2) and (NO3)", unit = "mg/l", out_unit = "ug/l", conv_factor = 0.2259*1000)

data_TN<-detectconvert(dat = data_TN, variable = "Nitrogen, mixed forms (NH3), (NH4), organic, (NO2) and (NO3)", unit = "mg/l", out_unit = "ug/l", conv_factor = 0.2259*1000)


temp<-data_TN %>% filter(CharacteristicName == "Nitrogen, mixed forms (NH3), (NH4), organic, (NO2) and (NO3)")
unique(temp$ResultMeasure.MeasureUnitCode)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)


#WORKING WITH "Nitrogen" 

temp<-data_TN %>% filter(CharacteristicName == "Nitrogen")
unique(temp$ResultMeasure.MeasureUnitCode) #convert mg/l to ug/l
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)  #all NA's - don't need to convert

  
data_TN<-resultconvert(dat = data_TN, variable = "Nitrogen", unit = "mg/l", out_unit = "ug/l", conv_factor = 1000)

temp<-data_TN %>% filter(CharacteristicName == "Nitrogen")
unique(temp$ResultMeasure.MeasureUnitCode) 


#working with "Ammonia"
temp<-data_TN %>% filter(CharacteristicName == "Ammonia")
unique(temp$ResultMeasure.MeasureUnitCode) #convert mg/l to ug/l
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)  #all NA's - don't need to convert

  
data_TN<-resultconvert(dat = data_TN, variable = "Ammonia", unit = "mg/l", out_unit = "ug/l", conv_factor = 1000)

temp<-data_TN %>% filter(CharacteristicName == "Ammonia")
unique(temp$ResultMeasure.MeasureUnitCode) 


#working with "Ammonia and ammonium" - Has 0 observations

temp<-data_TN %>% filter(CharacteristicName == "Ammonia and ammonium")
unique(temp$ResultMeasure.MeasureUnitCode) #convert mg/l to ug/l
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)  #all NA's - don't need to convert

  

#working with "Ammonium"

temp<-data_TN %>% filter(CharacteristicName == "Ammonium")
unique(temp$ResultMeasure.MeasureUnitCode) #convert mg/l to ug/l
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)  #all NA's - don't need to convert
#has 1 observation - it's ueq/l - drop for resultvalue and detectionlimit

data_TN<-filter(data_TN, ResultMeasure.MeasureUnitCode != "ueq/L")


#working with "Ammonia-nitrogen"

temp<-data_TN %>% filter(CharacteristicName == "Ammonia-nitrogen")
unique(temp$ResultMeasure.MeasureUnitCode) #convert mg/l to ug/l
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)  #convert mg/l to ug/l

  
data_TN<-resultconvert(dat = data_TN, variable = "Ammonia-nitrogen", unit = "mg/l", out_unit = "ug/l", conv_factor = 1000)
data_TN<-detectconvert(dat = data_TN, variable = "Ammonia-nitrogen", unit = "mg/l", out_unit = "ug/l", conv_factor = 1000)



temp<-data_TN %>% filter(CharacteristicName == "Ammonia-nitrogen")
unique(temp$ResultMeasure.MeasureUnitCode)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#Completed
```



```{r}

#DIN

unique(data$CharacteristicName)

DIN_params<-c("Inorganic nitrogen (nitrate and nitrite)", "Nitrate", "Nitrite") #only values for DIN
data_DIN<-data[data$CharacteristicName%in%DIN_params,] #want to match all records to the vector we created above which have DIN
unique(data_DIN$ResultSampleFractionText)

temp<-data_DIN %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep
#fractionkeep<-c("Dissolved")
#data_DIN<-data_DIN[which(data_DIN$ResultSampleFractionText %in% fractionkeep | is.na(data_DIN$ResultSampleFractionText)),] #keeping if it's ones we chose or NA
#unique(data_DIN$ResultSampleFractionText)

###create dataset to check for non numeric objects in dataset
temp<-data_DIN %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change #398 NA's - can change
data_DIN<-data_DIN %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_DIN$ResultMeasure.MeasureUnitCode)
unique(data_DIN$DetectionQuantitationLimitMeasure.MeasureUnitCode)


#working with "Inorganic nitrogen (nitrate and nitrite)"

temp<-data_DIN %>% filter(CharacteristicName == "Inorganic nitrogen (nitrate and nitrite)")
unique(temp$ResultMeasure.MeasureUnitCode) 
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)  

  
data_DIN<-resultconvert(dat = data_DIN, variable = "Inorganic nitrogen (nitrate and nitrite)", unit = "mg/l as N", out_unit = "ug/l", conv_factor = 1000)
data_DIN<-detectconvert(dat = data_DIN, variable = "Inorganic nitrogen (nitrate and nitrite)", unit = "mg/l as N", out_unit = "ug/l", conv_factor = 1000)

data_DIN<-resultconvert(dat = data_DIN, variable = "Inorganic nitrogen (nitrate and nitrite)", unit = "mg/l", out_unit = "ug/l", conv_factor = 1000)
data_DIN<-detectconvert(dat = data_DIN, variable = "Inorganic nitrogen (nitrate and nitrite)", unit = "mg/l", out_unit = "ug/l", conv_factor = 1000)


temp<-data_DIN %>% filter(CharacteristicName == "Inorganic nitrogen (nitrate and nitrite)")
unique(temp$ResultMeasure.MeasureUnitCode) 
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)


#working with "Nitrate"

temp<-data_DIN %>% filter(CharacteristicName == "Nitrate")
unique(temp$ResultMeasure.MeasureUnitCode) 
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)  


data_DIN<-resultconvert(dat = data_DIN, variable = "Nitrate", unit = "mg/l as N", out_unit = "ug/l", conv_factor = 1000)
data_DIN<-detectconvert(dat = data_DIN, variable = "Nitrate", unit = "mg/l as N", out_unit = "ug/l", conv_factor = 1000)
data_DIN<-resultconvert(dat = data_DIN, variable = "Nitrate", unit = "mg/l", out_unit = "ug/l", conv_factor = 1000)

data_DIN<-resultconvert(dat = data_DIN, variable = "Nitrate", unit = "mg/l asNO3", out_unit = "ug/l", conv_factor = 0.2259*1000)

data_DIN<-detectconvert(dat = data_DIN, variable = "Nitrate", unit = "mg/l asNO3", out_unit = "ug/l", conv_factor = 0.2259*1000)

temp<-filter(data_DIN, ResultMeasure.MeasureUnitCode == "ueq/L")
temp<-filter(data_DIN, DetectionQuantitationLimitMeasure.MeasureUnitCode == "ueq/L")

#drop these

data_DIN<-filter(data_DIN, ResultMeasure.MeasureUnitCode != "ueq/L")

#working with "Nitrite"

temp<-data_DIN %>% filter(CharacteristicName == "Nitrite")
unique(temp$ResultMeasure.MeasureUnitCode) 
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)  

data_DIN<-resultconvert(dat = data_DIN, variable = "Nitrite", unit = "mg/l as N", out_unit = "ug/l", conv_factor = 1000)
data_DIN<-detectconvert(dat = data_DIN, variable = "Nitrite", unit = "mg/l as N", out_unit = "ug/l", conv_factor = 1000)
data_DIN<-resultconvert(dat = data_DIN, variable = "Nitrite", unit = "mg/l", out_unit = "ug/l", conv_factor = 1000)
data_DIN<-resultconvert(dat = data_DIN, variable = "Nitrite", unit = "mg/l asNO2", out_unit = "ug/l", conv_factor = 0.3044*1000)

#completed

```

```{r}

alldata_VA<- rbind(data_secchi, data_calcium, data_aluminum, data_mercury, data_magnesium, data_selenium, data_arsenic, data_atrazine, data_ecoli, data_silica, data_chloride, data_oxygen, data_chla, data_pH, data_temp, data_sulfate, data_turb, data_cond, data_carbon, data_alk, data_tss, data_DIP, data_TP, data_TKN, data_TN, data_DIN)     


```

