---
title: "Datacleaningcode_AZ"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
#here are functions

#for temperature

resultconvert_celsius<-function(dat, variable, unit, out_unit) {
  dat$ResultMeasureValue[which(dat$CharacteristicName == variable & dat$ResultMeasure.MeasureUnitCode == unit)] <- (dat$ResultMeasureValue[which(dat$CharacteristicName == variable & dat$ResultMeasure.MeasureUnitCode == unit)] -32)* 5/9
  
dat$ResultMeasure.MeasureUnitCode[which(dat$CharacteristicName == variable & dat$ResultMeasure.MeasureUnitCode == unit)] <- out_unit

return(dat)
  
}


detectconvert_celsius<-function(dat, variable, unit, out_unit) {
  dat$DetectionQuantitationLimitMeasure.MeasureValue[which(dat$CharacteristicName == variable & dat$DetectionQuantitationLimitMeasure.MeasureUnitCode == unit)] <- (dat$DetectionQuantitationLimitMeasure.MeasureValue[which(dat$CharacteristicName == variable & dat$DetectionQuantitationLimitMeasure.MeasureUnitCode == unit)] * -32)*5/9
  
dat$DetectionQuantitationLimitMeasure.MeasureUnitCode[which(dat$CharacteristicName == variable & dat$DetectionQuantitationLimitMeasure.MeasureUnitCode == unit)] <- out_unit

return(dat)
  
}

#for all other conversions

resultconvert<-function(dat, variable, unit, out_unit, conv_factor) {
  dat$ResultMeasureValue[which(dat$CharacteristicName == variable & dat$ResultMeasure.MeasureUnitCode == unit)] <- dat$ResultMeasureValue[which(dat$CharacteristicName == variable & dat$ResultMeasure.MeasureUnitCode == unit)] * conv_factor
  
dat$ResultMeasure.MeasureUnitCode[which(dat$CharacteristicName == variable & dat$ResultMeasure.MeasureUnitCode == unit)] <- out_unit

return(dat)
  
}


detectconvert<-function(dat, variable, unit, out_unit, conv_factor) {
  dat$DetectionQuantitationLimitMeasure.MeasureValue[which(dat$CharacteristicName == variable & dat$DetectionQuantitationLimitMeasure.MeasureUnitCode == unit)] <- dat$DetectionQuantitationLimitMeasure.MeasureValue[which(dat$CharacteristicName == variable & dat$DetectionQuantitationLimitMeasure.MeasureUnitCode == unit)] * conv_factor
  
dat$DetectionQuantitationLimitMeasure.MeasureUnitCode[which(dat$CharacteristicName == variable & dat$DetectionQuantitationLimitMeasure.MeasureUnitCode == unit)] <- out_unit

return(dat)
  
}


`%notin%` <- Negate(`%in%`)

#datapull

AZdatPull<-read.csv("~/Lagos Limno/AZ_alldata_1975_to_2020.csv")

names(AZdatPull)

summary(AZdatPull)

#removing data that have Y's instead of keeping data that have N's

read.csv("~/Lagos Limno/list of unique parameters to remove.csv") -> remove_params 


data<- AZdatPull[AZdatPull$CharacteristicName %notin% remove_params$Unique.parameters,]
data<-data %>% mutate(obs_id = seq(1, nrow(data), 1))

tdata1<-data %>% filter(!is.na(ResultDepthHeightMeasure.MeasureValue)) #identified specified depth samples



tdata2<-data %>% filter(is.na(ResultDepthHeightMeasure.MeasureValue)) %>% filter(!is.na(ActivityTopDepthHeightMeasure.MeasureValue)) #these are potential integrated samples

unique(tdata2$SampleCollectionMethod.MethodName)
method_name<-c("")

unique(tdata2$SampleCollectionMethod.MethodIdentifier)
method_identifier<-c("")

unique(tdata2$SampleCollectionMethod.MethodIdentifierContext)
method_context<-c("")

unique(tdata2$SampleCollectionEquipmentName)
method_equipment<-c("")

tdata2<-tdata2 %>% filter(SampleCollectionMethod.MethodName %in% method_name | 
                            SampleCollectionMethod.MethodIdentifier %in% method_identifier|
                            SampleCollectionMethod.MethodIdentifierContext %in% method_context|
                            SampleCollectionEquipmentName %in% method_equipment)  #all integrated samples

tdata3<-data %>% filter(is.na(ResultDepthHeightMeasure.MeasureValue)) #identifying grab samples

unique(tdata3$SampleCollectionMethod.MethodName)
method_name<-c("Lake Grab Sample", "Grab Sample", "Grab sample  (dip)", "Water Grab Sampling", "Single vertical")

unique(tdata3$SampleCollectionMethod.MethodIdentifier)
method_identifier<-c("Grab Sample", "NNEPAWQP-Grab Lake")

unique(tdata3$SampleCollectionMethod.MethodIdentifierContext)
method_context<-c("USGS parameter code 82398")

unique(tdata3$SampleCollectionEquipmentName)
method_equipment<-c("Open-Mouth Bottle", "Grab sample")

tdata3<-tdata3 %>% filter(SampleCollectionMethod.MethodName %in% method_name | 
                            SampleCollectionMethod.MethodIdentifier %in% method_identifier|
                            SampleCollectionMethod.MethodIdentifierContext %in% method_context|
                            SampleCollectionEquipmentName %in% method_equipment)  #all grab samples

data2<-rbind(tdata1, tdata2, tdata3)
rm(tdata1)
rm(tdata2)
rm(tdata3)

tdata4<-data %>% filter(obs_id %notin% data2$obs_id)#created object to look at all data not in datata2

unique(tdata4$CharacteristicName)
secchiparams<-c("Secchi, Horizontal Distance", "Depth, Secchi disk depth") #pulled out secchi data cuz it may not have depth data

tdata4<-tdata4 %>% filter(CharacteristicName %in% secchiparams) #filtered out only the secchi vars
data<-rbind(data2, tdata4) #combined everything back together

#will need to check for each state (the depth data)

rm(tdata4)
rm(data2)
data<-data %>% select(-obs_id)
rm(AZdatPull)
unique(data$CharacteristicName)

data<-data %>% filter(!(is.na(ResultMeasureValue) & is.na(DetectionQuantitationLimitMeasure.MeasureValue)))



#unique organizations
unique(data$OrganizationIdentifier) #10 organizations data
table(data$OrganizationFormalName) #tells us number of obvs in each organization




#looking at activity type codes
unique(data$ActivityTypeCode)
activitytype_keep<-c("Quality Control Sample-Equipment Blank", "Quality Control Field Replicate Portable Data Logger", "Quality Control Field Replicate Msr/Obs", "Quality Control Sample-Field Replicate")


data<-data[which(data$ActivityTypeCode %notin% activitytype_keep),]
unique(data$ActivityTypeCode)

#manually checking these columns to see if these is data we keep or can drop

unique(data$SubjectTaxonomicName) #expected it to be na - to make sure nothing we need is in there
unique(data$SampleTissueAnatomyName) #also NA's - expected

unique(data$ActivityMediaSubdivisionName)
#only keeping subdivision name with surface water and NA's - dropping everything else 
data<-data %>% filter(ActivityMediaSubdivisionName == "Surface Water" | is.na(ActivityMediaSubdivisionName))
unique(data$ActivityMediaSubdivisionName)

unique(data$ResultStatusIdentifier)
unique(data$ResultValueTypeName)


unique(data$ResultDetectionConditionText)
#filtered out vars we don't need in resultsdetection condition text - did it in multistep because R doesn't handle multiple OR statements well


data<-data %>% filter(ResultDetectionConditionText != "Systematic Contamination" | is.na(ResultDetectionConditionText))

data<-data %>% filter(is.na(ResultDetectionConditionText) | ResultDetectionConditionText != "Not Reported")
unique(data$ResultDetectionConditionText)



unique(data$ResultSampleFractionText)

data<-data %>% filter(is.na(ResultSampleFractionText) | ResultSampleFractionText != "Bed Sediment")
unique(data$ResultSampleFractionText)


data<-data %>% select(-ActivityMediaName, -ActivityMediaSubdivisionName, -ActivityStartTime.Time, -ActivityStartTime.TimeZoneCode, -ActivityEndTime.Time, -ActivityEndTime.TimeZoneCode, -SampleAquifer, -HydrologicCondition, -HydrologicEvent, -SubjectTaxonomicName, -SampleTissueAnatomyName, -LaboratoryName, -AnalysisStartDate, -PreparationStartDate)

```

```{r}
#list of unique parameters
unique(data$CharacteristicName)
write.table(unique(data$CharacteristicName), "unique_parameters_AZ.csv", row.names = FALSE)

sum(is.na(data$ResultDepthHeightMeasure.MeasureValue))
unique(data$ActivityTypeCode)
unique(data$ResultDepthAltitudeReferencePointText)
temp<-data %>% filter(ResultDepthAltitudeReferencePointText == "Surface")
unique(data$SampleCollectionMethod.MethodName)

```

```{r}

###creating new columns to preserve original pulled data

data$source_parameter <- data$CharacteristicName
data$source_value<- data$ResultMeasureValue
data$source_unit <- data$ResultMeasure.MeasureUnitCode
data$detectionlimit_legacy <- data$DetectionQuantitationLimitMeasure.MeasureValue
data$detectionlimit_unit_legacy <- data$DetectionQuantitationLimitMeasure.MeasureUnitCode
```

```{r}
###Secchi
unique(data$CharacteristicName)

###set all the secchi params to read as secchi instead of the 6 objects below

secchi_params<-c("Depth, data-logger (ported)", "Depth, Secchi disk depth", "Depth")
data_secchi<-data[data$CharacteristicName%in%secchi_params,]
data_secchi$CharacteristicName<-"Secchi"

###checking for Na's
unique(data_secchi$ResultMeasure.MeasureUnitCode) #checked units
temp<-data_secchi %>% filter(is.na(ResultMeasure.MeasureUnitCode)) #checked how many na's we had #only 8
data_secchi<-data_secchi %>% filter(!is.na(ResultMeasure.MeasureUnitCode)) #filtered out NA's


###create dataset to check for non numeric objects in dataset
temp<-data_secchi %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in the results - had 0
data_secchi<-data_secchi %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

#CONVERSIONS

###convert inches to m for obvservations
data_secchi$ResultMeasureValue[which(data_secchi$ResultMeasure.MeasureUnitCode == "in")] <- data_secchi$ResultMeasureValue[which(data_secchi$ResultMeasure.MeasureUnitCode == "in")] * 0.0254

data_secchi[(!is.na(data_secchi$DetectionQuantitationLimitMeasure.MeasureUnitCode) & data_secchi$ResultMeasure.MeasureUnitCode != data_secchi$DetectionQuantitationLimitMeasure.MeasureUnitCode),] #checks to see if detection limit units same as obvs units

#convert inches to m for detectionlimits
data_secchi$DetectionQuantitationLimitMeasure.MeasureValue[which(data_secchi$ResultMeasure.MeasureUnitCode == "in")] <- data_secchi$DetectionQuantitationLimitMeasure.MeasureValue[which(data_secchi$ResultMeasure.MeasureUnitCode == "in")] * 0.0254


####convert ft to m's for values

data_secchi$ResultMeasureValue[which(data_secchi$ResultMeasureValue == "ft")] <-
  data_secchi$ResultMeasureValue[which(data_secchi$ResultMeasureValue == "ft")] * 0.3048

#convert ft to m's for detection limits

data_secchi$DetectionQuantitationLimitMeasure.MeasureValue[which(data_secchi$DetectionQuantitationLimitMeasure.MeasureValue == "ft")]<-
  data_secchi$DetectionQuantitationLimitMeasure.MeasureValue[which(data_secchi$DetectionQuantitationLimitMeasure.MeasureValue == "ft")] * 0.3048

#then change all the units to m

data_secchi$ResultMeasure.MeasureUnitCode<-"m" #for values

data_secchi$DetectionQuantitationLimitMeasure.MeasureUnitCode<-"m"  #for detection limit
#check to see if it worked
unique(data_secchi$ResultMeasure.MeasureUnitCode)
unique(data_secchi$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#complete
```

```{r}
###calcium

unique(data$CharacteristicName)

calcium_params<-c("Calcium") #only values for Calcium
data_calcium<-data[data$CharacteristicName%in%calcium_params,] #want to match all records to the vector we created above which have Calcium

#checking and filtering out NA's
unique(data_calcium$ResultMeasure.MeasureUnitCode) #checked units
temp<-data_calcium %>% filter(is.na(ResultMeasure.MeasureUnitCode)) #checked how many na's we had #only 5
#data_calcium<-data_calcium %>% filter(!is.na(ResultMeasure.MeasureUnitCode)) #filtered out NA's

###create dataset to check for non numeric objects in dataset
temp<-data_calcium %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in the results # 4 non numeric values
data_calcium<-data_calcium %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA


data_calcium$CharacteristicName<-"Calcium"  #rename everything in the characteristics column as calcium

###convert ppm to mg/l for obvservations ##1ppm = 1mg/l
data_calcium$ResultMeasureValue[which(data_calcium$ResultMeasure.MeasureUnitCode == "ppm")] <- data_calcium$ResultMeasureValue[which(data_calcium$ResultMeasure.MeasureUnitCode == "ppm")] * 1

data_calcium[(!is.na(data_calcium$DetectionQuantitationLimitMeasure.MeasureUnitCode) & data_calcium$ResultMeasure.MeasureUnitCode != data_calcium$DetectionQuantitationLimitMeasure.MeasureUnitCode),] #checks to see if detection limit units same as obvs units

#convert ppm to mg/l for detectionlimits
data_calcium$DetectionQuantitationLimitMeasure.MeasureValue[which(data_calcium$ResultMeasure.MeasureUnitCode == "ppm")] <- data_calcium$DetectionQuantitationLimitMeasure.MeasureValue[which(data_calcium$ResultMeasure.MeasureUnitCode == "ppm")] * 1


####convert ug/l to mg/l for values

data_calcium$ResultMeasureValue[which(data_calcium$ResultMeasureValue == "ug/l")] <-
  data_calcium$ResultMeasureValue[which(data_calcium$ResultMeasureValue == "ug/l")] / 0.001

#convert ug/l to mg/l for detection limits

data_calcium$DetectionQuantitationLimitMeasure.MeasureValue[which(data_calcium$DetectionQuantitationLimitMeasure.MeasureValue == "ug/l")]<-
  data_calcium$DetectionQuantitationLimitMeasure.MeasureValue[which(data_calcium$DetectionQuantitationLimitMeasure.MeasureValue == "ug/l")] /0.001

#then change all the units to mg/l

data_calcium$ResultMeasure.MeasureUnitCode<-"mg/l" #for values
data_calcium$DetectionQuantitationLimitMeasure.MeasureUnitCode<-"mg/l"  #for detection limit

#check to see if it worked
unique(data_calcium$ResultMeasure.MeasureUnitCode)
unique(data_calcium$DetectionQuantitationLimitMeasure.MeasureUnitCode)

unique(data_calcium$ResultSampleFractionText) # we want to only keep dissolved 
data_calcium<-data_calcium %>% filter(ResultSampleFractionText == "Dissolved") 



```

```{r}
#aluminum

unique(data$CharacteristicName)

Aluminum_params<-c("Aluminum") #only values for aluminum
data_aluminum<-data[data$CharacteristicName%in%Aluminum_params,] #want to match all records to the vector we created above which have Calcium
data_aluminum$CharacteristicName<-"Aluminum"  #rename everything in the characteristics column as calcium

#checking and filtering out NA's
unique(data_aluminum$ResultMeasure.MeasureUnitCode) #checked units
temp<-data_aluminum %>% filter(is.na(ResultMeasure.MeasureUnitCode)) #had 521 - not filtering out in this case - check with NOAH
#data_aluminum<-data_aluminum %>% filter(!is.na(ResultMeasure.MeasureUnitCode)) #filtered out NA's

###create dataset to check for non numeric objects in dataset
temp<-data_aluminum %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in the results # 1332 non numeric values
data_aluminum$ResultDetectionConditionText[which(data_aluminum$ResultMeasureValue == "< 3")] <- "Not Detected"
data_aluminum<-data_aluminum %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA  -- CHECK WITH NOAH
unique(temp$ResultMeasureValue)


###convert ppm to mg/l for obvservations ##1ppm = 1mg/l
#data_aluminum$ResultMeasureValue[which(data_aluminum$ResultMeasure.MeasureUnitCode == "in")] <- data_aluminum$ResultMeasureValue[which(data_aluminum$ResultMeasure.MeasureUnitCode == "in")] * 1

#data_aluminum[(!is.na(data_aluminum$DetectionQuantitationLimitMeasure.MeasureUnitCode) & data_aluminum$ResultMeasure.MeasureUnitCode != data_aluminum$DetectionQuantitationLimitMeasure.MeasureUnitCode),] #checks to see if detection limit units same as obvs units

#convert ppm to mg/l for detectionlimits
#data_aluminum$DetectionQuantitationLimitMeasure.MeasureValue[which(data_aluminum$ResultMeasure.MeasureUnitCode == "in")] <- data_aluminum$DetectionQuantitationLimitMeasure.MeasureValue[which(data_aluminum$ResultMeasure.MeasureUnitCode == "in")] * 1


####convert mg/l to ug/l for values

data_aluminum$ResultMeasureValue[which(data_aluminum$ResultMeasureValue == "mg/l")] <-
  data_aluminum$ResultMeasureValue[which(data_aluminum$ResultMeasureValue == "mg/l")] *1000

#convert mg/l to ug/l for detection limits

data_aluminum$DetectionQuantitationLimitMeasure.MeasureValue[which(data_aluminum$DetectionQuantitationLimitMeasure.MeasureValue == "mg/l")]<-
data_aluminum$DetectionQuantitationLimitMeasure.MeasureValue[which(data_aluminum$DetectionQuantitationLimitMeasure.MeasureValue == "mg/l")] *1000

#then change all the units to ug/l

data_aluminum$ResultMeasure.MeasureUnitCode<-"ug/l" #for values
data_aluminum$DetectionQuantitationLimitMeasure.MeasureUnitCode<-"ug/l"  #for detection limit

#check to see if it worked
unique(data_aluminum$ResultMeasure.MeasureUnitCode)
unique(data_aluminum$DetectionQuantitationLimitMeasure.MeasureUnitCode)

unique(data_aluminum$ResultSampleFractionText)
data_aluminum$ResultSampleFractionText[which(data_aluminum$ResultSampleFractionText == "Recoverable")]<-"Total"  #add recoverable into total category


```

```{r}
###silica

unique(data$CharacteristicName)

silica_params<-c("Silica") #only values for Calcium
data_silica<-data[data$CharacteristicName%in%silica_params,] #want to match all records to the vector we created above which have silica
data_silica$CharacteristicName<-"Silica"  #rename everything in the characteristics column as silica

unique(data_silica$ResultSampleFractionText)

#checking and filtering out NA's
unique(data_silica$ResultMeasure.MeasureUnitCode) #checked units
temp<-data_silica %>% filter(is.na(ResultMeasure.MeasureUnitCode)) #checked how many na's we had #158
data_silica<-data_silica %>% filter(!is.na(ResultMeasure.MeasureUnitCode)) #filtered out NA's

###create dataset to check for non numeric objects in dataset
temp<-data_silica %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in the results # 2 non numeric values
data_silica<-data_silica %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA


data_silica[(!is.na(data_silica$DetectionQuantitationLimitMeasure.MeasureUnitCode) & data_silica$ResultMeasure.MeasureUnitCode != data_silica$DetectionQuantitationLimitMeasure.MeasureUnitCode),] #checks to see if detection limit units same as obvs units - equals 0 - expected

###convert ppm to mg/l for obvservations ##1ppm = 1mg/l
#data_silica$ResultMeasureValue[which(data_silica$ResultMeasure.MeasureUnitCode == "ppm")] <- data_silica$ResultMeasureValue[which(data_silica$ResultMeasure.MeasureUnitCode == "ppm")] * 1

#convert ppm to mg/l for detectionlimits
#data_silica$DetectionQuantitationLimitMeasure.MeasureValue[which(data_silica$ResultMeasure.MeasureUnitCode == "ppm")] <- data_silica$DetectionQuantitationLimitMeasure.MeasureValue[which(data_silica$ResultMeasure.MeasureUnitCode == "ppm")] * 1


####convert ug/l to mg/l for values

#data_silica$ResultMeasureValue[which(data_silica$ResultMeasureValue == "ug/l")] <-
#data_silica$ResultMeasureValue[which(data_silica$ResultMeasureValue == "ug/l")] / 0.001

#convert ug/l to mg/l for detection limits

#data_silica$DetectionQuantitationLimitMeasure.MeasureValue[which(data_silica$DetectionQuantitationLimitMeasure.MeasureValue == "ug/l")]<-
#data_silica$DetectionQuantitationLimitMeasure.MeasureValue[which(data_silica$DetectionQuantitationLimitMeasure.MeasureValue == "ug/l")] /0.001

#then change all the units to mg/l

data_silica$ResultMeasure.MeasureUnitCode<-"mg/l" #for values
data_silica$DetectionQuantitationLimitMeasure.MeasureUnitCode<-"mg/l"  #for detection limit

#check to see if it worked
unique(data_silica$ResultMeasure.MeasureUnitCode)
unique(data_silica$DetectionQuantitationLimitMeasure.MeasureUnitCode)


```