---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
#here are functions
#for temperature

resultconvert_celsius<-function(dat, variable, unit, out_unit) {
  dat$ResultMeasureValue[which(dat$CharacteristicName == variable & dat$ResultMeasure.MeasureUnitCode == unit)] <- (dat$ResultMeasureValue[which(dat$CharacteristicName == variable & dat$ResultMeasure.MeasureUnitCode == unit)] -32)* 5/9
  
dat$ResultMeasure.MeasureUnitCode[which(dat$CharacteristicName == variable & dat$ResultMeasure.MeasureUnitCode == unit)] <- out_unit

return(dat)
  
}


detectconvert_celsius<-function(dat, variable, unit, out_unit) {
  dat$DetectionQuantitationLimitMeasure.MeasureValue[which(dat$CharacteristicName == variable & dat$DetectionQuantitationLimitMeasure.MeasureUnitCode == unit)] <- (dat$DetectionQuantitationLimitMeasure.MeasureValue[which(dat$CharacteristicName == variable & dat$DetectionQuantitationLimitMeasure.MeasureUnitCode == unit)] * -32)*5/9
  
dat$DetectionQuantitationLimitMeasure.MeasureUnitCode[which(dat$CharacteristicName == variable & dat$DetectionQuantitationLimitMeasure.MeasureUnitCode == unit)] <- out_unit

return(dat)
  
}

#for all other conversions

resultconvert<-function(dat, variable, unit, out_unit, conv_factor) {
  dat$ResultMeasureValue[which(dat$CharacteristicName == variable & dat$ResultMeasure.MeasureUnitCode == unit)] <- dat$ResultMeasureValue[which(dat$CharacteristicName == variable & dat$ResultMeasure.MeasureUnitCode == unit)] * conv_factor
  
dat$ResultMeasure.MeasureUnitCode[which(dat$CharacteristicName == variable & dat$ResultMeasure.MeasureUnitCode == unit)] <- out_unit

return(dat)
  
}


detectconvert<-function(dat, variable, unit, out_unit, conv_factor) {
  dat$DetectionQuantitationLimitMeasure.MeasureValue[which(dat$CharacteristicName == variable & dat$DetectionQuantitationLimitMeasure.MeasureUnitCode == unit)] <- dat$DetectionQuantitationLimitMeasure.MeasureValue[which(dat$CharacteristicName == variable & dat$DetectionQuantitationLimitMeasure.MeasureUnitCode == unit)] * conv_factor
  
dat$DetectionQuantitationLimitMeasure.MeasureUnitCode[which(dat$CharacteristicName == variable & dat$DetectionQuantitationLimitMeasure.MeasureUnitCode == unit)] <- out_unit

return(dat)
  
}


`%notin%` <- Negate(`%in%`)

DEdatPull<-read.csv("~/Lagos Limno/DE_alldata_1975_to_2020.csv")

names(DEdatPull)

summary(DEdatPull)

#removing data that have Y's instead of keeping data that have N's

read.csv("~/Lagos Limno/list of unique parameters to remove.csv") -> remove_params #update this


data<- DEdatPull[DEdatPull$CharacteristicName %notin% remove_params$Unique.parameters,]
data<-data %>% mutate(obs_id = seq(1, nrow(data), 1))


# tdata1<-data %>% filter(!is.na(ResultDepthHeightMeasure.MeasureValue)) #identified specified depth samples
# 
# 
# tdata2<-data %>% filter(is.na(ResultDepthHeightMeasure.MeasureValue)) %>% filter(!is.na(ActivityTopDepthHeightMeasure.MeasureValue)) #these are potential integrated samples
# 
# unique(tdata2$SampleCollectionMethod.MethodName)
# method_name<-c("")
# 
# unique(tdata2$SampleCollectionMethod.MethodIdentifier)
# method_identifier<-c("")
# 
# unique(tdata2$SampleCollectionMethod.MethodIdentifierContext)
# method_context<-c("")
# 
# unique(tdata2$SampleCollectionEquipmentName)
# method_equipment<-c("")
# 
# tdata2<-tdata2 %>% filter(SampleCollectionMethod.MethodName %in% method_name | 
#                             SampleCollectionMethod.MethodIdentifier %in% method_identifier|
#                             SampleCollectionMethod.MethodIdentifierContext %in% method_context|
#                             SampleCollectionEquipmentName %in% method_equipment)  #all grab samples
# 
# tdata3<-data %>% filter(is.na(ResultDepthHeightMeasure.MeasureValue)) #identifying grab samples
# 
# unique(tdata3$SampleCollectionMethod.MethodName)
# method_name<-c("Grab Sample Collected With A Stainless Bucket", "Grab Sample Collected With A Water Bottle")
# 
# unique(tdata3$SampleCollectionMethod.MethodIdentifier)
# method_identifier<-c("Stainless Bucket", "Water Bottle")
# 
# unique(tdata3$SampleCollectionMethod.MethodIdentifierContext)
# method_context<-c("")
# 
# unique(tdata3$SampleCollectionEquipmentName)
# method_equipment<-c("Bucket", "Water Sampler (Other)", "Water Bottle")
# 
# tdata3<-tdata3 %>% filter(SampleCollectionMethod.MethodName %in% method_name | 
#                             SampleCollectionMethod.MethodIdentifier %in% method_identifier|
#                             SampleCollectionMethod.MethodIdentifierContext %in% method_context|
#                             SampleCollectionEquipmentName %in% method_equipment)  #all grab samples
# 
# data2<-rbind(tdata1, tdata2, tdata3)
# rm(tdata1)
# rm(tdata2)
# rm(tdata3)
# 
# tdata4<-data %>% filter(obs_id %notin% data2$obs_id)#created object to look at all data not in datata2
# 
# unique(tdata4$CharacteristicName)
# secchiparams<-c("Depth, Secchi disk depth") #pulled out secchi data cuz it may not have depth data
# 
# tdata4<-tdata4 %>% filter(CharacteristicName %in% secchiparams) #filtered out only the secchi vars
# data<-rbind(data2, tdata4) #combined everything back together
# 
# #will need to check for each state (the depth data)
# 
# rm(tdata4)
# rm(data2)
# data<-data %>% select(-obs_id)
# rm(DEdatPull)
# unique(data$CharacteristicName)


str(data$ResultMeasureValue)
sum(is.na(data$ResultMeasureValue))
data1<-data %>% filter(!is.na(ResultMeasureValue))
data2<-data %>% filter(!is.na(DetectionQuantitationLimitMeasure.MeasureValue)) %>% filter(is.na(ResultMeasureValue))
data3<-rbind(data1, data2)
data<-data3

rm(data1, data2, data3)


#unique organizations
unique(data$OrganizationIdentifier) #19 organizations data
table(data$OrganizationFormalName) #tells us number of obvs in each organization




#looking at activity type codes
unique(data$ActivityTypeCode)
activitytype_keep<-c("Quality Control Field Replicate Msr/Obs", "Quality Control Sample-Field Replicate", "Quality Control Sample-Field Blank")
data<-data[which(data$ActivityTypeCode %notin% activitytype_keep),]
unique(data$ActivityTypeCode)

#manually checking these columns to see if these is data we keep or can drop

unique(data$SubjectTaxonomicName) #expected it to be na - to make sure nothing we need is in there
unique(data$SampleTissueAnatomyName) #also NA's - expected

unique(data$ActivityMediaSubdivisionName)
#only keeping subdivision name with surface water and NA's - dropping everything else 
data<-data %>% filter(ActivityMediaSubdivisionName == "Surface Water" | is.na(ActivityMediaSubdivisionName))
unique(data$ActivityMediaSubdivisionName)

unique(data$ResultStatusIdentifier)
unique(data$ResultValueTypeName)


unique(data$ResultDetectionConditionText)
#filtered out vars we don't need in resultsdetection condition text - did it in multistep because R doesn't handle multiple OR statements well


data<-data %>% filter(ResultDetectionConditionText != "Systematic Contamination" | is.na(ResultDetectionConditionText))

data<-data %>% filter(is.na(ResultDetectionConditionText) | ResultDetectionConditionText != "Not Reported")
unique(data$ResultDetectionConditionText)



unique(data$ResultSampleFractionText)

data<-data %>% filter(is.na(ResultSampleFractionText) | ResultSampleFractionText != "Bed Sediment")
unique(data$ResultSampleFractionText)


data<-data %>% select(-ActivityMediaName, -ActivityMediaSubdivisionName, -ActivityStartTime.Time, -ActivityStartTime.TimeZoneCode, -ActivityEndTime.Time, -ActivityEndTime.TimeZoneCode, -SampleAquifer, -HydrologicCondition, -HydrologicEvent, -SubjectTaxonomicName, -SampleTissueAnatomyName, -LaboratoryName, -AnalysisStartDate, -PreparationStartDate)


unique(data$ActivityDepthHeightMeasure.MeasureUnitCode) #has ft, feet, and m - need to convert the ones with ft and feet 
unique(data$ActivityTopDepthHeightMeasure.MeasureUnitCode) #all in m - no conversion needed
unique(data$ActivityBottomDepthHeightMeasure.MeasureUnitCode) #all in m - no conversion needed
unique(data$ResultDepthHeightMeasure.MeasureUnitCode) #all in m - no conversion needed

#all in m's - no conversions required

```

```{r}
#list of unique parameters
#unique(data$CharacteristicName)
#write.table(unique(data$CharacteristicName), "unique_parameters_DE.csv", row.names = FALSE)
#unique_parameters_VA<-read.csv("~/Lagos Limno/unique_parameters_VA.csv")
#data<-data[data$CharacteristicName %in% unique_parameters_VA$Unique_params,]
#unique(data$CharacteristicName)


```

```{r}

###creating new columns to preserve original pulled data

data$source_parameter <- data$CharacteristicName
data$source_value<- data$ResultMeasureValue
data$source_unit <- data$ResultMeasure.MeasureUnitCode
data$detectionlimit_legacy <- data$DetectionQuantitationLimitMeasure.MeasureValue
data$detectionlimit_unit_legacy <- data$DetectionQuantitationLimitMeasure.MeasureUnitCode

#spreadsheet for VA variables
#write.table(unique(data$CharacteristicName), "Va_vars.csv", row.names = FALSE)
```


```{r}
#secchi

unique(data$CharacteristicName)

Secchi_params<-c("Depth, Secchi disk depth") #values for secchi
data_secchi<-data[data$CharacteristicName%in%Secchi_params,]
unique(data_secchi$ResultSampleFractionText)
temp<-data_secchi %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep


###create dataset to check for non numeric objects in dataset
temp<-data_secchi %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change
data_secchi<-data_secchi %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_secchi$ResultMeasure.MeasureUnitCode) #checked units
unique(data_secchi$DetectionQuantitationLimitMeasure.MeasureUnitCode)

temp<-data_secchi[which(!is.na(data_secchi$DetectionQuantitationLimitMeasure.MeasureUnitCode) & data_secchi$ResultMeasure.MeasureUnitCode != data_secchi$DetectionQuantitationLimitMeasure.MeasureUnitCode),] #checks to see if detection limit units same as obvs units

###convert inches to m for resultsmeasurevalues
data_secchi<-resultconvert(dat = data_secchi, variable = "Depth, Secchi disk depth", unit = "in", out_unit = "m", conv_factor = 0.0254)
unique(data_secchi$ResultMeasure.MeasureUnitCode)

data_secchi$CharacteristicName<-"Secchi"

#don't  need to convert units for detectionlimits - all NA's

#done
```



```{r}
#calcium

Calcium_params<-c("Calcium") #only values for calcium
data_calcium<-data[data$CharacteristicName%in%Calcium_params,] #want to match all records to the vector we created above which have calcium
unique(data_calcium$ResultSampleFractionText)
temp<-data_calcium %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep



###create dataset to check for non numeric objects in dataset
temp<-data_calcium %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change
data_calcium<-data_calcium %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_calcium$ResultMeasure.MeasureUnitCode) #checked units
unique(data_calcium$DetectionQuantitationLimitMeasure.MeasureUnitCode)


#convert ug/l to mg/l for resultvalues, don't need to do anything for detection limits
data_calcium<-resultconvert(dat = data_calcium, variable = "Calcium", unit = "ug/l", out_unit = "mg/l", conv_factor = 1/1000)
unique(data_calcium$ResultMeasure.MeasureUnitCode)

data_calcium$CharacteristicName<-"Calcium"

#COMPLETED
```
```{r}
#aluminum Dissolved - checked - no total aluminum exists in this data set

Aluminum_params<-c("Aluminum") #only values for aluminum
data_aluminum_dissolved<-data[data$CharacteristicName%in%Aluminum_params,] #want to match all records to the vector we created above which have calcium
unique(data_aluminum_dissolved$ResultSampleFractionText)
temp<-data_aluminum_dissolved %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep


###create dataset to check for non numeric objects in dataset
temp<-data_aluminum_dissolved %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change
data_aluminum_dissolved<-data_aluminum_dissolved %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_aluminum_dissolved$ResultMeasure.MeasureUnitCode) #checked units
unique(data_aluminum_dissolved$DetectionQuantitationLimitMeasure.MeasureUnitCode) #checked units - all NA's - won't have to convert any detection limits

#resultmeasurecode - all in ug/l which is lagos units - no conversion needed


data_aluminum_dissolved$CharacteristicName<-"Aluminum, dissolved"
#completed


```


```{r}
#Magnesium

Magnesium_params<-c("Magnesium") #only values for magnesium
data_magnesium<-data[data$CharacteristicName%in%Magnesium_params,] #want to match all records to the vector we created above which have calcium
unique(data_magnesium$ResultSampleFractionText)
temp<-data_magnesium %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep



###create dataset to check for non numeric objects in dataset
temp<-data_magnesium %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change
data_magnesium<-data_magnesium %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_magnesium$ResultMeasure.MeasureUnitCode) #checked units
unique(data_magnesium$DetectionQuantitationLimitMeasure.MeasureUnitCode) #checked units

#need to convert ug/l to mg/l for resultsvalues, no changes needed for detection limits

data_magnesium<-resultconvert(dat = data_magnesium, variable = "Magnesium", unit = "ug/l", out_unit = "mg/l", conv_factor = 1/1000)
unique(data_magnesium$ResultMeasure.MeasureUnitCode) #checked units

data_magnesium$CharacteristicName<-"Magnesium, dissolved"

#completed
```

```{r}
#selenium total

Selenium_params<-c("Selenium") #only values for selenium
data_selenium_total<-data[data$CharacteristicName%in%Selenium_params,] #want to match all records to the vector we created above which have calcium
unique(data_selenium_total$ResultSampleFractionText)
temp<-data_selenium_total %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep
fractionkeep<-c("Total")
data_selenium_total<-data_selenium_total[which(data_selenium_total$ResultSampleFractionText %in% fractionkeep | is.na(data_selenium_total$ResultSampleFractionText)),] 
unique(data_selenium_total$ResultSampleFractionText)



###create dataset to check for non numeric objects in dataset
temp<-data_selenium_total %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change # 2 NA - can change
data_selenium_total<-data_selenium_total %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_selenium_total$ResultMeasure.MeasureUnitCode)#checked units
unique(data_selenium_total$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#units matched - all ug/l - this is lagos units - no conversions needed

data_selenium_total$CharacteristicName<-"Selenium, total"

#completed
```


```{r}
#selenium dissolved

Selenium_params<-c("Selenium") #only values for selenium
data_selenium_dissolved<-data[data$CharacteristicName%in%Selenium_params,] #want to match all records to the vector we created above which have calcium
unique(data_selenium_dissolved$ResultSampleFractionText)
temp<-data_selenium_dissolved %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep
fractionkeep<-c("Dissolved")
data_selenium_dissolved<-data_selenium_dissolved[which(data_selenium_dissolved$ResultSampleFractionText %in% fractionkeep | is.na(data_selenium_dissolved$ResultSampleFractionText)),] 
unique(data_selenium_dissolved$ResultSampleFractionText)



###create dataset to check for non numeric objects in dataset
temp<-data_selenium_dissolved %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change # 2 NA - can change
data_selenium_dissolved<-data_selenium_dissolved %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_selenium_dissolved$ResultMeasure.MeasureUnitCode)#checked units
unique(data_selenium_dissolved$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#units matched - all ug/l - this is lagos units - no conversions needed

data_selenium_dissolved$CharacteristicName<-"Selenium, dissolved"


#completed
```


```{r}
#arsenic total

Arsenic_params<-c("Arsenic") #only values for arsenic
data_arsenic_total<-data[data$CharacteristicName%in%Arsenic_params,] #want to match all records to the vector we created above which have calcium
unique(data_arsenic_total$ResultSampleFractionText)
temp<-data_arsenic_total %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep
fractionkeep<-c("Total")
data_arsenic_total<-data_arsenic_total[which(data_arsenic_total$ResultSampleFractionText %in% fractionkeep | is.na(data_arsenic_total$ResultSampleFractionText)),] 
unique(data_arsenic_total$ResultSampleFractionText)



###create dataset to check for non numeric objects in dataset
temp<-data_arsenic_total %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change #714 NA's - can change
data_arsenic_total<-data_arsenic_total %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_arsenic_total$ResultMeasure.MeasureUnitCode)#checked units
unique(data_arsenic_total$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#already in ug/l - lagos units 

data_arsenic_total$CharacteristicName<-"Arsenic, total"


#completed

```

```{r}
#arsenic dissolved

Arsenic_params<-c("Arsenic") #only values for arsenic
data_arsenic_dissolved<-data[data$CharacteristicName%in%Arsenic_params,] #want to match all records to the vector we created above which have calcium
unique(data_arsenic_dissolved$ResultSampleFractionText)
temp<-data_arsenic_dissolved %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep
fractionkeep<-c("Dissolved")
data_arsenic_dissolved<-data_arsenic_dissolved[which(data_arsenic_dissolved$ResultSampleFractionText %in% fractionkeep | is.na(data_arsenic_dissolved$ResultSampleFractionText)),] 
unique(data_arsenic_dissolved$ResultSampleFractionText)



###create dataset to check for non numeric objects in dataset
temp<-data_arsenic_dissolved %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change #714 NA's - can change
data_arsenic_dissolved<-data_arsenic_dissolved %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_arsenic_dissolved$ResultMeasure.MeasureUnitCode)#checked units
unique(data_arsenic_dissolved$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#already in ug/l - lagos units 

data_arsenic_dissolved$CharacteristicName<-"Arsenic, dissolved"


#completed

```

```{r}
#silica

Silica_params<-c("Silica") #only values for silica
data_silica<-data[data$CharacteristicName%in%Silica_params,] #want to match all records to the vector we created above which have calcium
unique(data_silica$ResultSampleFractionText)
temp<-data_silica %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep



###create dataset to check for non numeric objects in dataset
temp<-data_silica %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change
data_silica<-data_silica %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_silica$ResultMeasure.MeasureUnitCode) #checked units
unique(data_silica$DetectionQuantitationLimitMeasure.MeasureUnitCode)
temp<-data_silica[which(!is.na(data_silica$DetectionQuantitationLimitMeasure.MeasureUnitCode) & data_silica$ResultMeasure.MeasureUnitCode != data_silica$DetectionQuantitationLimitMeasure.MeasureUnitCode),] #checks to see if detection limit units same as obvs units


data_silica$CharacteristicName<-"Silica, dissolved"
#completed

```

```{r}
#chloride

Chloride_params<-c("Chloride") #only values for chloride
data_chloride<-data[data$CharacteristicName%in%Chloride_params,] #want to match all records to the vector we created above which have calcium
unique(data_chloride$ResultSampleFractionText)
fractionkeep<-c("Dissolved")
data_chloride<-data_chloride[which(data_chloride$ResultSampleFractionText %in% fractionkeep | is.na(data_chloride$ResultSampleFractionText)),] #keeping if it's ones we chose or NA
unique(data_chloride$ResultSampleFractionText)
temp<-data_chloride %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep



###create dataset to check for non numeric objects in dataset
temp<-data_chloride %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change
data_chloride<-data_chloride %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_chloride$ResultMeasure.MeasureUnitCode) #checked units
unique(data_chloride$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#alreading in mg/l - lagos units - no conversion needed


data_chloride$CharacteristicName<-"Chloride, dissolved"

```
```{r}
#oxygen

Oxygen_params<-c("Dissolved oxygen (DO)") #only values for oxygen
data_oxygen<-data[data$CharacteristicName%in%Oxygen_params,] #want to match all records to the vector we created above which have oxygen
unique(data_oxygen$ResultSampleFractionText)
temp<-data_oxygen %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep
#both types are dissolved oxygen - convert all characteristic names to oxygen



###create dataset to check for non numeric objects in dataset
temp<-data_oxygen %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change #1 NA observation - can change
data_oxygen<-data_oxygen %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_oxygen$ResultMeasure.MeasureUnitCode) #checked units
unique(data_oxygen$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#already in lagos units - mg/l - no conversion needed

data_oxygen$CharacteristicName<-"Oxygen, dissolved"

#completed

```


```{r}
#chlorophyll

unique(data$CharacteristicName)


Chla_params<-c("Chlorophyll a") #only values for Chl
data_chla<-data[data$CharacteristicName%in%Chla_params,] #want to match all records to the vector we created above which have chl
unique(data_chla$ResultSampleFractionText)
temp<-data_chla %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep



###create dataset to check for non numeric objects in dataset
temp<-data_chla %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change #27 NA's - can change
data_chla<-data_chla%>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_chla$ResultMeasure.MeasureUnitCode) #checked units
unique(data_chla$DetectionQuantitationLimitMeasure.MeasureUnitCode)
#results and detection limit both in ug/l - Lagos units - no conversions needed
#completed


data_chla$CharacteristicName<-"Chlorophyll a"

```


```{r}
# pH

pH_params<-c("pH") #only values for pH
data_pH<-data[data$CharacteristicName%in%pH_params,] #want to match all records to the vector we created above which have pH
unique(data_pH$ResultSampleFractionText)
temp<-data_pH %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep



###create dataset to check for non numeric objects in dataset
temp<-data_pH %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change
data_pH<-data_pH %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_pH$ResultMeasure.MeasureUnitCode) #checked units
unique(data_pH$DetectionQuantitationLimitMeasure.MeasureUnitCode)

temp<-filter(data_pH, DetectionQuantitationLimitMeasure.MeasureUnitCode == "None")

#convert text - from none to pH - (for resultmeasurevalue) data is correct, but mislabelled - detection limits are all NA's

data_pH$ResultMeasure.MeasureUnitCode<-"pH"
unique(data_pH$ResultMeasure.MeasureUnitCode)

data_pH$CharacteristicName<-"pH, equilibrated"


#completed
```


```{r}
#sulfate
Sulfate_params<-c("Sulfate") #only values for sulfate
data_sulfate<-data[data$CharacteristicName%in%Sulfate_params,] #want to match all records to the vector we created above which have calcium
unique(data_sulfate$ResultSampleFractionText)
temp<-data_sulfate %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep



###create dataset to check for non numeric objects in dataset
temp<-data_sulfate %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change
data_sulfate<-data_sulfate %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_sulfate$ResultMeasure.MeasureUnitCode) #checked units
unique(data_sulfate$DetectionQuantitationLimitMeasure.MeasureUnitCode)


data_sulfate$CharacteristicName<-"Sulfate, dissolved"

#already in mg/l - no conversion needed

```

```{r}
#turbidity

Turbidity_params<-c("Turbidity") #only values for calcium
data_turb<-data[data$CharacteristicName%in%Turbidity_params,] #want to match all records to the vector we created above which have calcium
unique(data_turb$ResultSampleFractionText)
temp<-data_turb %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep



###create dataset to check for non numeric objects in dataset
temp<-data_turb %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change #73 NA's - can change
data_turb<-data_turb %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_turb$ResultMeasure.MeasureUnitCode) #checked units
unique(data_turb$DetectionQuantitationLimitMeasure.MeasureUnitCode)

data_turb$CharacteristicName<-"Turbidity"

#detection limit is in NTU - lagos units - don't need to change
#completed

```

```{r}
#carbon total (TC)

Carbon_params<-c("Carbon", "Organic carbon") #only values for carbon
data_tc<-data[data$CharacteristicName%in%Carbon_params,] #want to match all records to the vector we created above which have calcium
unique(data_tc$ResultSampleFractionText)
fractionkeep<-c("Total")
data_tc<-data_tc[which(data_tc$ResultSampleFractionText %in% fractionkeep | is.na(data_tc$ResultSampleFractionText)),] #keeping if it's ones we chose or NA
unique(data_tc$ResultSampleFractionText)
#not taking carbon data - this is only filterable carbon - we want organic total carbon

temp<-data_tc%>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change - 15 NA - can change
data_tc<-data_tc %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_tc$ResultMeasure.MeasureUnitCode) #checked units
unique(data_tc$DetectionQuantitationLimitMeasure.MeasureUnitCode)

data_tc$CharacteristicName<-"Carbon, total organic"


#both in mg/l - lagos units - no conversion needed

#completed
```

```{r}
#carbon dissolved total (TDC)

Carbon_params<-c("Carbon", "Organic carbon") #only values for carbon
data_tdc<-data[data$CharacteristicName%in%Carbon_params,] #want to match all records to the vector we created above which have calcium
unique(data_tdc$ResultSampleFractionText)
fractionkeep<-c("Dissolved")
data_tdc<-data_tdc[which(data_tdc$ResultSampleFractionText %in% fractionkeep | is.na(data_tdc$ResultSampleFractionText)),] #keeping if it's ones we chose or NA
unique(data_tdc$ResultSampleFractionText)
#not taking carbon data - this is only filterable carbon - we want organic total carbon

temp<-data_tdc%>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change - 15 NA - can change
data_tdc<-data_tdc %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_tdc$ResultMeasure.MeasureUnitCode) #checked units
unique(data_tdc$DetectionQuantitationLimitMeasure.MeasureUnitCode)

data_tdc$CharacteristicName<-"Carbon, dissolved organic"


#both in mg/l - lagos units - no conversion needed

#completed
```

```{r}
#alkalinity


Alk_params<-c("Alkalinity, total") #only values for alkalinity
data_alk<-data[data$CharacteristicName%in%Alk_params,] #want to match all records to the vector we created above which have calcium
unique(data_alk$ResultSampleFractionText) #keeping both total and dissolved
temp<-data_alk %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep



###create dataset to check for non numeric objects in dataset
temp<-data_alk %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change - 1 NA - can change
data_alk<-data_alk %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_alk$ResultMeasure.MeasureUnitCode) #checked units
unique(data_alk$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#need to convert mg/l to ueq/l for both resultsvalues and detectionlimits



#converting alk total from mg/l to ueq/l
data_alk<-resultconvert(dat = data_alk, variable = "Alkalinity, total", unit = "mg/l", out_unit = "ueq/l", conv_factor = 19.98)
unique(data_alk$ResultMeasure.MeasureUnitCode)

#convert mg/l caco3 to ueq/l for detection limits
data_alk<-detectconvert(dat = data_alk, variable = "Alkalinity, total", unit = "mg/l", out_unit = "ueq/L", conv_factor = 19.98)
unique(data_alk$DetectionQuantitationLimitMeasure.MeasureUnitCode)

data_alk$CharacteristicName<-"Alkalinity"

#completed

```

```{r}
#TSS

Tss_params<-c("Total suspended solids") #only values for tss
data_tss<-data[data$CharacteristicName%in%Tss_params,] #want to match all records to the vector we created above which have calcium
unique(data_tss$ResultSampleFractionText)
temp<-data_tss %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep


###create dataset to check for non numeric objects in dataset
temp<-data_tss %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change #184 NA's - can change
data_tss<-data_tss %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_tss$ResultMeasure.MeasureUnitCode) #checked units
unique(data_tss$DetectionQuantitationLimitMeasure.MeasureUnitCode)

data_tss$CharacteristicName<-"Solids, total suspended"

#units in mg/l - lagos units - no conversions needed
#completed

```
```{r}
###DIP (dissolved inorganic phosphorus)

unique(data$CharacteristicName)

DIP_params<-c("Orthophosphate", "Phosphate-phosphorus") #only values for DIP
data_DIP<-data[data$CharacteristicName%in%DIP_params,] #want to match all records to the vector we created above which have DIP
unique(data_DIP$ResultSampleFractionText)
temp<-data_DIP %>% filter(is.na(ResultSampleFractionText))
unique(temp$CharacteristicName) #this characteristic name is typically associated with dissolved 
fractionkeep<-c("Dissolved")
data_DIP<-data_DIP[which(data_DIP$ResultSampleFractionText %in% fractionkeep | is.na(data_DIP$ResultSampleFractionText)),]
unique(data_DIP$ResultSampleFractionText)


###create dataset to check for non numeric objects in dataset
temp<-data_DIP %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values - if NA's not losing any other data - can change
#394 NA's - can change
data_DIP<-data_DIP %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA


unique(data_DIP$ResultMeasure.MeasureUnitCode) #check units
unique(data_DIP$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#working withOrthophosphate

temp<-filter(data_DIP, CharacteristicName == "Orthophosphate")
unique(temp$ResultMeasure.MeasureUnitCode)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)

#convert orthophosphate mg/l as PO4 to ug/L
#convert orthophosphate mg/l to ug/L #assuming it is PO4 even though it doesnt mention - we noticed it's dissolved - we;re assumming

data_DIP<-resultconvert(dat = data_DIP, variable = "Orthophosphate", unit = "mg/l", out_unit = "ug/L", conv_factor = 326.1)
data_DIP<-detectconvert(dat = data_DIP, variable = "Orthophosphate", unit = "mg/l", out_unit = "ug/L", conv_factor = 326.1)


data_DIP<-resultconvert(dat = data_DIP, variable = "Orthophosphate", unit = "mg/l asPO4", out_unit = "ug/L", conv_factor = 326.1)
data_DIP<-detectconvert(dat = data_DIP, variable = "Orthophosphate", unit = "mg/l asPO4", out_unit = "ug/L", conv_factor = 326.1)

data_DIP<-resultconvert(dat = data_DIP, variable = "Orthophosphate", unit = "mg/l as P", out_unit = "ug/L", conv_factor = 1000)
data_DIP<-detectconvert(dat = data_DIP, variable = "Orthophosphate", unit = "mg/l as P", out_unit = "ug/L", conv_factor = 1000)


temp<-filter(data_DIP, CharacteristicName == "Orthophosphate")
unique(temp$ResultMeasure.MeasureUnitCode)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)


#working with Phosphate-phosphorus

temp<-filter(data_DIP, CharacteristicName == "Phosphate-phosphorus")
unique(temp$ResultMeasure.MeasureUnitCode)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)

data_DIP<-resultconvert(dat = data_DIP, variable = "Phosphate-phosphorus", unit = "mg/l", out_unit = "ug/L", conv_factor = 326.1)
data_DIP<-detectconvert(dat = data_DIP, variable = "Phosphate-phosphorus", unit = "mg/l", out_unit = "ug/L", conv_factor = 326.1)

temp<-filter(data_DIP, CharacteristicName == "Phosphate-phosphorus")
unique(temp$ResultMeasure.MeasureUnitCode)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)

data_DIP$CharacteristicName<-"Phosphorus, soluable reactive orthophosphate"


#COMPLETED

```



```{r}
#TKN #kjeldahl

unique(data$CharacteristicName)

TKN_params<-c("Kjeldahl nitrogen") #only values for TKN
data_TKN<-data[data$CharacteristicName%in%TKN_params,] #want to match all records to the vector we created above which have TKN
unique(data_TKN$ResultSampleFractionText)
temp<-data_TKN %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep
fractionkeep<-c("Total")
data_TKN<-data_TKN[which(data_TKN$ResultSampleFractionText %in% fractionkeep | is.na(data_TKN$ResultSampleFractionText)),] #keeping if it's ones we chose or NA
unique(data_TKN$ResultSampleFractionText)


###create dataset to check for non numeric objects in dataset
temp<-data_TKN %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change - 2 NA's - can change
data_TKN<-data_TKN %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_TKN$ResultMeasure.MeasureUnitCode)
unique(data_TKN$DetectionQuantitationLimitMeasure.MeasureUnitCode)#checked units

#all are mg/l - convert to ug/l

data_TKN<-resultconvert(dat = data_TKN, variable = "Kjeldahl nitrogen", unit = "mg/l", out_unit = "ug/l", conv_factor = 1000)
data_TKN<-detectconvert(dat = data_TKN, variable = "Kjeldahl nitrogen", unit = "mg/l", out_unit = "ug/l", conv_factor = 1000)


#check to see everything converted 
temp<-data_TKN %>% filter(CharacteristicName == "Kjeldahl nitrogen")
unique(temp$ResultMeasure.MeasureUnitCode)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)

data_TKN$CharacteristicName<-"Nitrogen, total Kjeldahl"

#COMPLETED

```


```{r}
#TDKN #kjeldahl

unique(data$CharacteristicName)

TDKN_params<-c("Kjeldahl nitrogen") #only values for TKN
data_TDKN<-data[data$CharacteristicName%in%TDKN_params,] #want to match all records to the vector we created above which have TKN
unique(data_TDKN$ResultSampleFractionText)
temp<-data_TDKN %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep
fractionkeep<-c("Dissolved")
data_TDKN<-data_TDKN[which(data_TDKN$ResultSampleFractionText %in% fractionkeep | is.na(data_TDKN$ResultSampleFractionText)),] #keeping if it's ones we chose or NA
unique(data_TDKN$ResultSampleFractionText)


###create dataset to check for non numeric objects in dataset
temp<-data_TDKN %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change - 2 NA's - can change
data_TDKN<-data_TDKN %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_TDKN$ResultMeasure.MeasureUnitCode)
unique(data_TDKN$DetectionQuantitationLimitMeasure.MeasureUnitCode)#checked units

#convert mg/l and mg/l as N to ug/l for result measure value - detection limits all NAs

data_TDKN<-resultconvert(dat = data_TDKN, variable = "Kjeldahl nitrogen", unit = "mg/l", out_unit = "ug/l", conv_factor = 1000)
data_TDKN<-resultconvert(dat = data_TDKN, variable = "Kjeldahl nitrogen", unit = "mg/l as N", out_unit = "ug/l", conv_factor = 1000)


#check to see everything converted 
temp<-data_TDKN %>% filter(CharacteristicName == "Kjeldahl nitrogen")
unique(temp$ResultMeasure.MeasureUnitCode)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)

data_TDKN$CharacteristicName<-"Nitrogen, dissolved Kjeldahl"



#COMPLETED

```


```{r}

#Ammonia

unique(data$CharacteristicName)

NH4_params<-c("Ammonia-nitrogen") #only values for TN
data_ammonia<-data[data$CharacteristicName%in%NH4_params,] #want to match all records to the vector we created above which have TP
unique(data_ammonia$ResultSampleFractionText)
temp<-data_ammonia %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep

###create dataset to check for non numeric objects in dataset
temp<-data_ammonia %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change #133 NA's - can change
data_ammonia<-data_ammonia %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_ammonia$ResultMeasure.MeasureUnitCode) #checked units
unique(data_ammonia$DetectionQuantitationLimitMeasure.MeasureUnitCode)


data_ammonia<-resultconvert(dat = data_ammonia, variable = "Ammonia-nitrogen", unit = "mg/l", out_unit = "ug/l", conv_factor = 1000)
data_ammonia<-detectconvert(dat = data_ammonia, variable = "Ammonia-nitrogen", unit = "mg/l", out_unit = "ug/l", conv_factor = 1000)



temp<-data_ammonia %>% filter(CharacteristicName == "Ammonia-nitrogen")
unique(temp$ResultMeasure.MeasureUnitCode)
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)

data_ammonia$CharacteristicName<-"Nitrogen, NH4"


#Completed
```


```{r}
#NO3 params

unique(data$CharacteristicName)

NO3_params<-c("Inorganic nitrogen (nitrate and nitrite)") #only values for DIN
data_NO3<-data[data$CharacteristicName%in%NO3_params,] #want to match all records to the vector we created above which have DIN
unique(data_NO3$ResultSampleFractionText)

temp<-data_NO3 %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep
#fractionkeep<-c("Dissolved")
#data_NO3<-data_NO3[which(data_NO3$ResultSampleFractionText %in% fractionkeep | is.na(data_NO3$ResultSampleFractionText)),] #keeping if it's ones we chose or NA
#unique(data_NO3$ResultSampleFractionText)

###create dataset to check for non numeric objects in dataset
temp<-data_NO3 %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change #142 NA's - can change
data_NO3<-data_NO3 %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_NO3$ResultMeasure.MeasureUnitCode)
unique(data_NO3$DetectionQuantitationLimitMeasure.MeasureUnitCode)


temp<-data_NO3 %>% filter(CharacteristicName == "Inorganic nitrogen (nitrate and nitrite)")
unique(temp$ResultMeasure.MeasureUnitCode) 
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)

temp2<-temp %>% filter(CharacteristicName == "Inorganic nitrogen (nitrate and nitrite)") %>% filter(ResultMeasure.MeasureUnitCode == "mg/l")
unique(temp2$ResultAnalyticalMethod.MethodName)
unique(temp2$ResultAnalyticalMethod.MethodIdentifier) #353.2 - written as N - do direct conversion 



data_NO3<-resultconvert(dat = data_NO3, variable = "Inorganic nitrogen (nitrate and nitrite)", unit = "mg/l", out_unit = "ug/l", conv_factor = 1000)
data_NO3<-detectconvert(dat = data_NO3, variable = "Inorganic nitrogen (nitrate and nitrite)", unit = "mg/l", out_unit = "ug/l", conv_factor = 1000)


data_NO3<-resultconvert(dat = data_NO3, variable = "Inorganic nitrogen (nitrate and nitrite)", unit = "mg/l as N", out_unit = "ug/l", conv_factor = 1000)
data_NO3<-detectconvert(dat = data_NO3, variable = "Inorganic nitrogen (nitrate and nitrite)", unit = "mg/l as N", out_unit = "ug/l", conv_factor = 1000)


temp<-data_NO3 %>% filter(CharacteristicName == "Inorganic nitrogen (nitrate and nitrite)")
unique(temp$ResultMeasure.MeasureUnitCode) 
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)


data_NO3$CharacteristicName<-"Nitrogen, nitrite (NO2) + nitrate (NO3)"

#completed

```


```{r}

#nitrite (NO2)

unique(data$CharacteristicName)

NO2_params<-c("Nitrite") #only values for DIN
data_NO2<-data[data$CharacteristicName%in%NO2_params,] #want to match all records to the vector we created above which have DIN
unique(data_NO2$ResultSampleFractionText)

temp<-data_NO2 %>% filter(is.na(ResultSampleFractionText)) #to check NA's or anything unclear - we check and decide what to keep
#fractionkeep<-c("Dissolved")
#data_NO2<-data_NO2[which(data_NO2$ResultSampleFractionText %in% fractionkeep | is.na(data_NO2$ResultSampleFractionText)),] #keeping if it's ones we chose or NA
#unique(data_NO2$ResultSampleFractionText)

###create dataset to check for non numeric objects in dataset
temp<-data_NO2 %>% filter(is.na(as.numeric(ResultMeasureValue)))  #checks for non numeric values in result measure value - if NA's not losing any other data - can change #142 NA's - can change
data_NO2<-data_NO2 %>% mutate(ResultMeasureValue = as.numeric(ResultMeasureValue)) # non numeric values become NA

unique(data_NO2$ResultMeasure.MeasureUnitCode)
unique(data_NO2$DetectionQuantitationLimitMeasure.MeasureUnitCode)

temp<-data_NO2 %>% filter(CharacteristicName == "Nitrite")
unique(temp$ResultMeasure.MeasureUnitCode) 
unique(temp$DetectionQuantitationLimitMeasure.MeasureUnitCode)

temp2<-temp %>% filter(CharacteristicName == "Nitrite") %>% filter(ResultMeasure.MeasureUnitCode == "mg/l")
unique(temp2$ResultAnalyticalMethod.MethodName)
unique(temp2$ResultAnalyticalMethod.MethodIdentifier) #354.1 - written as Nitrogen nitrite - do direct conversion 


data_NO2<-resultconvert(dat = data_NO2, variable = "Nitrite", unit = "mg/l as N", out_unit = "ug/l", conv_factor = 1000)
data_NO2<-detectconvert(dat = data_NO2, variable = "Nitrite", unit = "mg/l as N", out_unit = "ug/l", conv_factor = 1000)


data_NO2<-resultconvert(dat = data_NO2, variable = "Nitrite", unit = "mg/l", out_unit = "ug/l", conv_factor = 1000)
data_NO2<-detectconvert(dat = data_NO2, variable = "Nitrite", unit = "mg/l", out_unit = "ug/l", conv_factor = 1000)


data_NO2<-resultconvert(dat = data_NO2, variable = "Nitrite", unit = "mg/l asNO2", out_unit = "ug/l", conv_factor = 0.3044*1000)
data_NO2<-detectconvert(dat = data_NO2, variable = "Nitrite", unit = "mg/l asNO2", out_unit = "ug/l", conv_factor = 0.3044*1000)


data_NO2$CharacteristicName<-"Nitrogen, nitrite (NO2)"

#completed

```


```{r}

alldata_DE<-rbind(data_secchi, data_calcium, data_aluminum_dissolved,  data_magnesium, data_selenium_total, data_selenium_dissolved, data_arsenic_total, data_arsenic_dissolved, data_silica, data_chloride, data_oxygen, data_chla, data_pH, data_sulfate, data_turb, data_tc, data_tdc, data_alk, data_tss, data_DIP, data_TKN, data_TDKN, data_ammonia, data_NO3, data_NO2)     



write.csv(alldata_DE, file = "alldata_DE.csv", row.names = FALSE)

```

